[해시] 1단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #12
Opened 2023-02-16 06:57 UTC by EmilyCh0

1단계 로또 제출합니다.
바쁘신 와중에 시간 내어 리뷰해 주셔서 감사합니다 😄

2023-02-16 07:04 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/LottoResult.kt
> +}
이 함수가 클래스 내부에서 사용되지는 않지만 LottoResult와 관련된 메서드라고 생각해서 해당 클래스 companion object에 작성했는데 `valueOf()` 메서드를 사용하는 Lotto 클래스에 작성하는 것이 더 좋을지 궁금합니다.

2023-02-17 01:11 UTC, namjackson requested changes
안녕하세요 해시님! 
로또 미션을함께하게된 잭슨(조남재)라고합니다! 
잘부탁드립니다! 
미션 진행을 잘해주셨네요! 몇가지 고민할법한 포인트들 코멘트로 남겼으니, 확인해주세요!

2023-02-17 01:11 UTC, namjackson commented on src/main/kotlin/domain/model/LottoResult.kt
> +}
팩토리 함수 형태의 함수는 자주 사용합니다 !
가볍게 읽어보시면 좋을거같아요! 

https://kyucumber.github.io/posts/book/effective-kotlin/effective-kotlin-item-33

2023-02-17 12:19 UTC, EmilyCh0 commented on src/main/kotlin/domain/LottoGenerator.kt
> +        domain.LottoGenerator.NUMBER_UNIT_ERROR
제거했습니다!

2023-02-17 12:19 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/LottoResult.kt
> +    SECOND(30_000_000, 5),
아래 코드처럼 matchBonus를 관리한다는 의미이실까요? 그러면 보너스 번호 일치 여부와 관련 없는 FIRST, FORTH, FIFTH, MISS의 matchBonus 값은 어떻게 해야 할지가 고민인데 제가 맞게 이해한 것인지 궁금합니다.

```kotlin
enum class LottoResult(val prizeMoney: Int, val matchCount: Int, val matchBonus: Boolean) {
		...
    THIRD(1_500_000, 5, false),
    SECOND(30_000_000, 5, true),
```

2023-02-17 12:21 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/WinningNumbers.kt
> +    val catchNumbers: Set<Int>,
LottoNumber 클래스로 분리해서 번호 관련 로직을 처리하도록 했습니다. 또한 팩토리 함수를 사용해서 LottoNumber의 생성자 역할을 대신하도록 했습니다!

2023-02-17 12:22 UTC, EmilyCh0 commented on src/main/kotlin/domain/ProfitCalculator.kt
> +    fun getProfit(purchaseMoney: PurchaseMoney, lottoResults: List<LottoResult>) =
리턴값을 명시해서 직관적으로 파악할 수 있도록 수정했습니다!

2023-02-17 12:24 UTC, EmilyCh0 commented on src/test/kotlin/LottoTest.kt
> +        assertThrows<IllegalArgumentException> {
다른 예외에 걸려서 의도치 않은 결과가 발생할 수 있겠네요..! 에러 메시지도 확인하도록 수정했습니다.

2023-02-17 12:25 UTC, EmilyCh0 commented on src/test/kotlin/LottoTest.kt
> +    fun `당첨 결과가 1등인 경우`() {
구체적인 테스트명으로 수정했습니다!

2023-02-17 12:28 UTC, EmilyCh0 commented on src/test/kotlin/LottoTest.kt
> +        )
가독성을 높이기 위해 given, when, then 주석 표기를 추가했습니다. LottoNumber 클래스를 분리하다 보니 각 테스트가 많이 길어졌는데 이 부분도 개선이 필요할까요?

2023-02-18 07:14 UTC, namjackson approved these changes
안녕하세요 해시님!
피드백 적용 잘해주셧네요! 😄 
질문주신부분은 코멘트 남겼으니 확인해주세요!
2단계 진행해주시면 좋을거같아요! 👍

2023-02-18 07:14 UTC, namjackson commented on src/test/kotlin/LottoTest.kt
> +        )
Lotto 생성 코드가 길어졌네요!
테스트코드내 Lotto 생성하는 코드를 함수로 분리하거나 팩토리 메소드 패턴을 사용해보셔도 좋을거 같아요! 
다음 미션인 수동 로또 생성과도 연결된 포인트이니, 다음 미션진행하면서 고민해보세요! 😄

2023-02-18 07:14 UTC, merged