[산군] 1단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #18
Opened 2023-02-16 08:36 UTC by s9hn

안녕하세요

2023-02-17 02:04 UTC, namjackson commented
> 원시값 객체를 이렇게까지 만들어줘야 하는지

원시값 포장의 장담점은 무엇이라고 생각하시나요?
사실 모든 원시값을 포장할필요는 없다고 생각이 들어요. 
하지만 장점이 있는 만큼, 원시값에 의미가 있다면 포장하면 장점들이 있다고 생각이합니다!
https://tecoble.techcourse.co.kr/post/2020-05-29-wrap-primitive-type/
가볍게 읽어보셔도 좋을거같아요!


> 입력값에 대한 예외처리, 어디서 해주는게 좋은지
> 입력값에 대한 예외처리 후, 해당 값을 사용하는 도메인에서 재검사를 진행하는지 혹은 원시값 포장 객체에서 해주어야하는지

구현에 대한 부분이라, 정답이 없는 문제네요 ㅠㅠ
개인적으로는 입력화면에 대한 책임도 있을수 있지만, 입력 화면은 사용자의 입력만을 받고, 도메인영역에서의 책임이 크다고 생각해요!
View는 자주 변경되기도 하고, 협업이나 다른곳에서 도메인 코드를 사용해야할수도 있기때문에,
도메인영역에서 방어적 로직를 구현하는게 좋다고 생각이 들어요!

> 매개변수로 넘기는것과 글로벌필드에 프로퍼티로 두는 것 중 어느방법이 더 좋은지

이부분도 케이스마다 다를것 같아요, 해당 객체가 어떤 책임이 있는지를 고려하셔서 구현해보시면 어떨까요?
프로퍼티로 들고있으면 상태관리를 해야하기때문에, 그럴만한 책임 이없다면, 매개변수로 사용이 좋지않을까 생각합니다!

> 인라인화 하는것과 가독성을 위해 컨테이너 변수애 담아서 넣어주는것 중 무엇이 더 좋은방법인지

인라인화하는것과 컨테이너 변수에 담는다는것은 어떤부분을 말씀하시는걸까욤? 
이부분도 케이스마다 다를것 같은데 구체적인 예시가 있으면 좋을거같아요!

2023-02-17 02:05 UTC, namjackson requested changes
안녕하세요 산군님
로또 미션을 함께하게된 잭슨(조남재) 라고합니다!
잘부탁드려요! 
미션 수행 장해주셨어요! 
몇가지 고민할법한 포인트들, 질문을 코멘트로 남겼으니, 확인해주세요!

2023-02-22 06:43 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +        }
정확히 수행했는지, 모르겠지만, 
구글링을 통해 lottoCount만큼의 List를 생성하고, 
각 list에 lottoMachine.generateLotto()를 호출해 로또를 생성해주고, 리턴해주는 식으로 수정하였습니다!
감사합니다!
커밋반영

2023-02-22 06:47 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +        return count.number
적용했습니다! Int타입 -> Count타입으로 변경하니, 훨씬 더 함수명과 어울리고 가독성이 좋아진 걸 느꼈습니다! 
감사합니다!
커밋반영

2023-02-22 09:07 UTC, s9hn commented on src/main/kotlin/domain/Rank.kt
> +    THIRD(5, 1_500_000),
Rank내부에서 Rank를 결정짓는 함수를 open키워드를 이용해, 2등과 MISS일때만 override해주는 식으로 바꾸어주었습니다!
감사합니다!

2023-02-22 10:45 UTC, s9hn commented on src/main/kotlin/domain/ShuffledNumberGenerator.kt
> +        repeat(MAXIMUM_LOTTO_NUMBER) { lottoNumbers.add(LottoNumber(lottoNumber++)) }
원시타입을 처음 적용해보아서 range를 적용할 생각을 못했습니다!
range적용 후, 리턴단계에서 wrapping해주는 식으로 수정했습니다!
감사합니다!

2023-02-22 11:02 UTC, s9hn commented on src/main/kotlin/model/BonusNumber.kt
> +        lotto.lottoNumbers.forEach { lottoNumber ->
contains를 사용해 한줄로 줄였습니다!
감사합니다!

2023-02-22 12:15 UTC, s9hn commented on src/main/kotlin/model/BonusNumber.kt
> +    }
프로퍼티에서 바로 사용할 수 있도록 수정하였습니다!
감사합니다!

2023-02-22 12:23 UTC, s9hn commented on src/main/kotlin/model/Lotto.kt
> +        }
map을 활용해 바로 리스트를 만들어 반환하도록 수정하였습니다!
감사합니다!

2023-02-23 02:40 UTC, s9hn commented on src/main/kotlin/domain/LottoAdministrator.kt
> +    }
이 부분이 살짝 어려웠는데, 맞게 구현한건지 잘 모르겠습니다!
Lotto Class내부에서, 상태와 행위를 한 곳에서 관리해야함은 이해했습니다!
getMatchOfNumber 함수를 Lotto Class내로 옮겨주고, isMatchBonus 함수 또한 Lotto Class 내부로 옮겨주면, 굳이 LottoAdministrator라는 클래스가 필요할까..라는 의문이 듭니다!

커밋내역

2023-02-23 05:49 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +    private fun printLottoResult(lotteries: List<Lotto>, winningNumber: Lotto, bonusNumber: BonusNumber) {
안녕하세요 잭슨님! 리뷰요청을 눌러야했군요..!
너무 많이 늦어서 죄송합니다! (이해안가고 쌓인 지식들이 많아 차근차근 정리하다보니..)
리뷰 모두 확인하고 수정했습니다! 리뷰는 리뷰어님 사정에 맞추어 천천히 해주셔도 됩니다!
---
printLottoResult의 이름과 맞지않게, 너무 많은 일을 하고 있는 것 같아서 3개의 함수로 분리해보았습니다!
감사합니다!

2023-02-23 05:59 UTC, s9hn commented on src/main/kotlin/model/LottoResult.kt
> +    var result: HashMap<Rank, Int> = hashMapOf()
맞습니다! 빠르게 진행하다보니 놓친 부분 같습니다! 
감사합니다!

2023-02-23 06:17 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +            lottoResult.plusRankCount(rank!!, lottoResult.result)
Rank를 반환해주는 곳에서, 엘비스연산자를 이용하여 널처리해주었습니다!
감사합니다!

2023-02-23 07:01 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +    private fun printLottoResult(lotteries: List<Lotto>, winningNumber: Lotto, bonusNumber: BonusNumber) {
안녕하세요 잭슨님! 반갑습니다! 
너무 오래 기다리게 해 죄송합니다!(새로배운것들이 마구 쌓이다보니 정리할 시간이 필요했습니다 ㅠ,ㅠ)
남겨주신 리뷰들 모두 꼭꼭 씹어먹었습니다! 
앞으로의 리뷰는 리뷰어님 사정에 맞추어 천천히해주셔도 됩니다!
감사합니다!!

----
print라는 함수네이밍에 맞지않게 과분한 책임을 들고 있는 것 같습니다! 함수 3개로 분리해주었습니다! 
감사합니다!

2023-02-23 07:11 UTC, s9hn commented on src/main/kotlin/model/LottoResult.kt
> +    }
Rank클래스 내부의 프로퍼티를 은닉화해주었고, 외부로 전달하는 일 없이, 내부 컬렉션데이터를 조작하는 함수들은 모두 내부적으로 처리하고, 메시지만을 전달할 수 있도록 바꿔주었습니다!
감사합니다!

2023-02-23 07:11 UTC, s9hn commented on src/main/kotlin/model/LottoResult.kt
> +    fun getProfitRate(result: HashMap<Rank, Int>): Double {
😂위와 같이 수정했습니다!
감사합니다!

2023-02-23 07:16 UTC, s9hn commented on src/main/kotlin/domain/NumberGenerator.kt
> +interface NumberGenerator {
역할에 맞게 수정해주었습니다!
감사합니다!

2023-02-23 07:50 UTC, s9hn commented on src/main/kotlin/view/OutputView.kt
> +        )
가독성을 좀 높여주긴했는데, 맞는지 잘 모르겠습니다.. 어떤식으로 분리해주어야 할까요..?

2023-02-23 07:51 UTC, s9hn commented on src/test/kotlin/model/LottoNumberTest.kt
> +        }
감사합니다!

2023-02-23 07:51 UTC, s9hn commented on src/test/kotlin/model/LottoNumberTest.kt
> +    fun `당첨번호와 보너스번호는 1~45이다`() {
구체적인 테스트케이스와 네이밍 고민해보겠습니다!
감사합니다!

2023-02-24 04:25 UTC, namjackson requested changes
안녕하세요 산군님! 
피드백 적용잘해주셨네요!
몇가지 추가적인 내용 코멘트 남겼으니 확인해주세요!

2023-02-24 04:25 UTC, namjackson commented on src/main/kotlin/model/BonusNumber.kt
> +class BonusNumber(private val lotto: Lotto, val bonusNumber: LottoNumber) {
BonusNumber라는 클래스지만, 불필요해보이는 lotto 값도 프로퍼티를 가지고있네요,
이 클래스의 책임은 무엇일까요?

2023-02-24 04:25 UTC, namjackson commented on src/main/kotlin/model/LottoResult.kt
> +    }
함수를 통해 내부프로퍼티를 변경하게 되면, 
상태관리가 어려워지고, 관리하기가 까다롭습니다

updateRankCount함수가 아닌, 생성자를 통해 결과를 받아오면 어떨까요?

2023-02-24 04:25 UTC, namjackson commented on src/main/kotlin/domain/LottoAdministrator.kt
> +    }
LottoAdministrator의 책임에 대해 고민해보세요!
LottoAdministrator는 어떠한 역할을 하고있을까요?
불필요하다면 과감하게 제거해주셔도 좋을것 같아요! 

Administrator,Processor, Manager, Super 등과 같이 모호한 단어가 있는 경우, 불필요하거나, 여러가지의 책임이 혼재되어있는 경우가 있습니다!

2023-02-24 04:25 UTC, namjackson commented on src/main/kotlin/view/OutputView.kt
> +        )
Rank.values()를 활용해보면 어떨까요?
match,reward등의 정보를 하드코딩하기보다 Rank의 데이터를 사용하면 좋을거같아요!

2023-02-24 04:25 UTC, namjackson commented on src/test/kotlin/model/LottoTest.kt
> +class LottoTest {
Lotto 클래스내의 당첨을 확인하는 로직이 생긴부분도 테스트해보면 어떨까요?

2023-02-24 04:25 UTC, namjackson commented on src/test/kotlin/model/LottoTest.kt
> +        )
테스트의 준비 단계가 길어져서, 가독성이 안좋아진것 같아요! 
테스트내의 함수, 팩토리 함수, 가짜생성자 등을 활용해보면 어떨까요?

2023-02-24 04:55 UTC, s9hn commented on src/main/kotlin/domain/LottoAdministrator.kt
> +    }
다음 구현에선 LottoAdministrator 클래스를 없앨 생각입니다!
감사합니다!

2023-02-24 09:23 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +        val count = Seller(payment).getLottoCount()
오! 아무리봐도 Seller가 로또를 주는게 맞네요,, 손님이 돈을 지불했는데, 정작 로또는 안주고 있었군요,,, 신고당할뻔,,
감사합니다!

2023-02-26 09:11 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +    private val lottoResult: LottoResult,
lottoResult를 집계해주는 함수가 애초에 controller단에 있는게 이상한 것 같습니다! 따라서, 
lottoResult를 집계해주는 함수를 lottoResult로 옮긴 후, controller단에선, 결과만 받아오는 식으로 구현했습니다!

감사합니다!

2023-02-26 09:28 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +    }
로또 머신이 해주도록 바꾸었습니다!
감사합니다!

2023-02-26 12:56 UTC, s9hn commented on src/main/kotlin/LottoController.kt
> +    private fun readyLottoResult(lotteries: List<Lotto>, winningNumber: Lotto, bonusNumber: BonusNumber) {
winningNumber라는 하나의 클래스를 만들어주었고, 이 클래스 내에서 당첨번호와 보너스번호 모두를 갖고있을 수 있도록 수정하였습니다!
감사합니다!

2023-02-26 12:56 UTC, s9hn commented on src/main/kotlin/domain/LottoAdministrator.kt
> +        return Lotto(lottoNumbers).getMatchOfNumber(winningNumber)
본 클래스는 삭제했습니다!
감사합니다!

2023-02-26 12:57 UTC, s9hn commented on src/main/kotlin/domain/LottoAdministrator.kt
> +    fun getMatchOfNumber(lottoNumber: Lotto, winningNumber: Lotto): Int {
본 클래스는 삭제했습니다!
감사합니다!

2023-02-26 12:57 UTC, s9hn commented on src/main/kotlin/model/BonusNumber.kt
> +class BonusNumber(private val lotto: Lotto, val bonusNumber: LottoNumber) {
당첨번호와 보너스번호 모두를 들고 있는 winningNumber클래스로 바꿔주었습니다!
감사합니다!

2023-02-26 13:16 UTC, s9hn commented on src/main/kotlin/model/LottoResult.kt
> +    }
이 부분이 잘 이해가 가지 않아서.. 
이전 코드리뷰들을 통해, updateRankCount함수를 호출하는 코드를 LottoResult내부로 옮겨주었습니다.
해당 updateRankCount함수를 사용할 코드의 매개변수들을 생성자로 옮겨주었는데,, 맞게한건지 모르겠습니다!

2023-02-27 03:03 UTC, namjackson approved these changes
안녕하세요 산군님!
피드백 반영 잘해주셨네요!
추가적으로 코멘트 남겼으니, 
다음 미션 진행하시면서 확인해주세요! 🏃 🏃

2023-02-27 03:03 UTC, merged