[베르] 1단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #25
Opened 2023-02-16 08:57 UTC by SeongHoonC

먼저 리뷰 잘부탁드립니다!

이번 미션에서 페어 프로그래밍 진행하면서 질문이 생겼습니다.

1. 원시값을 포장하고 나서 객체를 사용할 때 마다 value를 뽑아서 쓰는 형태인데 맞는 것인지 의문이 듭니다.

2. 또한 입력이 숫자인지 검증하는 함수가 controller에서 작성되었는데 이 기능이 inputView에서 해야할지 혹은 Validator 클래스를 만들어서 해야할지 궁금합니다.  만약 Validator를 만든다면 validator 에서 값 검증만 수행할지 값 검증 후 값 변환까지 해야할 지 궁금합니다.

3. 한 번만 사용되고 상태를 갖지 않는 클래스를 오브젝트로 변경하는게 좋은지 외부에서 인자로 주입해 주는게 좋은지 궁금합니다.

감사합니다.

2023-02-16 14:41 UTC, vagabond95 commented
1. 넵 맞습니다. 어디선가는 값을 가져다 쓸 수 밖에 없기 때문에 value 를 뽑는 상황이 생기게 되고 이는 자연스러운 일입니다.
2. 각 컴포넌트 / 클래스의 역할은 무엇인지, 변경이 되어야한다면 무엇때문인지에 대해 고민해보시면 좋겠어요. validator 에 대한 역할 범위 역시 마찬가지로 정답이 없습니다만, 어느 방향이 추후에 변경에 용이할지 생각해보시면 방향성을 잡을 수 있을거 같습니다.
3. 오브젝트 사용에 대한 기준은 싱글턴 객체로 활용할 수 있는지를 살펴보시면 될 거 같습니다.

2023-02-16 14:42 UTC, vagabond95 requested changes
테스트 코드를 정말 꼼꼼히 잘 작성해주셨네요 👍 
원시값 포장도 놓치지 않고 잘 해주신 것 같습니다 ㅎㅎ

구현해주신 내용과 관련하여 몇가지 코멘트 남겼는데 확인 후 리뷰요청 부탁드려요!

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/LottoController.kt
> +        val lottoBunch = LottoBunch(lottoes)
lottoes 를 LottoBunch 에서 스스로 만들어주도록 리펙토링해보는 것은 어떨까요?
컨트롤러는 세부 도메인 요구사항은 알지 못하고, model 과 view 사이의 중계 역할만 하는 다소 멍청하고 게으른 상태를 유지해봐도 좋겠어요.

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/Validator.kt
> +    fun isNumber(value: String): Boolean = Pattern.matches("^[0-9]+$", value)
extension function 을 활용해봐도 좋겠어요!

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/Validator.kt
> +object Validator {
무엇을 검증하는지에 대한 구체적인 내용이 들어가면 좋을 것 같아요.
이름이 모호할수록 어떠한 역할이든 수행이 가능하고 이는 곧 코드를 비대하게 만들어주는 신호가 될 수 있다고 생각해요.

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/LottoController.kt
> +    ): Any {
1

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/constant/Rank.kt
> +    FIRST(6, 2000000000),
1

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/constant/Rank.kt
> +            if (matchCount == 5) {
특정 등수에 대한 조건문 없이 일관된 로직으로 등수를 구해볼 수 있을까요?
현재와 같은 구조는 보너스 번호가 다른 등수에도 추가되는 요구사항이 들어오면 계속 if 문이 추가될 수 밖에 없을 것 같아요.

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    val lottoNumbers: List<LottoNumber> = lottoNumbers.sortedBy { it.value }
도메인 레벨에서 정렬연산을 해줘야할 필요성이 있을까요?

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/constant/Rank.kt
> +    FIRST(6, 2000000000),
```suggestion
    FIRST(6, 2_000_000_000),
```
언더 스코어를 활용하면 조금 더 가독성을 확보할 수 있습니다 :)

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    override fun toString(): String = lottoNumbers.map { lottoNumber -> lottoNumber.value }.toString()
도메인에서 '어떻게 표현되는지'에 대해 다룰 필요가 있을까요~?

2023-02-16 14:42 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    override fun toString(): String = lottoNumbers.map { lottoNumber -> lottoNumber.value }.toString()
해당 도메인 모델외에 다른 곳에서의 toString() 역시 동일하게 참고 부탁드립니다 :)

2023-02-18 02:32 UTC, SeongHoonC commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    val lottoNumbers: List<LottoNumber> = lottoNumbers.sortedBy { it.value }
정렬 연산을 view에서 하도록 변경했습니다!

2023-02-18 02:33 UTC, SeongHoonC commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    override fun toString(): String = lottoNumbers.map { lottoNumber -> lottoNumber.value }.toString()
도메인에선 결과만 넘겨주고 view에서 형식을 만들어내도록 수정하였습니다!

2023-02-18 02:35 UTC, SeongHoonC commented on src/main/kotlin/lotto/constant/Rank.kt
> +            if (matchCount == 5) {
BonusResult enum class 를 만들어 세가지 분기를 만들고 BONUS_MATCH 일 때 참으로 조건을 변경하였습니다!

2023-02-18 02:38 UTC, SeongHoonC commented on src/main/kotlin/lotto/domain/Validator.kt
> +object Validator {
컨트롤러에서 검증하지 않고 InputView 에서 정수인지 체크하고 가공 후 컬렉션 혹은 값을 반환하는 형태로 변경하였습니다!

2023-02-18 02:39 UTC, SeongHoonC commented on src/main/kotlin/lotto/domain/Validator.kt
> +    fun isNumber(value: String): Boolean = Pattern.matches("^[0-9]+$", value)
String.toIntOrNull() 을 사용하여 변경하였습니다!

2023-02-18 02:39 UTC, SeongHoonC commented on src/main/kotlin/lotto/LottoController.kt
> +        val lottoBunch = LottoBunch(lottoes)
LottoBunch 에 팩토리를 넘겨주어 내부에서 value를 직접 생산하도록 변경하였습니다!

2023-02-19 04:05 UTC, vagabond95 approved these changes
리뷰가 조금 늦어져 죄송합니다 😿 😢 
코멘트 드렸던 내용을 모두 꼼꼼히 잘 반영해주셨네요!

특히 2등/ 보너스번호와 관련된 리펙토링은 처음에 많이 어려워 하시는 부분들인데 잘 접근해주신 것 같습니다 👍 
남긴 코멘트는 다음단계 진행시 참고 부탁드려요 :)
1단계는 머지하도록 하겠습니다!

2023-02-19 04:05 UTC, vagabond95 commented on src/main/kotlin/lotto/constant/Rank.kt
> +        fun convertToGrade(matchCount: Int, bonusResult: BonusResult): Rank {
bonusResult 도입 시도 좋습니다!

2023-02-19 04:05 UTC, vagabond95 commented on src/main/kotlin/lotto/LottoController.kt
> +    ): Any {
Any 를 리턴할 경우 매번 타입 캐스팅이 요구되므로 제네릭을 활용해보는 것은 어떨까요?

2023-02-19 04:05 UTC, merged