[써니] 1단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #3
Opened 2023-02-15 09:09 UTC by inseonyun

안녕하세요 리뷰어님 :)
로또 1단계 미션 제출합니다. 

페어와 함께 진행하며 객체 지향, MVC, 코틀린에 대해 배울 수 있어 좋았습니다.
아직 해당 지식이 많이 부족하다 보니 위배되는 점이 있는지 개선점 피드백 부탁드립니다!

리뷰 감사합니다! :)  😊

2023-02-15 18:13 UTC, namjackson requested changes
안녕하세요! 로또 미션을 함께하게된 잭슨(조남재)라고합니다! 
로또 미션 잛부탁드립니다! 
미션 진행 잘해주셨네요! 👍 
몇가지 고민할법한 포인트들 코멘트 남겼으니, 확인해주세요 😄

2023-02-15 18:13 UTC, namjackson commented on src/main/kotlin/lotto/controller/World.kt
> +            WinStatistics(lottos.value.map { LottoRankDeterminer().determine(it, winLotto) })
lottos의 value를 받아와서, determine을 통해 , WinStatistics객체를 생성해주는 동작을 하고있네요! 
객체에게 메세지를 보내고, 책임을 주어 , 서로 협력하는 구조를 만들어보면 어떨까요?

2023-02-15 18:13 UTC, namjackson commented on src/main/kotlin/lotto/model/LottoRankDeterminer.kt
> +class LottoRankDeterminer : RankDeterminer {
RankDeterminer와 ProfitRateCalculator 인터페이스를 분리하셨네요! 
어떤 기준으로 인터페이스를 분리하셨는지 의견이 궁금합니다!

2023-02-15 18:13 UTC, namjackson commented on src/test/kotlin/lotto/model/LottoProfitRateCalculatorTest.kt
> +    fun `구입금액이 14000원이고 당첨금이 5000원이면 수익률은 0_35이다`() {
구체적인 테스트 케이스 👍

2023-02-16 01:43 UTC, inseonyun commented on src/main/kotlin/lotto/entity/Lotto.kt
> +class Lotto(val numbers: List<Int>) {
RandomLottoGenerator에서 1~45의 숫자를 shuffled 함수를 통해 중복되지 않는 숫자 6개가 Lotto로 생성되어 검증의 필요성을 못 느꼈던 것 같습니다! 가만 생각해보면 테스트하기 쉬운 코드 작성을 위해 LottoGenerator를 상속받아 순차 검증을 하게 되는데 이때, 리뷰어님이 말씀하신 예외가 발생할 수도 있겠다는 생각이 드네요!! 감사합니다 :)

2023-02-16 08:21 UTC, inseonyun commented on src/main/kotlin/lotto/model/LottoRankDeterminer.kt
> +class LottoRankDeterminer : RankDeterminer {
둘 다 미션의 규칙이 변경 되었을 때를 대비해서 인터페이스로 분리를 했었습니다.
이와 관련해서 고민을 해봤는데 너무 가능성 없는 미래를 고민하고 인터페이스로 분리한건 아닌지 생각하게 됩니다...🙄
현재는 리펙터링 과정에서 주어진 규칙이 바뀔 가능성이 없을 거 같다 생각해 RankDeterminer의 역할은 Rank 클래스가 갖고 있게 수정 했습니다.
혹시 리뷰어님은 어떻게 생각하시는지 궁금합니다!

2023-02-17 06:31 UTC, inseonyun commented on src/main/kotlin/lotto/controller/World.kt
> +        return lottos
View와 도메인 작업만을 해야 한다 생각합니다! 
해당 로직은 잭슨님 피드백 고려하여 Lottos에서 수행하도록 하고 컨트롤러는 위 작업만 수행할 수 있도록 수정하겠습니다!

2023-02-18 09:49 UTC, inseonyun commented on src/main/kotlin/lotto/controller/World.kt
> +            WinStatistics(lottos.value.map { LottoRankDeterminer().determine(it, winLotto) })
Lotto와 Lottos, Rank.valueOf에서 로또의 결과를 구하도록 구성했는데 이렇게 구성하도록 하는 게 맞는건지, WinStatistics의 책임을 줄이려고 너무 불필요하게 각 model에게 책임을 준게 아닌지 의문이 듭니다!

2023-02-18 12:14 UTC, namjackson requested changes
안녕하세요 써니님 
변경사항 적용 잘해주셨네요! 😄 
몇가지 참고하실만한 내용들 코멘트 남겼으니 확인해주세요!

2023-02-18 12:14 UTC, namjackson commented on src/main/kotlin/lotto/controller/World.kt
> +            WinStatistics(lottos.value.map { LottoRankDeterminer().determine(it, winLotto) })
구현에는 정답이 없기 때문에, 다양한 구조가 될수 있어요!
다양한 구조 들 중 각각의 구현 방법 중 장단점을 비교해서, 
써니님 만의 우선순위나 규칙, 코딩철학을 고민해보시면 좋을거같아요! 

저의 개인적인 생각으로는, 
makeWinStatistics에 당첨에 대한 로직이 모두 있엇지만, 
makeWinStatistics는 컨트롤러내에 구현되어있기 때문에,
테스트로 검증하기 힘들뿐더러, 컨트롤러에서 View관련 코드와 도메인 로직들이 다양하게 실행되고 있었던거 같아요! 
각 모델들에게 책임을 나누었기 때문에, 테스트할 수 있는 구조가 된것 같아서 개선 되었다고 생각이 들어요!
( 해당 테스트를 작성해보셔도 좋을거같아요!)

하지만 써니님이 생각하는 각 클래스의 책임은 무엇인지, 불필요하게 책임이 과중된 클래스는 무엇인지 고민해보셔도 좋을거같아요!

2023-02-18 12:14 UTC, namjackson commented on src/main/kotlin/lotto/model/LottoRankDeterminer.kt
> +class LottoRankDeterminer : RankDeterminer {
YAGNI라고, "실제로 필요할 때 무조건 구현하되, 그저 필요할 것이라고 예상할 때에는 절대 구현하지 말라"라는 소프트웨어원칙을 말하는 의견도 있어요 :), 예상했던 부분과 다르게 요구사항이 변경될때, 오히려 예상하여 구현된 부분은 독이 될수도 있기 때문인데요,
그렇기 때문에 예상을 통해 구현하기보다, 객체의 역할과 책임을 분리하여 관리하도록 하면 좋을거 같아요!

위 부분의 구현이 잘못되었다고 생각하진 않지만,
인터페이스를 통해 추상화를 하였지만, 구현체만 사용하고 인터페이스는 사용하지 않는 구조라서 
스타일에 따라서, 인터페이스가 필요한가? 라는 의견도 있을것 같단 생각이 들어요!
고민을 해보시면 좋을것 같아요!

2023-02-19 14:56 UTC, inseonyun commented on src/main/kotlin/lotto/controller/World.kt
> +        return tryAndRerun {
InputVIew에 관해 질문드리고 싶은게 있습니다!
사실 요구사항에는 '입력에 대한 예외 발생 시 다시 입력을 받아야 한다'라는 말이 없어 항상 해당 로직을 구성할 때 의문점이 생기곤 합니다!
크루들 사이에도 이와 관련해서 말이 많이 오가고, 대게는 '나중에 이러한 요구사항이 생길 때를 대비하자'라는 말이 오간 것을 들었는데,
요구사항에는 없는 반복 입력을 계속 냅두는게 맞는 것일까요...? 아니면 예외 처리를 해 프로그램 동작이 멈추게 하는 것이 맞을까요..?

2023-02-19 14:58 UTC, inseonyun commented on src/main/kotlin/lotto/controller/World.kt
> +        return tryAndRerun {
또, InputView에서 입력 받은 원시값을 넘겨주는것이 아닌 포장된 PurchaseMoney나 Lotto, LottoNumber를 넘겨주는 것과 입력에 대한 검증을 수행하는 것이 올바른 InputView의 책임인지 의문이 듭니다!

2023-02-21 07:58 UTC, namjackson approved these changes
써니님 1단계 미션 고생하셨습니다.
리뷰가 조금 늦어졌네요 ㅠㅠ
몇가지 고민할법한 포인트, 답변 코멘트로 남겼으니, 확인해주세요!
2단계 미션 가시죠! 🏃

2023-02-21 07:58 UTC, namjackson commented on src/main/kotlin/lotto/entity/Lottos.kt
> +    }
Lottos 클래스는 어떤책임 있고,
로또를 생성해주는 책임은 어디에 있는게 좋을까요?
다음 미션과 연관된 부분이라 고민해보시면 좋을거같아요!

2023-02-21 07:58 UTC, namjackson commented on src/main/kotlin/lotto/entity/Lottos.kt
> +                }
List(lottoCount) Builder를 사용해보셔도 좋을것 같아요!

2023-02-21 07:58 UTC, namjackson commented on src/test/kotlin/lotto/entity/LottoTest.kt
> +        )
Lotto 번호 생성에 대한 코드가 너무 길어져서, 테스트 가독성이 저하된것 같아요!
팩토리 함수나, 확장함수, 함수등의 방법으로 분리해보면 어떨까요?

2023-02-21 07:58 UTC, namjackson commented on src/main/kotlin/lotto/controller/World.kt
> +        return tryAndRerun {
> InputVIew에 관해 질문드리고 싶은게 있습니다!
> 사실 요구사항에는 '입력에 대한 예외 발생 시 다시 입력을 받아야 한다'라는 말이 없어 항상 해당 로직을 구성할 때 의문점이 생기곤 합니다!
> 크루들 사이에도 이와 관련해서 말이 많이 오가고, 대게는 '나중에 이러한 요구사항이 생길 때를 대비하자'라는 말이 오간 것을 들었는데,
> 요구사항에는 없는 반복 입력을 계속 냅두는게 맞는 것일까요...? 아니면 예외 처리를 해 프로그램 동작이 멈추게 하는 것이 맞을까요.

사실이 요구사항에 존재 없기 때문에, 구현하지 않아도되지만, 사용성을 고려하는 부분은 좋은거 같아요! 
현업에서도 요구사항에 없는 부분도 고려하여, 다른 관계자들과 적극적으로 커뮤니케이션하기도 합니다
하지만, 예측하지 못한 에러의 경우에는 의도치 못한 동작을 하게되는데요,
input에 대한 에러 뿐아니라, 다양한 에러에서도 tryRerun이 동작하기 때문에
의도하지 않은 동작의 가능성도 있지않을까요?

2023-02-21 07:58 UTC, namjackson commented on src/main/kotlin/lotto/controller/World.kt
> +        return tryAndRerun {
> 또, InputView에서 입력 받은 원시값을 넘겨주는것이 아닌 포장된 PurchaseMoney나 Lotto, LottoNumber를 넘겨주는 것과 입력에 대한 검증을 수행하는 것이 올바른 InputView의 책임인지 의문이 듭니다!
입력값 검증에 대한 부분은 View에도 있어도 되지만, 입력시 검증하더라도 도메인에서 처리될 부분이라고 생각이 들어요! 
원시값을 포장 또한 도메인영역에서 진행되어야 책임이 있지않을까 생각합니다!

2023-02-21 07:58 UTC, merged