[해시] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #40
Opened 2023-02-22 15:31 UTC by EmilyCh0

잭슨님 안녕하세요! 
이번 2단계 미션에서는 지난 피드백을 반영하고, 수동 로또와 예외처리를 추가했습니다. 감사합니다 😄

2023-02-23 15:31 UTC, namjackson requested changes
안녕하세요 해시님,
2단계 미션 고생하셨습니다!
몇가지 고민할법한 포인트들 코멘트로 남겼으니 확인해주세요!

2023-02-23 15:31 UTC, namjackson commented on src/main/kotlin/controller/LottoController.kt
> +        return PurchasedLottos(manualLottos + autoLottos)
Controller내에서 중요한 로직이 실행되고 있어요! 
View관련코드와 비즈니스 로직이 섞여있는거 같아요!
테스트하기도 어려운 구조네요ㅠㅠ!
로또를 몇장 생성하는지 등의 여부는 다른 클래스를 생성하여 책임을 부여해보면 어떨까요?

2023-02-23 15:31 UTC, namjackson commented on src/main/kotlin/controller/LottoController.kt
> +        val manualLottos = repeatWithRunCatching { purchaseManualLottos(numberOfManualLottos) }
repeatWithRunCatching는 실패시 재시도하는 함수인데요,
입력등의 경우가 아니라면 위험한 로직인거 같아요! 
ManualLottos 생성시에 문제가 있었다면, 사용자 입력과 상관없이 
재귀함수가 종료되지 않을것으로 보여요!

2023-02-23 15:31 UTC, namjackson commented on src/main/kotlin/controller/LottoController.kt
> +        require(numberOfManualLottos >= 0) { NEGATIVE_NUMBER_ERROR }
검증 또한 Controller가 아닌 LottoShop같은 객체를 만들어 책임을 부여해보면 어떨까요?

2023-02-23 15:31 UTC, namjackson commented on src/main/kotlin/domain/model/WinningNumbers.kt
> +    fun getMatchCount(numbers: Set<LottoNumber>) =
리턴값을 명시적으로 작성해주세요!
구현부를 자세히 보지않으면 리턴값을 파악하기가 힘들것 같아요!

2023-02-23 15:31 UTC, namjackson commented on src/test/kotlin/WinningNumbersTest.kt
>      fun `당첨 번호가 6개인 경우`() {
테스트 케이스는 구체적으로 작성해주세요! 
당첨 번호가 6개인 경우, 어떻게 동작해야하는건지는 내부 구현부를 살펴보아야하는 구조예요! 
테스트 케이스를 하나의 프로그램 요구사항 명세서라고 생각해보셔도 좋을거같아요! 😄

2023-02-24 09:13 UTC, EmilyCh0 commented on src/main/kotlin/controller/LottoController.kt
> +        return PurchasedLottos(manualLottos + autoLottos)
LottoShop 클래스를 추가하여 로또 생성 / 수동 로또 개수에 대한 검증 / 자동 로또 개수 구하기 역할을 수행하도록 했습니다!

2023-02-24 09:16 UTC, EmilyCh0 commented on src/main/kotlin/controller/LottoController.kt
> +        val manualLottos = repeatWithRunCatching { purchaseManualLottos(numberOfManualLottos) }
중복해서 repeatWithRunCatching 하는 코드 제거했습니다!

2023-02-24 09:16 UTC, EmilyCh0 commented on src/main/kotlin/controller/LottoController.kt
> +        require(numberOfManualLottos >= 0) { NEGATIVE_NUMBER_ERROR }
LottoShop이 검증하도록 수정했습니다!

2023-02-24 09:17 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/WinningNumbers.kt
> +    fun getMatchCount(numbers: Set<LottoNumber>) =
리턴 타입 작성했습니다!

2023-02-24 09:18 UTC, EmilyCh0 commented on src/test/kotlin/WinningNumbersTest.kt
>      fun `당첨 번호가 6개인 경우`() {
`당첨 번호가 6개인 경우 예외가 발생하지 않고 WinningNumbers가 생성된다` 로 구체적인 테스트 케이스 작성했습니다!

2023-02-24 09:39 UTC, namjackson requested changes
안녕하세요 해시님, 피드백 반영 잘해주셨네요,
추가적으로 코멘트 드릴부분이 많지않네요!
마지막으로 코멘트 확인해주세요!

2023-02-24 09:39 UTC, namjackson commented on src/main/kotlin/domain/model/lotto/Lotto.kt
> +    }
data 클래스와 일반 클래스는 어떤 차이가 있을까요?

2023-02-24 09:39 UTC, namjackson commented on src/main/kotlin/domain/model/lotto/LottoShop.kt
> +    fun purchaseManualLotto(numbers: List<Int>): Lotto {
List<Int>는 무엇을 의미하는걸까요? 
LottoTicket같은 네이밍의 일급컬렉션으로 만들어보아요!

2023-02-24 09:39 UTC, namjackson commented on src/main/kotlin/domain/model/lotto/Lotto.kt
>      }
winningNumbers에서 matchCount, hasBonusNumber 를 따로 리턴하기보단, LottoResult를 리턴하면 어떨까요?

2023-02-24 09:39 UTC, namjackson commented on src/test/kotlin/LottoShopTest.kt
> +class LottoShopTest {
LottoShop Test로 수동/자동 갯수를 테스트 할수 있게되었네요 👍

2023-02-24 15:06 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/lotto/Lotto.kt
> +    }
data class는 equals(), hashCode(), toString() 등의 메서드를 자동으로 구현해 줍니다. Lotto 같은 클래스는 data class로 정의해서 자동으로 정의된 equals(), hashCode()를 사용하는 것을 좋을 것 같습니다! 다만 기존 Lotto 클래스는 외부에서 인스턴스를 생성하지 못하도록 private constructor로 정의했는데, data class를 사용하면 copy()도 사용할 수 있어 외부에서 인스턴스를 생성할 수 있게 되어 의도치 않은 문제가 생길 수 있을 것 같습니다.

2023-02-24 15:07 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/lotto/LottoShop.kt
> +    fun purchaseManualLotto(numbers: List<Int>): Lotto {
LottoTicket를 추가했고, LottoTicket에서 숫자 개수와 중복 검증을 합니다. Lotto 생성 시 LottoNumbers를 받아서 처리하도록 했기 때문에 Lotto에서 하던 검증은 제거했습니다!

2023-02-24 15:08 UTC, EmilyCh0 commented on src/main/kotlin/domain/model/lotto/Lotto.kt
>      }
WinningNumbers에 최종 결과 LottoResult를 리턴하는 `findLottoResult()`를 추가했습니다!

2023-02-25 12:32 UTC, namjackson approved these changes
안녕하세요, 해시님 로또 미션 고생하셨습니다 
로또 미션은 이만 마무리하도록 할게요 💯 
로또 미션을 진행하는 과정이 의미있는 시간이길 바랍니다 💪 
남은 미션들도 응원하겠습니다! 🏃 화이팅! 👍

2023-02-25 12:32 UTC, merged