[크롱] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #41
Opened 2023-02-22 17:11 UTC by krrong

안녕하세요! 1단계 미션을 진행하면서 결과를 출력하는 부분을 진행하지 않았는데 이를 확인하지 못하였습니다. 이 부분을 추가하고, 1단계 머지해주시면서 남겨주셨던 코멘트 반영, 수업에서 배웠던 내용들을 정리하고 복습하다보니  2단계 미션 제출이 늦은 것 같습니다. 늦은만큼 피드백 열심히 반영해서 리팩토링 진행해보겠습니다! 

2단계 미션을 진행하면서도 궁금한 부분이 생겨서 질문드립니다!
먼저 이번 미션에서는 로또를 수동으로 발급해줘야 해서 이 부분을 구조를 수정하지 않으면서 어떻게 진행할 수 있을까 고민해봤는데 2가지 방법이 떠올랐습니다.
1. 현재는 `LottoMachine`인터페이스에서 `createRandomLotto`, `createManualLotto`함수를 각각 만들어서 자동 로또와 수동 로또를 반환해주도록 하고 있습니다. 
2. 기존에 있던 `create()` 함수를 `create(numbers: List<LottoNumber>? = null)` 로 바꿔주고, 랜덤로또를 생성해주는 `RandomLottoMachine`과 수동로또를 생성해주는 `ManualLottoMachine`을 구현하여 각각 다르게 처리하는 방식도 있을 것 같다고 생각이 들었습니다. 
하지만 이렇게 진행하면 2번처럼 진행했을 경우 `create()`을 사용할 때 같은 인자를 받아 다르게 처리하는 것이 아니라 인자를 받거나 받지 않는 방법으로 처리를 진행하기 때문에 인터페이스의 의미가 없어진다고 생각해서 1번 방법을 선택하였습니다. 둘 중 어느 방법이 더 좋은 방법일까요?

다음으로 현재 InputView에서는 원하는 타입으로 들어왔는지만 검사하고 컨트롤러에서 원하는 객체를 생성할 때 에러가 발생하는지 검사하도록 구분을 해 둔 상태입니다. 이러한 이유 컨트롤러에 코드가 과도하게 많지 않은가에 대해서도 고민하고 있습니다. 이 부분에 대해서 리뷰어님은 어떻게 생각하시는지 여쭤보고 싶습니다!

늦은 시간에 PR을 보내게 돼서 죄송하고 자세하게 코멘트를 적어주시는만큼 재밌게 리팩토링 진행해보겠습니다! 감사합니다.😀

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/domain/LottoVendingMachine.kt
> +}
랜덤 기능이 도메인 레이어에 구현되는게 맞을까요?

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/domain/Ticket.kt
> +        return Ticket(lottos.toMutableList() + ticket.lottos)
컬렉션 `+` 함수가 어떻게 동작하고 있는지 확인해보고 toMutableList()가 왜 필요한지 답해주세요

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/domain/WinningLotto.kt
> +        return lotto.count { number ->
컬렉션 타입을 위임으로 사용하면, 컬렉션 처럼 사용할 수 있다는 장점이 있습니다.

하지만 그렇게 되면 필요한 기능 외에도 컬렉션의 모든 기능을 사용할 수 있기 때문에 위의 코드처럼 프로퍼티만 접근하지 않을 뿐이지 결국 비즈니스 로직을 뺏어서 작성했다고 볼 수 있습니다.

Lotto 객체에게 필요한 메시지를 전달해서 동작하도록 만들어보세요

```kotlin
// 로또 객체에게 -> 몇개 일치했는지 알려줘!
class WinningLotto(...) {
   fun match(lotto: Lotto): Int {
      return lotto.match(winningLotto)
   }
}
```

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/view/InputView.kt
> +            result[it] = getManualLotto()
Set 컬렉션을 List로 변환할 수 있듯이 반대도 가능합니다.

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/view/InputViewInterface.kt
> +    fun getManualLotto(): Set<Int>
getManualLotto()는 더이상 사용되지 않아요.

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/view/InputViewInterface.kt
> +    fun getManualLottos(count: Int): List<Set<Int>>
인터페이스 함수를 보면, getLottoNumbers(), getLotto(), getWinningLotto() 모두 결국엔 `Set<Int>`를 반환 하고 있습니다.

이름과 반환 타입이 그래서 무엇을 반환하는지 헷갈리지 않을까요?

2023-02-23 12:39 UTC, laco-dev commented on src/main/kotlin/view/ResultViewInterface.kt
> +    fun printLotto(lotto: Lotto)
마찬가지로 printLotto()도 더이상 인터페이스로서 사용이 되지 않네요

2023-02-23 12:39 UTC, laco-dev commented on src/test/kotlin/domain/RankTest.kt
> +    }
각 등수의 조건을 테스트 하나하나씩 보면서 바로 이해할 수 있어서 훨씬 좋아졌습니다. 👍🏻

2023-02-23 12:39 UTC, laco-dev commented on src/test/kotlin/domain/RankTest.kt
> +    }
각 등수의 조건을 테스트 하나하나씩 보면서 바로 이해할 수 있어서 훨씬 좋아졌습니다. 👍🏻

2023-02-23 12:42 UTC, laco-dev requested changes
2단계 미션 잘 구현 해주셨습니다.

컨트롤러에서 비즈니스 로직과 UI 로직에 대한 책임이 모두 존재하고 있습니다.
각 역할이 하는 영역을 잘 구분해서 생각 해 주시면 좋을 것 같습니다.

또한 위임같은 전략을 사용하셨는데, 이러한 전략에 이어서 따라오는 장단점을 충분히 고민 해보시면 좋겠습니다.

2023-02-23 12:42 UTC, laco-dev commented on src/test/kotlin/domain/RankTest.kt
> +    }
각 등수의 조건을 테스트 하나하나씩 보면서 바로 이해할 수 있어서 훨씬 좋아졌습니다. 👍🏻

2023-02-23 12:45 UTC, laco-dev commented on src/main/kotlin/domain/LottoMachine.kt
> +    fun createManualLotto(lottoNumbers: Set<Int>): Lotto
> 기존에 있던 create() 함수를 create(numbers: List<LottoNumber>? = null) 로 바꿔주고, 랜덤로또를 생성해주는 RandomLottoMachine과 수동로또를 생성해주는 ManualLottoMachine을 구현하여 각각 다르게 처리하는 방식도 있을 것 같다고 생각이 들었습니다.
하지만 이렇게 진행하면 2번처럼 진행했을 경우 create()을 사용할 때 같은 인자를 받아 다르게 처리하는 것이 아니라 인자를 받거나 받지 않는 방법으로 처리를 진행하기 때문에 인터페이스의 의미가 없어진다고 생각해서 1번 방법을 선택하였습니다. 둘 중 어느 방법이 더 좋은 방법일까요?

왜 인터페이스가 create(numbers)로 변경이 필요할까요?
구현체에서 결정할 내용이 아닐까요?

2023-02-23 15:27 UTC, laco-dev commented on src/main/kotlin/controller/LottoController.kt
> +            initializeMoney()
이 내용은, InputView에서 도메인 모델을 반환할 필요가 있을까? 에 대한 의문이기 때문에 꼭 정답은 아닙니다.

생각해보시고, 조금더 효율적이라고 생각하신 관점으로 접근해주시면 감사하겠습니다.

2023-02-24 05:21 UTC, krrong commented on src/main/kotlin/controller/LottoController.kt
> +    }
`LottoCount`를 생성하여 수정하였습니다!

2023-02-24 09:27 UTC, krrong commented on src/main/kotlin/view/ResultViewInterface.kt
> +    fun printLotto(lotto: Lotto)
인터페이스에서 제거하고 구현체에 private으로 생성했습니다.

2023-02-24 09:48 UTC, krrong commented on src/main/kotlin/controller/LottoController.kt
> +            initializeMoney()
너무 자세하게 설명해주셔서 감사합니다 😊

제 생각을 말씀드리면 일단 지금과 같이 구현한 이유는 `InputView`에서는 알맞는 형태의 값이 들어왔는지만 검사를 진행하고 컨트롤러에서 모델을 반환할 때 유효성 검증을 하게 구분하려고 했기 때문입니다.

말씀해주신 것처럼 변경하면서 든 생각이 `InputView`에서 어느정도의 도메인 모델까지 반환을 해야하는가에 대해 고민하게 되었습니다. 예를 들어 수동 로또를 입력 받는 경우 `Lotto`로 반환을 할지, `Ticket`으로 반환할지 고민을 했고, `Ticket`을 반환하면 결국 `LottoSeller`가 하는 일을 뷰에서 가져가는 것이 아닌가 생각이 들어서 다시 원래대로 되돌렸습니다. 이 부분에 대해서는 달아주신 피드백을 보면서 더 고민해보도록 하겠습니다!! 감사합니다 🙃

2023-02-24 10:09 UTC, krrong commented on src/main/kotlin/domain/LottoStatistics.kt
> +        return sum
result를 통해 값을 가져오도록 수정했습니다!

2023-02-25 06:30 UTC, krrong commented on src/main/kotlin/domain/LottoMachine.kt
> +    fun createManualLotto(lottoNumbers: Set<Int>): Lotto
제가 찾아본 의존성 주입 방법은 생성자 주입, 필드 주입, setter주입 세 가지입니다. 위 방식으로 구현하기 위해서는 `LottoSeller`가 가지고 있는 `LottoMachine`을 setter 주입을 통해서 변경하면 될 것 같다고 생각을 했습니다.

이를 적용하기 위해 노력을 해보았는데, `ManualLottoMachine`의 `create()`함수를 어떻게 작성해야 할 지 감이 오지 않습니다. `ManualLottoMachine`은 사용에게 입력 받은 숫자를 바탕으로 로또를 만들어줘야 한다고 생각이 듭니다. 그러기 위해서는 파라미터로 넘겨와야 하지만 `LottoMachine`의 `create()`와 시그니처가 달라지기 때문에 어떤 방식으로 수정해야 할 지 어려운 것 같습니다.

2023-02-25 06:41 UTC, krrong commented on src/main/kotlin/domain/Ticket.kt
> +        return Ticket(lottos.toMutableList() + ticket.lottos)
컬렉션의 `+`는 피연산자인 두 컬렉션의 사이즈만큼 새로운 컬렉션을 생성하고 그 새로운 컬렉션에 피연산자의 element들을 모두 넣어주는 방식으로 동작합니다. 이에따라 `toMutableList`를 삭제하였습니다!

2023-02-25 06:45 UTC, krrong commented on src/main/kotlin/domain/Lotto.kt
> +        }
`Lotto`의 `toList()`는 `List<LottoNumber>`를 반환하고 `ResultView`에서 변경하여 출력하도록 수정하였습니다!

2023-02-25 07:15 UTC, krrong commented on src/main/kotlin/domain/WinningLotto.kt
> +        return lotto.count { number ->
위임을 사용하지 않고 필요한 메시지를 던져 동작하도록 수정했습니다!

2023-02-25 07:30 UTC, krrong commented on src/main/kotlin/view/InputView.kt
> +            result[it] = getManualLotto()
List를 Set으로 바꿀 수 있지만 현재 코드에서 어떻게 적용할 수 있는 것인지 잘 이해하지 못했습니다. 혹시 어떤 방법으로 개선이 가능한 것인가요?

2023-02-25 07:31 UTC, krrong commented on src/main/kotlin/view/InputViewInterface.kt
> +    fun getManualLotto(): Set<Int>
`InputViewInterface`에서는 삭제하고 `InputView`에서 구현하여 사용하였습니다!

2023-02-25 07:35 UTC, krrong commented on src/main/kotlin/view/InputViewInterface.kt
> +    fun getManualLottos(count: Int): List<Set<Int>>
저도 이 부분을 고민하고 있었습니다. 그런데 `InputView`에서 모델을 생성하지 않고 반환하고 있고, 함수의 이름에는 자료형을 붙이지 않는다고 알고 있어서 위와 같이 작성했습니다. 

자료형을 붙이는 것이 더 명확하고 좋을까요?

2023-02-25 07:44 UTC, krrong commented on src/main/kotlin/domain/LottoVendingMachine.kt
> +}
[이 부분](https://github.com/woowacourse/kotlin-lotto/pull/41#discussion_r1117875886)과 함께 잘 이해되지 않습니다.

2023-02-25 07:53 UTC, krrong commented on src/main/kotlin/controller/LottoController.kt
> +    }
수익률 계산 로직을 `LottoStatistics`로 이동했습니다!

2023-02-25 07:53 UTC, krrong commented on src/main/kotlin/controller/LottoController.kt
> +        private const val EACH_LOTTO_PRICE = 1000
로또 한 장의 가격은 Money가 가지고 있도록 수정했습니다!

2023-02-25 07:56 UTC, krrong commented on src/main/kotlin/controller/LottoController.kt
> +        val money = initializeMoney()
통일성있게 수정했습니다!

[반영커밋](https://github.com/woowacourse/kotlin-lotto/pull/41/commits/53fe9c299a73e5ae65421e49b70fdd02297d1c1f)

2023-02-25 09:51 UTC, laco-dev requested changes
피드백 작성 잘 해주셨습니다.

어려운 내용을 몇 가지 소개해드렸는데, 스스로 의견을 빠르게 정리 해주시고
답변을 주셔서 좋았습니다.

관련해서 제 생각을 조금 남겨보았는데,
코드를 조금 더 개선 해 보고싶으시다면 해보셔도 좋고, 아니라면 답글 남겨서 바로 리뷰요청 주시면 되겠습니다.

2023-02-25 09:51 UTC, laco-dev commented on src/main/kotlin/domain/LottoStatistics.kt
> +        return floor((profit / totalMoney.money).toDouble()).toString()
LottoStatistics는 Result를 스스로 계산할 능력이 있는데요.
그렇다면, 수익률을 계산할때 totalMoney 하나만 있으면 모든 것을 알 수 있지 않을까요?

LottoStatistics가 하나의 WinningLotto를 두고 재사용 되는 것을 고려해서 객체가 설계되었는데,

아래처럼 가지고 있다면 어떤 차이가 생길 수 있을까요?
```
class LottoStatistics(winningLotto: WinningLotto, ticket: Ticket) { ... }
```

2023-02-25 09:51 UTC, laco-dev commented on src/main/kotlin/domain/LottoSeller.kt
> +    fun sellRandomLottos(count: Int): Ticket {
> 제가 찾아본 의존성 주입 방법은 생성자 주입, 필드 주입, setter주입 세 가지입니다. 위 방식으로 구현하기 위해서는 LottoSeller가 가지고 있는 LottoMachine을 setter 주입을 통해서 변경하면 될 것 같다고 생각을 했습니다.
이를 적용하기 위해 노력을 해보았는데, ManualLottoMachine의 create()함수를 어떻게 작성해야 할 지 감이 오지 않습니다. ManualLottoMachine은 사용에게 입력 받은 숫자를 바탕으로 로또를 만들어줘야 한다고 생각이 듭니다. 그러기 위해서는 파라미터로 넘겨와야 하지만 LottoMachine의 create()와 시그니처가 달라지기 때문에 어떤 방식으로 수정해야 할 지 어려운 것 같습니다.

우선 필드 주입, setter 주입은 같은 것을 의미하는 듯 합니다.
3가지는 생성자 주입, 필드 주입, 함수 파라미터 주입을 가집니다.

로또 셀러는 어떤 기계를 이용해서 만들지 관심이 없이, 티켓을 만드려고 한다면 아래와 같은 형태로 작성할 수 있겠습니다.
```kotlin
class LottoSeller {
   // 더이상 로또머신이 랜덤인지 뭔지 알 필요가 없어짐
   fun sellTicket(count: Int lottoMachine: LottoMachine): Ticket {
      return Ticket(lottoMachine.create(count))
   }
}
```

그리고, 어떤 기계를 이용해서 만들지는 사용하는 곳에서 결정을 하게 됩니다.
```kotlin
val lottoSeller: LottoSeller
val manualTicket = lottoSellet.sellTicket(ManualLottoMachine)
val autoTicket = lottoSeller.sellTicket(RandomLottoMachine)
```

이런 생각을 또 해보셨으면 좋겠어요
랜덤으로 로또를 만드는데 LottoMachine 타입을 사용하고 있고
수동으로 로또를 만드는데 직접 만들고 있고, 뭔가 어색한 느낌?

---

이 개념은 조금 많이 어려운 내용이라서, 고민 해 주신 부분으로도 충분합니다.
꼭 이 내용을 해결해보기 위해서 너무 많은 시간을 투자하지 않으셔도 괜찮습니다.

2023-02-25 09:51 UTC, laco-dev commented on src/main/kotlin/domain/Ticket.kt
> +}
> 위임 전략을 사용한 이유는 단순히 프로퍼티로 접근하지 않고 foreach와 같은 스트림함수를 사용하기 위함이었습니다.

스스로 비즈니스 로직을 처리해야 하는 원칙을 외부에서 작성하기 쉬워진다는 점을 둘 수 있겠습니다.

예를 들어 지금 구현에서 티켓 두개를 합치는 기능은 아래 코드로도 동작합니다.

```kotlin
val lotto: Lotto
val ticket: Ticket
val ticket2 = ticket + lotto
```

티켓에 어떤 로또가 있는지 찾는것도 물론 가능합니다.
```kotlin
val myLotto: Lotto
val ticket: Ticket
val someLotto  = ticket.find { lotto == myLotto }
```

그러면 이제 리뷰가 달리겠죠? 객체에 메시지를 보내서 받아오도록 해보세요.

2023-02-25 09:51 UTC, laco-dev commented on src/main/kotlin/view/InputView.kt
> +    }
> 추가로 궁금한 것이 있는데 혹시 리뷰어님은 InputView에서 모델을 생성하여 반환하는 것을 선호하시나요? 그렇다면 이유도 궁금합니다!

이것은 트레이드 오프의 영역이라고 생각해요.
반복되는 검증 로직을 도메인 모델에서 하도록 할 것인가,
도메인과 UI를 명확히 분리하는 대신 보일러 플레이트를 감수할 것인가,

이거는 앞으로 여러가지 코딩을 하시면서 직접 경험해보시는게 최고일 것 같습니다.

다만, 한 가지 생각해보셔야 할 점은,

InputView는 도메인을 알면 안된다 라고 명확하게 기준을 잡으셨다면,
왜 OutputView는 티켓을 알고 있는걸까요? 😱 

~대충 멘붕에 빠지는 소리~

2023-02-25 11:23 UTC, krrong commented on src/main/kotlin/domain/LottoStatistics.kt
> +        return floor((profit / totalMoney.money).toDouble()).toString()
`LottoStatistics`가 `WinningLotto`와 발급한 모든 Ticket에 대한 정보를 가지고 있으면 내부에서 수익과 수익률을 모두 계산할 수 있을 것 같습니다! 컨트롤러에서 조금 더 간단하게 사용할 수 있을 것 같습니다 😊

2023-02-25 12:33 UTC, krrong commented on src/main/kotlin/domain/Ticket.kt
> +}
ㅎㅎ.. `Ticket`도 위임 전략을 사용하지 않고 메시지를 통해 원하는 결과를 반환하도록 수정하였습니다. 한 가지 고민되는 것이 있습니다. `LottoStatistics`의 `getWinningCountBy`를 계산하기 위해서는 필수적으로 `ticket`의 `lottos`에 접근을 해야 합니다.. 이런 경우에는 직접 접근해서 `foreach`를 사용해도 문제가 없는 것일까요? 아니면 이 부분 역시 메시지를 던져서 결과를 반환 받아야 할까요? 고민해보고 남겨보았습니다..!


말씀해주신 것들을 바탕으로 고민해보니까 위임 전략을 사용하게 되면 비즈니스 로직을 외부에서 작성하기 쉬워지지만 그만큼 도메인 로직의 분리가 덜 된다고 생각이 됩니다. 객체에게 메시지를 던져서 원하는 결과를 반환 받는 방법이 더 좋다면(로직의 분리에 대해) 위임 전략이 있는 이유와 언제 사용하는지에 대해서도 고민이 되네요😢

2023-02-25 13:05 UTC, krrong commented on src/main/kotlin/view/InputView.kt
> +    }
사실 OutputView 구현 당시에도 데이터를 가지고 있는 객체에서 출력을 위한 문자열로 바꿔준 뒤에 OutputView 에 전달하려고 했지만 너무 복잡해지지는 않을까 생각하면서 무심코 객체를 넘겨준 것 같습니다. 짚어주시지 않았다면 간과하고 넘어갔을 것 같아요! 감사합니다😊

2023-02-25 13:55 UTC, krrong commented on src/main/kotlin/domain/LottoSeller.kt
> +    fun sellRandomLottos(count: Int): Ticket {
정말 세세하게 설명해주셔서 한번에 이해가 된 것 같아요! 정말 감사합니다.😊


제가 이해한 바로는 말씀해주신 방법이 파라미터 주입으로 `LottoSeller`가 사용하는 `LottoMachine`을 동적으로 변경하여 사용할 수 있도록 만드는 것으로 이해했습니다. 자동으로 랜덤 로또를 생성하는 것은(RandomLottoMachine) 어렵지 않게 진행했지만 수동으로 로또를 생성하는 부분에서 많은 고민을 했습니다. 


해결할 수 있는 방법을 다양하게 고민해봤지만 제가 생각할 수 있는 것은 `ManualLottoMachine`을 생성할 때 수동으로 입력한 로또 번호들을 넘기는 것 뿐이었는데요. 이유를 설명하기는 어렵지만 그렇게 좋은 방법이 아니라고 생각이 됩니다. 더 효율적인 방법이 존재하는지 궁금합니다!

2023-02-25 14:27 UTC, laco-dev commented on src/main/kotlin/domain/LottoSeller.kt
> +    fun sellRandomLottos(count: Int): Ticket {
1. ManualLotto가 InputView의 의존성을 가진다.
   - 이 경우는 일관성이 다소 떨어지는 대신, ManualLotto가 스스로 동작한다고 볼 수 있겠습니다.
2. ManualLotto가 가져올 로또 번호를 다시 한번 협력을 통해 가져온다. 
   - 이 경우는, 위임을 사용하거나 또 다른 인터페이스를 사용하거나 등 여러가지 방법이 있는데 우선은 이런 코드가 있다 정도로만 생각해주시면 되겠습니다.

```kotlin
class ManualLottoMachine(
   private val getLottoNumbers: () -> List<LottoNumber>
): LottoMachine {
   fun create(...) { return getLottoNumbers() }
}

class ManualLottoMachine(
   private val delegate: LottoMachine
): LottoMachine by lottoMachine


// Controller 
val lottoMachine: LottoMachine = ManualLottoMachine { getManualLottoNumbers() }
```


사실 이런 방법 외에도 굳이 구현체를 이름으로 직접 만들지 않아도 인터페이스를 익명으로 구현하는 방법이 꽤나 간단하기도 합니다.

```
val manualLottoMachine = object: LottoMachine {
   override fun create(...) { return getManualLottoNumbers() }
}
```

2023-02-25 14:29 UTC, laco-dev commented on src/main/kotlin/view/InputView.kt
> +    }
코틀린 구현에서는 이정도로 고민 해주시면 충분하고, 안드로이드 개발을 시작할 때 더 해보시면 되겠습니당

2023-02-25 14:32 UTC, laco-dev approved these changes
지금까지 정말 고생 많으셨습니다.

아직 고민되는 점도 많을 거고, 답답한 점도 많으실텐데요
0부터 100까지 모든 것을 미션내에 담아가려고 하시지 않으셔도 괜찮습니다.
첫 설계는 항상 뒤돌아보면 레거시가 되고 수많은 리팩토링이 기다리고 있으니까요.

배워온 개념들이 앞으로의 미션들 외에도 안드로이드 개발에 어떻게 적용할 수 있을까를 잘 고민 해보셨으면 좋겠습니다.

2023-02-25 14:32 UTC, merged