[로피] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #47
Opened 2023-02-23 08:54 UTC by Choisehyeon

저번에 리뷰해주신 피드백 반영해서 구현했습니다! 에러 처리를 구현하는데 시간을 많이 써서 2단계 제출이 늦었습니다ㅠㅠ 리뷰 잘 부탁드립니다!

2023-02-24 04:44 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!
리팩토링을 진행할 때도 TDD를 활용해서 진행해보시면 좋겠어요 :)
수동 티켓 생성에 대한 테스트도 꼭 추가해주세요!

고민해볼만한 곳에 코멘트 달아두었어요.
피드백 반영하시고 다시 리뷰 요청 부탁드릴게요!

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/controller/LottoController.kt
> +            Money(input!!)
null 과 non-null을 엄격히 구분하는 언어이니, !!의 사용은 지양해주세요.

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/controller/LottoController.kt
> +            lottoMachine.generateManualLottos(input)
로또를 생성할 때마다 LottoMachine을 새로 생성하지 않고 재활용할 수 있는 방법을 생각해보아요 :)

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/controller/LottoController.kt
> +        }
로또 결과를 생성하는 것은 어느 객체의 일일지 다시 고민해보아요 :)

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/domain/Lotto.kt
> +data class Lotto(private val numbers: Set<LottoNumber>) : Set<LottoNumber> by numbers {
Kotlin Delegation을 활용해서 일급 컬렉션을 구현해 주셨네요 :)

delegation을 활용하면, Lotto에서 필요한 메서드 뿐만 아니라 불필요한 메서드 까지도 갖게 됩니다.
일급 컬렉션에서는 필요한 메서드만 구현해보는 것은 어떨까요?

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/domain/LottoMachine.kt
>          return (1..count).map { lottoGenerator.generateLotto() }
`List ( ) { ... }`를 활용해볼 수 있어요 🙂

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/domain/RandomLottoGenerator.kt
> +                .take(LOTTO_LIMIT_SIZE)
take 확장 함수를 활용해주셨네요 👍

2023-02-24 04:44 UTC, malibinYun commented on src/main/kotlin/domain/Count.kt
> +class Count(val money: Money, val count: Int) {
이 Count는 이름에 비해서 많은 의존 관계가 엮여있어 보여요.
Count라 하면 갯수만을 가지고 있을 것이 기대되는데, Money를 알고. Lotto를 간접적으로 알고있는 형태예요.
이 객체의 역할과 책임에 대해서는 충분히 고민을 해보셨으면 좋겠어요.
너무 어려운 내용일 수도 있으니, 많은 변형을 하지 않으셔도 좋습니다 🙂

2023-02-24 04:44 UTC, malibinYun commented on src/test/kotlin/LottoTest.kt
> +            .withMessageContaining("당첨 번호가 6개가 아닙니다")
로또 숫자는 반드시 당첨 번호는 아니라고 생각해요.
메시지를 더 다듬어보는 건 어떨까요?

2023-02-24 04:44 UTC, malibinYun commented on src/test/kotlin/LottoTest.kt
> +    fun `로또와 당첨번호가 일치하는 개수가 6개인지 확인`() {
이 테스트는 Parameterized Test를 활용해볼 수 있겠네요 :)

2023-02-24 04:44 UTC, malibinYun commented on src/test/kotlin/WinningLottoTest.kt
> +        delimiter = ':',
list 처럼 복잡한 객체가 필요한 경우엔 Method Source가 더 적합할 수 있어요 :)

2023-02-24 04:44 UTC, malibinYun commented on src/test/kotlin/WinningLottoTest.kt
>          fun produceOverlayBonusNumber(): List<Arguments> {
필요하지 않는 코드는 지워주세요!

2023-02-25 13:28 UTC, Choisehyeon commented on src/main/kotlin/controller/LottoController.kt
> +            lottoMachine.generateManualLottos(input)
object 클래스 사용해서 한번만 생성하도록 수정했습니다!

2023-02-25 13:29 UTC, Choisehyeon commented on src/main/kotlin/controller/LottoController.kt
> +        }
WinningLotto 클래스에서 결과 생성하도록 수정했습니다!

2023-02-25 13:34 UTC, Choisehyeon commented on src/main/kotlin/domain/Count.kt
> +class Count(val money: Money, val count: Int) {
Count 클래스를 제거하고 Money 클래스에서 로또를 사고 남은 금액을 반환하는 함수를 만들어서 Money 클래스에서 자동 로또와 수동로또의 개수를 구할 수 있도록 했습니다.

2023-02-26 07:04 UTC, malibinYun approved these changes
로또 미션 고생 많으셨어요!
많은 부분이 깔끔해져서 크게 피드백 드릴 부분이 없었네요 :)
저와 미션을 함께 하면서 고민했던 부분들이 앞으로 개발하시면서 도움이 되셨으면 좋겠어요😊
미션은 이만 마무리하도록 할게요!
다른 미션들도 잘 수행하시길 응원할게요~ 💪🔥

2023-02-26 07:04 UTC, malibinYun commented on src/test/kotlin/WinningLottoTest.kt
> +        assertThat(actual).isEqualTo(rank)
Parameterized Test를 잘 작성해주셨네요! 👍

2023-02-26 07:18 UTC, merged