[빅스] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #51
Opened 2023-02-24 15:11 UTC by briandr97

2단계 과제 제출합니다~!!!
결국 오늘을 넘겼네요,,, 12시가 넘었습니다 ㅠㅠ

2단계는 하면서 뭔가 특정한 질문이 많이 떠오르지는 않았습니다.
아무래도 페어없이 혼자 고민한 영향이 큰 것 같습니다.
분명 고민은 엄청 많이했는데 딱 뭐라고 질문해야할지 모르겠달까,,

그래도 몇가지 질문 드리자면,,,
1. Purchaser의 로직이... 적절한 방식일까요? 뭔가 굉장히 지저분해진 기분이지만 어떻게 해야할지 잘 감이 안 잡혔습니다.
2. View 구조를 다시 변경하였습니다. 입력을 요청하는 아웃풋과 해당 입력을 받는 인풋을 한데 묶어보았습니다,, 이는 입력에 대한 에러 처리를 컨트롤러에서 하지 않고 뷰에서 깔끔하게 처리하기 위함이었습니다. InputView에 inputNullControl함수를 통해 에러 처리를 해주었는데 적절한 방식인지 궁금합니다.
3. Controller에서는 checkError 함수를 통해서 에러 처리를 해주었는데 이런식으로 에러를 처리하는 것이 맞는지,,, 역시 궁금합니다. 원래 이렇게 require로 에러가 발생하는 부분을 모두 감싸는게 맞을까요..?

뭔가 이번 질문들이 대체적으로 주장도 없고 근거도 없는 느낌이라 많이 찝찝하네요,, 더 열심히 해보겠습니다,,

2023-02-25 15:18 UTC, woowahan-leah requested changes
안녕하세요 빅스!

Step2 구현을 잘 해주셨습니다 💯  깔끔한 구현이 좋았습니다.
고민해보시면 좋을만한 코멘트와 남겨주신 질문에 대한 답변을 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-02-25 15:18 UTC, woowahan-leah commented on src/main/kotlin/domain/Purchaser.kt
> +class Purchaser(spentMoney: Money) {
> Purchaser의 로직이... 적절한 방식일까요? 뭔가 굉장히 지저분해진 기분이지만 어떻게 해야할지 잘 감이 안 잡혔습니다.

가장 큰 원인은 컨트롤러에서 확인할 수 있을 것 같네요.
```kotlin
val purchaser = checkError { Purchaser(getMoney()) }
checkError { purchaser.decideManualLottoCount(getManualLottoCount()) }
checkError { purchaser.purchaseManualLottoBundle(getManualLottoBundle(purchaser.manualLottoCount)) }
```
Purchaser의 상태가 세 번에 나뉘어 초기화되고 있습니다. 이런 고민을 해볼 수 있을 것 같아요.
1. Purchaser의 상태가 여러 번 나뉘어져 초기화될 필요가 있을까?
2. Purchaser가 외부의 조작 없이 스스로 일할 수 있도록 만들어보면 어떨까? 
3. 꼭 Purchaser가 이 모든 일을 해야 할까?
4. ...

빅스는 어떻게 생각하세요?

2023-02-25 15:18 UTC, woowahan-leah commented on src/main/kotlin/domain/WinStatistics.kt
> +        private const val LOTTO_PRICE = 1000
요구사항이 바뀌어 로또 한 장이 2000원으로 올랐다면 이곳과 Purchaser 모두 수정되어야 할까요?

2023-02-25 15:18 UTC, woowahan-leah commented on src/main/kotlin/view/InputResponseView.kt
> +object InputResponseView {
> View 구조를 다시 변경하였습니다. 입력을 요청하는 아웃풋과 해당 입력을 받는 인풋을 한데 묶어보았습니다,, 이는 입력에 대한 에러 처리를 컨트롤러에서 하지 않고 뷰에서 깔끔하게 처리하기 위함이었습니다. InputView에 inputNullControl함수를 통해 에러 처리를 해주었는데 적절한 방식인지 궁금합니다.

👍  뷰를 노출하는 관심사/사용자의 입력에 대한 유효성 검사를 하는 관심사가 잘 분리된 것 같습니다. 이전 단계에서 고민하던 내용이 해결되었나요? 다음 미션을 진행할 때에는 이런 View를 나누는 또다른 방법(예를 들어 도메인에 따라 나눠보기)을 적용해보고 장단점을 비교해보는것도 재밌을거예요. 
물론 도메인 로직을 작성하는 것보다 중요한 우선순위라고 생각하진 않습니다 ㅎㅎ

2023-02-25 15:18 UTC, woowahan-leah commented on src/main/kotlin/view/InputResponseView.kt
> +object InputResponseView {
inputNullControl은 다음 사항에 대한 연습을 위한 로직이라고 생각하면 될까요?

> 논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.

2023-02-25 15:18 UTC, woowahan-leah commented on src/test/kotlin/domain/MoneyTest.kt
> +        assertThrows<IllegalArgumentException> { Money(receivedMoney) }
assertThrows 활용 👍

2023-02-25 15:18 UTC, woowahan-leah commented on src/test/kotlin/domain/PurchaserTest.kt
> +    )
이러한 값을 테스트를 위한 Fixture라고 합니다. 이러한 픽스쳐는 어떻게 사용하는 것이 직관적일까요?
다음 구문을 보고 다른 개발자가 한눈에 otherLottoBundle값을 예상할 수 있을까요?
```kotlin
purchaser.purchaseManualLottoBundle(otherLottoBundle)
```

2023-02-25 15:18 UTC, woowahan-leah commented on src/test/kotlin/domain/lotto/LottoBundleTest.kt
> +    fun `plus가 잘 작동하는지 테스트`() {
테스트명에서 테스트하고자 하는 대상과 로직을 명확히 밝혀주세요 🙂

2023-02-25 15:18 UTC, woowahan-leah commented on src/test/kotlin/domain/lotto/LottoTest.kt
> +    @MethodSource("provideNumbers")
MethodSource 활용 👍

2023-02-25 15:18 UTC, woowahan-leah commented on README.md
>  ## 기능 목록
요구사항이 누락되었습니다.
<img width="298" alt="image" src="https://user-images.githubusercontent.com/112997521/221364948-f593d58a-d020-41ef-b8f9-1009da42d664.png">
당첨 통계에서 당첨되지 않은 통계도 확인할 수 있도록 해주세요!

2023-02-27 06:47 UTC, briandr97 commented on README.md
>  ## 기능 목록
step2 이전의 기록들을 지웠습니다!
누락된 요구사항도 만족하도록 수정하였습니다!

2023-02-27 06:50 UTC, briandr97 commented on src/main/kotlin/LottoController.kt
> +        checkError { purchaser.purchaseManualLottoBundle(getManualLottoBundle(purchaser.manualLottoCount)) }
"Input에서 받는 입력을 분기점이라고 가정하여 블록을 나누는 방법도 있을 것 같네요"
이 경우에는 현재 domain에 존재하는 논리 오류 검증들을 input에서도 적용해야하는 것일까요??

"또 현재는 catch (e: Exception)와 다를 바가 없는 로직일 수 있을 것 같은데 이를 더 명확한 에러 구분으로 처리"
이 부분에서 궁금한 점이,, 현재는 모든 에러 발생 시 다시 입력 받는 로직이 수행되는데, 에러 발생에 따른 다음 동작이 다를 때 이런 부분을 적용하면 좋다는 말씀이신가요?

2023-02-27 06:55 UTC, briandr97 commented on src/main/kotlin/domain/Purchaser.kt
> +class Purchaser(spentMoney: Money) {
Purchaser가 여러 번에 걸쳐 초기화되고, 자율적이지 못하며, 일이 많다는 피드백에 대한 고민 결과 우선 Purchaser를 사용하지 않고 논리 검증이 필요한 부분만 LottoCount로 묶어놓았습니다.

다만 이렇게 했을 경우 LottoCount가 한번에 초기화는 가능하지만 전체 개수를 입력 받았을 때 오류가 발생해도 수동 개수까지 입력해야 에러가 발생하며 재입력을 받습니다. 즉 바로바로 에러가 발생하여 재입력을 받는 게 아닌 두 가지 행동이 끝났을 때 에러 발생과 재입력 받기가 수행됩니다.

그래서 Purchaser를 사용해도 LottoCount를 사용해도 부족하고 이상하다고 생각됩니다.

아직 해답은 찾지 못했습니다,, 두 가지의 문제점을 모두 해결하려면 컨트롤러에 더 많은 코드들이 들어갈 것 같은데 컨트롤러에 도메인에서 해야할 논리 검증 로직들이 들어가면 안된다고 생각해서 우선 이렇게 작성하였습니다.

어떻게.. 하는게 좋을까요? 😢 😭

2023-02-27 06:56 UTC, briandr97 commented on src/main/kotlin/domain/WinStatistics.kt
> +        private const val LOTTO_PRICE = 1000
LOTTO_PRICE를 util의 common으로 빼 전역으로 사용하도록 수정하였습니다.
이제 한 군데에서 수정하면 모든 곳에 적용될 것입니다!

2023-02-27 07:02 UTC, briandr97 commented on src/main/kotlin/view/InputResponseView.kt
> +object InputResponseView {
> 다음 미션을 진행할 때에는 이런 View를 나누는 또다른 방법(예를 들어 도메인에 따라 나눠보기)을 적용해보고 장단점을 비교해보는것도 재밌을거예요.

다음 미션에서는 input output으로 뷰를 나누지 않고 미션의 순서 혹은 각 기능별로 뷰를 나누어보겠습니다!(마치 Activity처럼) 아직 해보진 않았지만 예상되는 장점은 에러에 대한 예외처리가 좀 더 편해질 것 같습니다.


> inputNullControl은 다음 사항에 대한 연습을 위한 로직이라고 생각하면 될까요?

넵 맞습니다! 해당 힌트에 대한 로직이었습니다!
아직 _"논리적인 오류"_에 대한 기준을 제대로 확립하지는 못했지만 우선 입력값을 잘못 입력하는(숫자를 입력해야되는데 문자열을 입력했다던가) 경우에 대해 null로 처리하였습니다!

2023-02-27 07:04 UTC, briandr97 commented on src/test/kotlin/domain/PurchaserTest.kt
> +    )
> 다음 구문을 보고 다른 개발자가 한눈에 otherLottoBundle값을 예상할 수 있을까요?
이 부분을 보고 두 가지 생각을 했습니다.
1. 변수명을 좀 더 직관적으로 바꿔라
2. 다른 개발자가 otherLottoBundle이 뭔지 테스트에서 바로 알 수 있도록 해라

그래서 변수명으로 manualLottoBundle(수동 로또 번들)로 바꾸었으며 전역으로 따로 빼지 않고 각 함수 내부에서 사용했습니다.

이런 부분을 말씀하신게 맞는지 궁금합니다!

2023-02-27 07:04 UTC, briandr97 commented on src/test/kotlin/domain/lotto/LottoBundleTest.kt
> +    fun `plus가 잘 작동하는지 테스트`() {
넵 좀 더 명확하게 바꾸었습니다!

2023-02-28 04:55 UTC, woowahan-leah approved these changes
안녕하세요 빅스! 
마지막 리뷰 반영을 잘 해주셨습니다 💯 

조금 고민해보시면 좋을 내용을 코멘트로 달았으니 스스로 고민하는 시간을 가져보면 좋겠어요.
특히 수동/자동 로또를 어떻게 처리할지에 대해서는 로또 미션을 통해 진행할 수 있는 핵심 경험이라고 생각됩니다.

제가 스스로 생각할 수 있는 코멘트를 많이 남겼었는데 긴 시간동안 고생 많으셨습니다.
앞으로도 OOP를 진하게 경험하기 위한 양분이 되었으면 좋겠네요.

다음 미션도 화이팅입니다!

2023-02-28 04:55 UTC, woowahan-leah commented on src/main/kotlin/LottoController.kt
> +        checkError { purchaser.purchaseManualLottoBundle(getManualLottoBundle(purchaser.manualLottoCount)) }
> Input에서 받는 입력을 분기점이라고 가정하여 블록을 나누는 방법도 있을 것 같네요

이를테면 기존과 같이 각 블럭마다 checkError를 해주던 구문을
```kotlin
// before
private fun purchaseLotto(): LottoBundle {
    val purchaser = checkError { Purchaser(getMoney()) }
    checkError { purchaser.decideManualLottoCount(getManualLottoCount()) }
    checkError { purchaser.purchaseManualLottoBundle(getManualLottoBundle(purchaser.manualLottoCount)) }
    ResultOutputView.printPurchasingResult(purchaser)
    return purchaser.purchasedLottoBundle
}
```
다음과 같이 purchaseLotto()를 호출하는 곳으로 묶어서 해줄 수 있겠죠.
```kotlin
// after
val purchasedLottoBundle = checkError { purchaseLotto() }
```
즉, 매 Input 단위로 블럭을 지정하고 도메인 모델 유효성 검사 로직을 Input 단위로 끊는 것입니다. 매번 생성할때 체크하는 것이 아니라요. 이 방법도 정답은 아닙니다! 이전 방법과 뭐가 다른지 스스로 고민해보고 적절한 답을 찾아보세요.

2023-02-28 04:55 UTC, woowahan-leah commented on src/main/kotlin/LottoController.kt
> +        checkError { purchaser.purchaseManualLottoBundle(getManualLottoBundle(purchaser.manualLottoCount)) }
> 또 현재는 catch (e: Exception)와 다를 바가 없는 로직일 수 있을 것 같은데 이를 더 명확한 에러 구분으로 처리

catch (e: Exception)이 지양되는 이유는 뭘까요? 이러한 코드는 프로그램이 커질수록 예상치 못한 버그를 발견하기 어렵게 만들 수 있어요. (예를 들어 에러가 발생했는데 모든 에러를 catch문이 먹어서 프로그래머가 인지하지 못하는 일이 생길 수 있습니다) 나중에 미션을 진행하면서 조금이라도 구체적인 catch문을 작성하여 이러한 문제를 예방하는 편이 좋습니다.

checkError는 비교적 사용 목적이 명확하지만 프로그래머가 제대로 인지할 수 있도록 구체적인 에러를 명시하는게 어떤지 제안드린거였어요!

2023-02-28 04:55 UTC, woowahan-leah commented on src/main/kotlin/domain/LottoCount.kt
> +        require(manualCount <= totalCount) { "$PREFIX 수동으로 구매할 로또의 개수가 총 로또 개수보다 많을 수 없습니다. 수동 로또 개수: $manualCount, 총 로또 개수: $totalCount" }
구체적인 에러 상황 명시 👍 
이러한 에러를 IllegalArgumentException을 상속받는 다음과 같은 에러 형식으로 만들어보는 방법도 있습니다.
```kotlin
class CustomError(message: String = "어떤 이유로 에러가 생김") : IllegalArgumentException(message)
```
이런 에러 클래스를 만들면 어떤 장점이 있을까요?

2023-02-28 04:55 UTC, woowahan-leah commented on src/main/kotlin/domain/Purchaser.kt
> +class Purchaser(spentMoney: Money) {
근본적인 원인은 다음 세 가지라고 생각해요. 

1. Purchaser의 상태가 여러 번 나뉘어져 초기화될 필요가 있을까?
2. Purchaser가 외부의 조작 없이 스스로 일할 수 있도록 만들어보면 어떨까?
3. 꼭 Purchaser가 이 모든 일을 해야 할까?

LottoCount로 책임을 분리하려는 시도 좋았습니다 👍 
다만 한 발자국 더 나아가보자면... 로또를 구매하는 곳에서 수동 로또인지, 자동 로또인지 알 필요가 있을까요? 

외부에서 Purchaser의 책임으로 너무 많은 것을 할당한게 아닌가 하는 생각이 듭니다.
Purchaser에게 로또를 구매하는 책임만 갖게 하고 구체적으로 어떤 방법으로 구매하는지는 다른 클래스에서 알아서 하도록 해도 괜찮았을 것 같네요. 이 과정에서 상속이나 인터페이스의 구현 등의 방법이 사용될 수 있겠지만 구체적인 방법은 직접 고민해봐도 좋을 것 같아요.

로또 미션 2단계는 수동/자동 로직에 대한 책임을 어떻게 나누느냐가 가장 핵심이 되는 고민 중 하나입니다. 스스로 고민해보고 채널에도 공유해주면 좋겠네요!

2023-02-28 04:55 UTC, woowahan-leah commented on src/main/kotlin/view/InputResponseView.kt
> +        return readLine()?.toLongOrNull() // ?: throw IllegalArgumentException("$PREFIX 1000원 단위의 금액으로 입력해야합니다.")
이 주석은 꼭 필요한 주석일까요? 간단한 주석을 남길 때에도 주석이 꼭 필요한 상황인지 고려하여 남기시는게 좋습니다. 비록 이 프로젝트는 혼자 관리하시고 계시지만 여러 사람이 contribute 하는 프로젝트라면 이렇게 작성된 주석이 관리되지 않을 가능성이 높아집니다.
클린 코드 책에서 설명하는 주석에 대한 장을 읽어보시면 좋을 것 같아요!

FYI: https://nesoy.github.io/articles/2018-01/CleanCode-Comment

2023-02-28 04:56 UTC, merged

2023-02-28 05:03 UTC, woowahan-leah commented on src/test/kotlin/domain/PurchaserTest.kt
> +    )
@briandr97 현 상황에서 개발자가 이해할 수 있게 잘 구현해주셨다고 생각해요 👍 

장기적으로 프로그램이 커질수록 픽스쳐로 관리하고 싶은 샘플 코드들이 생길텐데요, 이러한 픽스쳐는 어떻게 관리하면 좋을지 스스로 고민해봐도 좋아요!
고민에 도움이 되도록 관련 예시를 첨부합니다.
- https://www.javaguides.net/2018/07/junit-4-test-fixtures-examples.html
- https://thalals.tistory.com/375