[수달] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #53
Opened 2023-02-25 11:24 UTC by otter66

잭슨님! 미션을 진행하며 궁금한점이 생겼습니다..!

<미션 요구사항>
* 참고로 코틀린에서는 아래와 같이 예외 처리를 한다. 장기적으로는 아래와 같이 예외 처리하는 걸 연습해 본다.
    * 논리적인 오류일 때만 예외를 던진다.
    * 논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.
    * 실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환한다.
    * 일반적인 코틀린 코드에서 try-catch를 사용하지 않는다.

위와 같이 값이 잘못되었을 때는 null을 반환하라는 요구사항이 있었습니다.
프리코스 때부터 지금까지는 에러를 발생시키거나 정상적인 값을 받을 때까지 다시 입력을 받는 방식을 사용하였습니다.
그리고 에러를 발생시키는 것보다는 다시 입력을 받는 것이 실제 사용에 더 올바른 형식이라고 생각합니다.

따라서 미션의 요구사항을 지키고 재입력을 받기 위해 try-catch가 아닌 runCatching을 이용해 
잘못된 값일 경우 null을 반환시켜 null일 경우 재입력을 받도록 하였습니다.
미션을 수행하며 이러한 방식을 사용하며 코드가 좀 더 간략해진다는 것 외에는 장점을 느끼거나 찾지 못하였습니다. 🥲🥲🥲…
혹시 이 외에 어떤 추가의 장점이 있을지 여쭤보고 싶습니다...!

2023-02-26 06:29 UTC, namjackson commented
> 따라서 미션의 요구사항을 지키고 재입력을 받기 위해 try-catch가 아닌 runCatching을 이용해
> 잘못된 값일 경우 null을 반환시켜 null일 경우 재입력을 받도록 하였습니다.
> 미션을 수행하며 이러한 방식을 사용하며 코드가 좀 더 간략해진다는 것 외에는 장점을 느끼거나 찾지 못하였습니다. 🥲🥲🥲…
> 혹시 이 외에 어떤 추가의 장점이 있을지 여쭤보고 싶습니다...!

코틀린에서는 CheckedException을 강제하지 않고, 에러가 아닌 로직으로써 예외를 처리하도록 가이드하고 있습니다. 
그렇기 때문에, 처리되지 않은 Exception으로 인해 프로그램이 강제로 종료되는 경우가 있는데요, 
safe한 프로그램을 작성하기위해선, 예측가능한 에러일 경우, null이나, 실패를 나타내는 Result,sealed클래스로 전닳을 추천하고있습니다.
실제로 kotlin의 api에서는 getOrNull, find 와 같은 부분에서, 에러가 아닌 null로 실패를 암시하도록 nullable객체 를 반환하기도합니다.

https://sejoung.github.io/2022/08/2022-08-11-effective_kotlin_item_7/
https://taes-k.github.io/2021/12/29/kotlin-checkedException/
가볍게 읽어보셔도 좋을거같아요!

2023-02-26 06:30 UTC, namjackson requested changes
안녕하세요 수달님
2단계 미션 고생하셨어요!
몇가지 고민할법한 포인트들, 질문에 대한 답변을 코멘트로 남겼으니 확인해주세요!

2023-02-26 06:30 UTC, namjackson commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun readPurchaseAmount(): PurchaseAmount? {
수동로또를 몇장 살것인가에 대한 Amount에 대한 부분과
구매하는 수동로또 리스트와 분리될필요가 있을까요?
수동로또번호를 받게되면, 구매하는 수동로또의 갯수도 당연히 알수 있을것 같아요 !

2023-02-26 06:30 UTC, namjackson commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
로또생성에 대한 부분은 LottoMachine에 위임해보아도 좋을거같아요!

2023-02-26 06:30 UTC, namjackson commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val lotteries: Lotteries = autoLotteries.plus(manualLotteries)
Controller에서 자동로또와, 수동로또를 따로 발행하여, 합치기 보다,
LottoMachine에 Lotteries를 발행하는 책임을 부여해보면 어떨까요?

2023-02-27 08:39 UTC, otter66 commented on src/main/kotlin/lotto/domain/LotteryNumber.kt
> +    private val number: Int
lotteryNumber.value라는 방식도 좋은 방식인 것 같네요!
외부에서 매개변수를 호출할 때 일관성을 위해 ".toInt()", ".toString()"과 같이 작성하였는데, 
내부에서 외부 로직과 관련지어 변수명을 짓지 않도록 하는 관점에서도 더 좋은 방법인 것 같습니다! 감사합니다!

2023-02-27 08:57 UTC, otter66 commented
잭슨 리뷰어님...! 
저번주 한 주동안 다른 크루들에 비해 부족한 것 같다는 걱정이 많았는데, 그것이 곧바로 코드의 실수로 곧바로 나타난 것 같습니다...ㅠㅠ
실수가 많았지만 이번에도 자세하게 피드백해주셔서 다시 기운차리고 열심히 할 수 있는데에 응원이 되었습니다!

또, 월요일 학습로그를 진행하며 궁금한 점이 생겨 여쭤보고 싶습니다!!!
- 로또 번호를 원시값 포장하는 것에 대해 data class를 추천해주셨는데, 
현재 코드에서는 value class가 더 좋지 않을까? 라는 고민이 있습니다!
작성한 학습로그: https://prolog.techcourse.co.kr/studylogs/2693

2023-02-27 10:09 UTC, otter66 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
리뷰어 잭슨님...!
여전히 View의 역할은 어디까지인지가에 대해서는 저만의 기준이 확정되지 않았습니다...🥲
현재는 값을 외부(controller 등)에서 원하는 형태로 가공해 반환하는 것까지를 View의 역할이라고 생각하고 코드를 작성하였습니다.
그러기 위해서 View에서 ", "를 기준으로 자르거나, 원하는 class 등으로 만들어 반환하도록 하였습니다.

제가 생각하기에 로또생성이란 곧 원하는 형태로 가공하는 작업인 것 같습니다.
LottoMachine에서 원하는 형태로 가공하기 위해서는 
controller에서 입력을 받아 domain에게 넘기고, 가공을 한 후 controller에게 가공된 값을 받는 과정이 복잡하다고 생각하였습니다...

추천해주신 방법의 장점이 view에서의 로직을 최소화하고, 역할을 각 클래스에 맞게 분리할 수 있다는 장점 때문이 맞을까요?

2023-02-27 13:17 UTC, namjackson commented
> 그리고 저번주 한 주동안 다른 크루들에 비해 부족한 것 같다는 걱정이 많았는데,
> 걱정들로 인한 잡생각들이 곧바로 코드의 실수로 나타난 것 같습니다...ㅠㅠ
> 실수가 많았지만 이번에도 자세하게 피드백해주셔서 다시 기운차리고 열심히 할 수 있는데에 응원이 되었습니다!

미션 수행을 잘하고 계십니다! 걱정안하셔도 될거 같아요 😄 
특히 피드백을 단순하게 그냥 적용하지 않고, 많이 고민하시면서 여러 예리한 질문을 주시는 모습이 인상적이예요! 👍 
이런 부분들이 수달님이 좋은 개발자로 성장하게되는 원동력이 될거 같아요!  
이번 미션과 다음미션들도 계속 응원하겠습니다! 👍 👍

2023-02-27 13:19 UTC, namjackson requested changes
안녕하세요 수달님 
피드백 반영 잘해주셨네요!
미션이 거의 마무리된것 같아요 😄 
몇가지 포인트들과 답변을 코멘트로 남겼으니 확인해주세요!

2023-02-27 13:19 UTC, namjackson commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
금액에 따른 조건으로 로또를 생성하는 책임이 LottoMachine에 있다고 생각이 들었어요!
View가 가지는 책임은 수달님이 생각하신 기준처럼 진행해주셔도 좋아요! 참고만 해주세요!
(LottoTicket과 같은 로또 발행전 클래스를 생성해주는 방법도 있을거같긴해요! 😄 )

2023-03-01 08:15 UTC, otter66 commented on src/main/kotlin/lotto/domain/LotteryNumber.kt
> +    val value: Int
data class를 소개해주신 덕분에 탐색하며 알아가는 과정에 value class도 알게 될 수 있어 좋았습니다!!
추가로 value class와 data class의 차이점을 알아보며 두 개 모두에 대해 이해도가 높아지기도 해서 좋았어요!!

그리고 말씀해주신 것처럼 LotteryNumber를 하나의 객체로 바라본다면 value class보다 data class가 적절할 것 같습니다!
그러나 현재는 class의 이름이 LotteryNumber라서 하나의 값으로 보아도 좋을 것 같다고 판단하였습니다!
(여기서 LotteryNumber가 아니라 LotteryBall과 같이 이름을 조금만 변경한다면 적절할 클래스의 종류가 달라질 것 같기도 하지만요...🤔)

그래서 이번에는 value class를 적용시켜 보았습니다!
객체 생성의 비용이 절감되고, 중복된 객체를 만들기 않기 위해 pull을 생성하는 과정을 줄일 수 있기 때문이라고 생각했기 때문입니다!
물론 이렇게 적용하는 과정에서 정적 펙토리 메서드에 대해 학습하고 적용해보며 연습할 수 있는 기회가 되어 좋았습니다!!

자세하고, 고민에 대해 결정할 수 있는 도움이 되는 코멘트들을 많이 남겨주셔서 정말 감사드립니다!!!

2023-03-01 10:18 UTC, otter66 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
이 부분에 대해서 모바일 5기 크루인 베르와 약 2시간 동안 고민을 해봤는데요..!!

저는 뷰에서 가공된 값을 보내고, controller의 기능을 최소화한다는 것에 집중하였습니다.
베르는 뷰의 역할을 최소화 하고, controller를 통해 전달해 도메인에서 값을 가공하는 등의 역할을 하는 것에 집중하였습니다.

저의 방법에서는 controller의 기능이 최소화되는 장점이 있지만, 도메인의 역할을 뷰에게 빼았긴 것 같기도 하다는 단점이 있는 것 같습니다.
베르의 방법에서는 controller의 기능이 조금은 늘어나는 단점이 있지만, 역할 분배가 좀 더 적절한 것 같다는 장점이 있는 것 같습니다.

아직 어떠한 방법이 더 좋은 방법인지 결정을 하지 못했기 때문에 다음 미션인 블랙잭에서는 잭슨 리뷰어님과 베르가 추천해준 방법을 사용해보고 두 방법을 비교해보고자 합니다!!

추천해주신 LottoTicket을 만드는 방법도 생각해 보았지만 단순히 값을 담는 것 외에는 기능이 없고, 역할이 1회성이라고 생각해 만들지는 않았습니다..!

2023-03-01 15:10 UTC, namjackson approved these changes
안녕하세요 수달님,
로또 미션 고생하셨습니다!
다음 미션들도 응원할게요! 💪

2023-03-01 15:10 UTC, merged