[핑구] 2단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #54
Opened 2023-02-25 12:46 UTC by pingu244

UserLottoGenerator를 생성하여 이 안에서 자동 로또까지 만들어 반환하게 해주었습니다. 
또, ManualLotto를 만들어 수동 로또를 이 안에 저장하게끔 하였습니다.
질문에 답변해 주신 것을 토대로 생각해 본 후에 클래스가 많은 일을 하진 않지만 수동 로또를 저장하는 용도로 만들어 보았습니다.
피드백 부탁드립니다~ 감사합니다!

2023-02-25 14:11 UTC, vagabond95 requested changes
고민의 흔적이 많이 보이는 구현이었습니다.
수동 로또를 최대한 분리하려고 노력을 많이 해주신 것 같아요 👍 
구현해주신 내용에 대하여 몇가지 코멘트 남겼는데, 확인 부탁드릴게요!

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/LottoController.kt
> +    private fun getNumberOfManualLotto(numberOfLotto: Int): ManualLotto {
함수 네이밍과 실제 리턴되는 대상이 불일치하는 것 같아요!

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/model/ManualLotto.kt
> +class ManualLotto(
해당 클래스는 로또 컬렉션을 가지고 있으므로 복수 표현형을 좀 더 드러내면 어떨까요?
외부에서 네이밍만 본다면, 단일한 ManualLotto 라고도 오해할 수 있어보여요.

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/model/ManualLotto.kt
> +    val lotto: MutableList<Lotto> = mutableListOf(),
MutableList 타입으로 리턴할 경우 외부에서 컬렉션의 수정이 가능할 것 같은데요. 
의도된 구현이실까요?

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/model/generator/UserLottoGenerator.kt
> +class UserLottoGenerator(
로또가 생성되는 방식을 Controller 에서 최대한 알지 못하게 하기 위해 취할 수 있는 방법은 무엇이 있을까요?

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/model/generator/UserLottoGenerator.kt
> +class UserLottoGenerator(
힌트를 드려보면
현재 UserLotto 의 경우 비교적 생성 과정이 잘 캡슐화 되어있는데,
ManualLotto 의 경우 Controller 가 많은 정보를 알고 있는 구조인 것 같아요.

2023-02-25 14:11 UTC, vagabond95 commented on src/main/kotlin/lotto/domain/LottoController.kt
> +    private fun getManualLotto(manualLotto: ManualLotto) {
manualLotto 를 전달받아 manualLotto 를 가져온다는 것은 조금 어색하지 않을까요~?

2023-02-25 16:13 UTC, pingu244 commented on src/main/kotlin/lotto/model/ManualLotto.kt
> +    val lotto: MutableList<Lotto> = mutableListOf(),
외부에서 값을 받아와 add하기 때문에 mutableList로 만들었는데 생각해보니 이렇게 한다면 외부 수정이 가능하겠군요! 수정하겠습니다.

2023-02-25 17:45 UTC, pingu244 commented on src/main/kotlin/lotto/model/generator/UserLottoGenerator.kt
> +class UserLottoGenerator(
수동 로또 생성을 위해서는 input 함수와 연결되는 것이 필수적이어서 매개변수로 input함수를 받는 함수를 전달해주었습니다. (input한 후 Lotto 객체화 시켜주는 함수)
이럴 경우 domain에서 input으로 접근했기때문에 MVC패턴에 위배되는걸까요?

2023-02-26 09:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/generator/UserLottoGenerator.kt
> +class UserLottoGenerator(
크게 위배된다고 생각하지는 않습니다!
제가 생각했던 방향에 대해 조금 더 말씀드려보면, 자동 로또의 경우 생성 시 별도 Generator 를 거치고 있고 / 수동 로또는 스스로 생성을 하고있는데요. 이러한 생성 방식의 통일이 이루어지면 어떨까 하는 생각이 들었어요.

2023-02-26 09:11 UTC, vagabond95 requested changes
빠르게 코멘트 반영해주셨네요 👍 

질문주신내용에 대하여 추가 코멘트를 남겼어요. 
이 부분은 꼭 반영되어야하는 사항은 아니므로, 논의 후 다음 요청에서는 머지하도록 하겠습니다~!

2023-02-26 13:32 UTC, pingu244 commented on src/main/kotlin/lotto/model/generator/UserLottoGenerator.kt
> +class UserLottoGenerator(
말씀해주신 것처럼 생성 방식을 통일하면 더 보기 좋을 것 같아 UserLottoGenerator에서 자동 로또와 수동 로또를 생성하도록 해보았습니다!

2023-02-27 02:06 UTC, vagabond95 approved these changes
긴 시간동안 미션 진행하시느라 고생 많으셨어요 👍 
해당 미션에서 제가 추가로 드릴 코멘트는 보이지 않는 것 같습니다.

로또 미션을 통해 얻어가는 것이 있으셨길 바라며, 미션 종료하겠습니다~!

2023-02-27 02:06 UTC, merged