[에디] 1단계 로또 제출합니다.
woowacourse/kotlin-lotto pull request #58
Opened 2024-02-21 06:42 UTC by junjange

잘 부탁드립니다!

2024-02-21 14:04 UTC, vagabond95 requested changes
안녕하세요. 에디 로또 미션 진행동안 잘 부탁드려요 :)

각 클래스와 함수를 적절한 단위로 나누어주셔서, 리뷰가 수월했습니다 👍 
남겨주신 코멘트는 참고하여, 개선 후 다시 리뷰 요청 부탁드릴게요~!

2024-02-21 14:04 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +    fun getLottoTicket(): Int = price.toInt() / MIN_PRICE
LottoTicket 과 Lotto 가 네이밍으로 봤을 때, 큰 차이를 알지 못할 것 같아요. 좀 더 적절한 이름은 없을까요~?

2024-02-21 14:04 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +    fun createLottos() =
요구사항 중 하나인 일급 컬렉션을 Lotto 리스트에 적용해볼 수 있을 것 같아요~!

2024-02-21 14:04 UTC, vagabond95 commented on src/test/kotlin/lotto/model/RankTest.kt
> +    @Test
나머지 등수는 테스트하지 않으신 이유가 있을까요~?

2024-02-21 15:05 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +class LottoMachine(private val price: String) {
View에서는 사용자를 통해 특정 값을 입력받고, 그 값을 통해 LottoMachine에서 로또를 만들고 있습니다. 여기서 View는 사용자에게서 입력만 잘 받으면 된다고 생각했고, LottoMachine에서는 입력값을 통해 로또를 만들 수 있는지 유효성 검사를 해야한다고 생각했습니다.

View에서 입력받은 price를 통해 LottoMachine에서 로또를 만들 수 있는지 검증하는 것이라고 생각합니다!

2024-02-22 04:40 UTC, junjange commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        val winningLotto = Lotto((winningNumber.split(",").map { LottoNumber(it.trim()) }))
input에 관한 로직은 View로 이동시켰습니다! 8b160da6f715fcf6da1cca25a2d1f1a75bfde47c

2024-02-22 04:40 UTC, junjange commented on src/main/kotlin/lotto/view/OutputView.kt
> +        println("---------")
View에 작성한 하드코딩도 상수화 진행했습니다! 281f5bd5f0a18c6885240512e92d7bb6b85fcaee

2024-02-22 04:42 UTC, junjange commented on src/main/kotlin/lotto/view/OutputView.kt
> +        Rank.entries.reversed().forEach { rank ->
LottoResult toString()을 커스텀하여, View에서는 LottoResult를 출력만 하도록 수정했습니다! ee5126dbb0f2d13ff16c720a80b232237bedec22

2024-02-22 04:45 UTC, junjange commented on src/main/kotlin/lotto/model/LottoAnalyzer.kt
> +class LottoAnalyzer(private val lottos: List<Lotto>, private val drawResult: DrawResult) {
object로 변경 후, calculateResult에서 사용되는 로직을 관련 객체에서 수행하도록 수정했습니다! 788fc05e1c8496303c667c0fe39104f3a77cbeb1

2024-02-22 04:46 UTC, junjange commented on src/test/kotlin/lotto/model/RankTest.kt
> +    @Test
1등부터 꽝까지 테스트 코드를 작성해보았습니다! f97d2a125c49ebda3a2b1ecc8fceefb211f25842

2024-02-22 12:14 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +class LottoMachine(private val price: String) {
역할은 위임하기 나름이니, 명확한 기준이 있다면 괜찮습니다!

2024-02-22 12:22 UTC, vagabond95 requested changes
코멘트 내용을 바탕으로 개선작업이 많이 진행되었네요 👍 
구현 의도도 같이 남겨주셔서 좋았습니다 ㅎㅎ

추가로 고민해볼 점에 대해 몇가지 남겼어요!
확인 후 리뷰 요청 부탁드릴게요.

2024-02-22 12:22 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Lotto.kt
> +class Lotto(val lottoNumbers: List<LottoNumber>) {
이미 중복 검증을 잘해주셨는데, 추가적으로 같이 생각해보면 좋을 부분이라 코멘트 남깁니다.

lottoNumbers 의 자료구조는 List 인데, Set 으로 바꾼다면 기본적으로 '중복을 허용하지 않는 자료구조' 이므로 도메인의 의미상 좀 더 적절한 자료구조가 될 수 있습니다.
또한, 외부에서는 lottoNumbers 가 List 일 경우 직접 코드를 확인하지 않는 이상 중복검사가 되었는지 알 수 없으니, 불필요한 중복검사를 다시 진행할 상황이 생길수 있지만 Set 이라면 그러한 상황을 피할 수 있습니다.

컬렉션을 무조건 List 로 만 사용하기보다 자료구조의 특징에 맞게 선택하는 연습을 같이 해보시면 좋을 것 같습니다~!

2024-02-22 12:22 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +class LottoMachine(private val price: String) {
LottoMachine 을 object 로 선언한다면 장/단점이 무엇이 있을까요?

2024-02-22 12:22 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Rank.kt
> +        }
현재는 보너스 번호 때문에  Rank, LottoResult 등의 클래스에서 매번 분기 처리가 필요한 상황인데요.
앞으로도 보너스 번호와 관련된 클래스는 모두 이러한 분기처리가 들어가야하고, 이는 추후에 변경사항이 발생할 경우 리소스가 많이 드는 작업이 될 수 있을 것 같아요.

분기처리 없이 등수를 구하도록 리펙토링 해볼 수 있을까요?

2024-02-22 14:27 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +class LottoMachine(private val price: String) {
LottoMachine을 object로 선언했을 때, 하나의 인스턴스만 생성되므로 메모리 측면에서 장점이 있을 것 같습니다. LottoMachine을 object로 선언했을 때 단점은.. 없는 것 같습니다..!

LottoMachine은 price를 의존하고 있지만, price는 getNumberOfLottoTickets() 메서드에서만 사용되고 있고 LottoMachine이 price의 상태를 가지고 있을 필요가 없기 때문에 object로 바꾸는게 더 적합할 것 같습니다!!

2024-02-22 14:48 UTC, junjange commented on src/main/kotlin/lotto/model/Lotto.kt
> +class Lotto(val lottoNumbers: List<LottoNumber>) {
개선했습니다! 3089df3abe53d63bd14ac79826e9ba10e3f88574
앞으로는 자료구조 선택에 대해서 좀 더 고민을 해보겠습니다.

2024-02-23 02:32 UTC, junjange commented on src/main/kotlin/lotto/model/Rank.kt
> +        }
현재 미션에서는 보너스 볼 당첨 유무를 통해 2등과 3등만이 구분되고 있습니다. 곰곰이 생각해봤지만, 관련한 분기처리를 아예 없애고 구현하는 방법은 생각이 나지 않아.. RankState라는 enum class에서 일반 당첨, 보너스 당첨, 미당첨을 구분하여 RankState에서만 분기 처리를 할 수 있게 구현했습니다. 이것으로 보너스 관련한 요구 사항이 바뀌더라도 Rank와 LottoResult를 바꾸지 않고 RankState 로직만 수정하면 해결될 수 있게 되었습니다! 요구하신 의도를 잘 반영했는지 모르겠네요..😂

4eb71594fa8e5af1c1fa1a04a0f62f751f736450

2024-02-23 12:01 UTC, vagabond95 approved these changes
추가로 코멘트 드릴 부분이 보이지 않아,
1단계는 여기서 마무리하겠습니다!

RankState 에 대한 내용은 다음 단계에서 같이 고민해주셔요 ㅎㅎ

2 단계에서 뵙겠습니다 :)

2024-02-23 12:01 UTC, merged

2024-02-23 14:32 UTC, junjange commented on src/main/kotlin/lotto/model/RankState.kt
> +enum class RankState {
헤헤 좀 더 고민해보겠습니다!