[로또] 벼리 1단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #78
Opened 2024-02-22 08:48 UTC by gaeun5744

안녕하세요 리뷰어님 이번 미션에 함께하게된 안드로이드 크루 벼리입니다!
앞으로 잘 부탁드립니다!!

---

코드를 작성하다 궁금한 점이 있어 질문 드립니다.

혹시 오류가 생기지 않을 때 까지 입력을 반복하는 `retryWhileNoException` 함수의 책임이 어느 클래스에 있다고 생각하시나요? 

처음에는 View에 책임이 있다고 생각했지만, 결국에는 프로그램의 전체 흐름과 관련된 메서드이기 때문에 Controller에 더 적합하다는 생각 또한 들었습니다.

Co-authored-by kimhm0728 <kimhm00728@gmail.com>

2024-02-23 00:28 UTC, KwonDae requested changes
로또 미션을 기능단위로 잘 구현해주셨습니다.

생각해보면 좋을만한 코멘트를 남겨드렸으니 확인해주시고,
충분히 고민하신 후 다시 요청주세요!

2024-02-23 00:28 UTC, KwonDae commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +}
WinningLotto 라는 일급컬렉션을 사용해주셨네요.
지금은 값을 wrapping 하는것 외에는 다른 역할이 없어서 클래스의 존재가 잘 드러나지 않고 있어요.
예를 들어, 당첨 번호 비교, 검증 같은 로직을 여기서 수행해보는건 어떨까요?

2024-02-23 00:28 UTC, KwonDae commented on src/main/kotlin/lotto/model/PurchaseInfo.kt
> +    private fun String.divideByLottoPrice() = toInt() % LOTTO_PRICE == 0
현재는 로또 가격이 1000으로 고정되어 있어서 문제가 없지만
로또 가격이 인상되었다면, `isMoreThanMin` 과 같은 비즈니스 로직 내부 코드도 변경되어야 하고 테스크 코드도 변경되어야 합니다.

티켓 판매가가 1000원 이었던 것을 기획쪽 요청으로 2000원으로 수정해달라는 요구사항이 생겼다면 어떤 일들이 병행되어야 하는지 생각해보면 알 수 있죠. 티켓 가격이라는 중요한 요구사항을 조금 더 유연하게 대처해볼까요?

2024-02-23 00:28 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +    }
> 1. retryWhileNoException 함수가 어디에 위치해야 하는지 궁금합니다.
> 처음에는 View에 책임이 있다고 생각했지만, 결국에는 프로그램의 전체 흐름과 관련된 메서드이기 때문에 Controller에 더 적합하다는 생각 또한 들었습니다. 혹시 오류가 생기지 않을 때 까지 입력을 반복하는 retryWhileNoException 함수의 책임이 어느 클래스에 있다고 생각하시나요?

결국 이 함수는 예외 발생시 출력을 하고 있고, 이 함수를 사용하는 함수들의 공통점은 View와 관련이 있다는 겁니다. 그러면 어디에서 관리하는게 보다 가독성이 좋을까요? 한번 더 고민해보셨으면 좋겠습니다 👍 

> 또한 해당 클래스를 따로 util 패키지에 넣어서 관리하는 것에 대해 어떻게 생각하시나요? 저는 코드 가독성을 위해 LottoController 안에 해당 코드를 위치시켰지만, retryWhileNoException가 다른 클래스에서도 사용될 수 있다는 미래 상황을 고려해 확장될 수 있도록 util 패키지에 따로 빼두어 언제든 사용할 수 있도록 해야 하나라는 궁금증이 생겼습니다.

`retryWhileNoException가 다른 클래스에서도 사용될 수 있다는 미래 상황을 고려해 확장될 수 있도록` 가 핵심인거 같습니다. 다른 클래스에서도 재사용이 된다..? 그렇다면 다른 재사용 되는 함수는 전부 util 패키지로 관리되어야 할까요?
`retryWhileNoException` 함수가 진정 어떤일을 하는지에 대해 보면 View와 관련이 있어보이는데, 특정 클래스에서 관리하기가 정말 애매하다면, View 패키지 내부에서 util 로 관리할 수 있겠네요!

2024-02-23 00:28 UTC, KwonDae commented on src/main/kotlin/lotto/view/OutputView.kt
> +object OutputView {
`3. object 함수에 대해 어떻게 생각하시나요?`

근본적인 내용으로 들어가보면 이해가 쉬우실 것 같은데요,
인스턴스화가 필요한가? 즉, 객체로 만들 필요가 있는 클래스인가? 에 대해 고민해보셨으면 좋겠습니다.
InputView, OutputView는 객체, 인스턴스화를 시킬 필요가 있는 대상일까요?
한번 고민해보시고 내린 결론을 저에게도 공유해주세요! :)

2024-02-25 14:13 UTC, gaeun5744 commented on src/main/kotlin/lotto/constants/StringConstants.kt
> +    const val OUTPUT_PROFIT_RATIO = "총 수익률은 %s입니다."
이 부분에 관해 질문이 있습니다! 실제 안드로이드 스튜디오에서는 strings.xml을 통해 문자열들을 관리하고 있습니다. 이렇게 하는 이유는, 추후 어플리케이션의 번역에 용이하기 위해서 라고 알고 있습니다.
실제 프로젝트에서는 따로 문자열을 관리하는 것을 권장하지만, 로또 미션에서는 다르게 적용되고 있는 이유가 궁금합니다!

2024-02-26 13:37 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +}
당첨 번호 비교, 검증과 같은 로직은 이미 파라미터의 타입인 Lotto와 LottoNumber 내에서 수행중입니다!! 혹시 WinningLotto의 파라미터 타입으로 원시값으로 사용한게 과도한 포장이라고 생각하시나요??

처음에는 
```
class WinningLotto(val lotto: Set<Int>, val bonusNumber: Int) {
```
이렇게 할려고 했지만, 검증 로직의 반복을 최소화하고, 각 도메인에 맞는 검증 로직을 배치하고자 이렇게 작성했습니다!!

2024-02-26 13:51 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/PurchaseInfo.kt
> +    private fun String.divideByLottoPrice() = toInt() % LOTTO_PRICE == 0
해당 코멘트에 대해, 외부에서도 티켓의 가격을 변경할 수 있도록 유연하게 대처하라는 의미로 받아들였습니다!!

하지만 이에 대해 의문이 있습니다. 가격이 변동된다면, companion object에 접근하여 `LOTTO_PRICE`를 변경하지 않고 외부에서 변경해야 하는 이유가 궁금합니다!
또한 파라미터가 많으면, 오히려 설정해야 하는 부분이 많아 재사용하는데 있어서 복잡하지 않을까 라는 생각이 들었습니다. 이러한 생각이 꼬리를 물어서 결국 `어디까지 확장성을 생각해야 하는가`라는 생각 또한 들었습니다. 
혹시 어디까지 확장성을 두어야 한다고 생각하시나요??

2024-02-26 14:09 UTC, gaeun5744 commented on src/main/kotlin/lotto/view/OutputView.kt
> +object OutputView {
계속 고민하다가 class로 만들기로 결정했습니다!
해당 문제는 객체 여부가 아닌, 메모리 관점으로 접근하는게 옳다고 생각했습니다.
InputView는 지속적으로 사용하는 클래스가 아닌, 뷰 로직에서만 사용하기 때문에 프로그램 런타임 내내 메모리를 차지하는 것은 낭비라는 생각이 들었습니다!!

2024-02-26 14:30 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +}
또한 해당 코멘트에 대해 궁금한 점이 있습니다.
`LottoNumber`나 `LottoStore` 또한 `WinningLotto`와 같이 별다른 로직이 없어서 해당 객체의 필요성에 대한 의문이 들었습니다.

프로그래밍의 요구사항에 원시값을 포장하라고 되어 있기에 우선은 구현하였지만, 이렇게 작은 로직에 대해서도 클래스를 추가하는게 맞을까요? 또한 원시값은 검증 로직으로서 그 의미를 다 하는 것일까요? 원시값을 객체로 보는 것이 맞을까요? 제이든은 어떻게 생각하시나요?

2024-02-27 13:32 UTC, KwonDae requested changes
피드백 반영해주시느라 고생많으셨습니다!
테스트코드 분리, 랜덤값 검증, 각 객체의 역할이 보다 명확해졌습니다.
한번 더 고민해볼만한 사항들을 코멘트로 남겨드렸으니 확인해주시고
다음 요청에는 바로 머지하고 2단계로 넘어가도 될 것 같습니다.
끝까지 화이팅입니다 💪

2024-02-27 13:32 UTC, KwonDae commented on src/main/kotlin/lotto/constants/LottoPrize.kt
> +            if (matchingCount == SECOND.amount) {
> 이 부분에 관해서는, 2등과 3등의 matchingCount가 서로 같아서 SECOND.amount 혹은 THIRD.amount 둘다 사용 가능하기에 그냥 그대로 5를 넣었습니다! 왜냐하면 둘 중 하나만 사용하면 의미가 헷갈릴수 있다고 여겼습니다..! 그래도 enum 값을 사용하는게 괜찮아 보이나요?

매직값은 함수의 정상적인 반환 유형에 적합하지만 특별한 의미를 지니고 있습니다. 이 케이스에만 들어맞기 때문에 이 값이 갖는 특별한 의미를 인지하지 못하고, 경계하지 않으면 수정사항에 정상적으로 대응하지 못할 가능성이 크겠죠
또한, 단위 테스트가 이 문제를 발견하지 못할 수 있다는 것입니다. 물론 지금 로또 미션에서는 5 라는 매직넘버를 사용해도 큰 지장은 없습니다. 다만, 이 부분을 인식하고 매직값을 피할 수 있는 방법에 대해 생각해보면 좋겠는 부분이어서 코멘트 드렸습니다 🙂
의도한 방향대로 잘 반영해주셨네요! 👍

2024-02-27 13:32 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val profitRatio = ResultCalculator.calculateProfitRatio(purchaseInfo, prizeCount)
Controller에서 priceCount, profitRatio 를 알아야 할까요?
WinningLotto 에게 필요한 재료들만 던져주고 WinningLotto 객체 스스로가 알아서 판단하게끔 행동을 부여하는건 어떨까요?

2024-02-27 13:32 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val profitRatio = ResultCalculator.calculateProfitRatio(purchaseInfo, prizeCount)
> 또한 해당 코멘트에 대해 궁금한 점이 있습니다.
> LottoNumber나 LottoStore 또한 WinningLotto와 같이 별다른 로직이 없어서 해당 객체의 필요성에 대한 의문이 들었습니다.
> 
> 프로그래밍의 요구사항에 원시값을 포장하라고 되어 있기에 우선은 구현하였지만, 이렇게 작은 로직에 대해서도 클래스를 추가하는게 맞을까요? 또한 원시값은 검증 로직으로서 그 의미를 다 하는 것일까요? 원시값을 객체로 보는 것이 맞을까요?
> 
> 만약 아닐 경우, 메서드가 2개 이상일 경우 클래스를 추가하라는 기준을 세우는게 나을까요? 제이든은 어떻게 생각하시나요?

해당 의문이 여기서 해결될 수 있겠네요.
벼리가 질문 주신 대로 현재 WinningLotto 는 별다른 로직이 존재하지 않습니다. 다만 현재 WinningLotto에서 수행 가능하지만 분산되어 있는 로직들을 각 객체에서 알아서 행동하게끔 부여한다면 의미있는 객체 활용이 될 수 있겠네요!
미션을 진행하면서 원시값을 어디까지 포장해야 하고, 어디까지 객체로 봐야 하는지 의문이 드는건 정말 당연하고 건강한 의문점입니다. 흩어져있는 로직들을 각 객체에 역할을 부여해보면서 이 의문점들은 하나씩 소거가 될거라고 생각합니다 :)

2024-02-27 13:32 UTC, KwonDae commented on src/main/kotlin/lotto/constants/StringConstants.kt
> +    const val OUTPUT_PROFIT_RATIO = "총 수익률은 %s입니다."
물론 안드로이드에서는 모듈별로 strings.xml 을 두어 관리가 가능합니다. 하지만 멀티모듈을 가정했을 때, 하나의 모듈에서 모든 string을 관리하게 될까요?
각 모듈에서 resource 를 갖는 목적이 무엇일까요?

2024-02-27 13:32 UTC, KwonDae commented on src/test/kotlin/lotto/ServiceTest.kt
> +class ServiceTest {
어떤 Service를 테스트 하려는 파일일까요?
어떠한 목적을 갖는 테스트인지 나타내기가 애매하다면 테스트코드를 분리해야 합니다.
아니라면 의미있는 네이밍을 지어주세요.

2024-02-27 13:41 UTC, gaeun5744 commented on src/test/kotlin/lotto/ServiceTest.kt
> +class ServiceTest {
앗 이부분에 관해서는
`fix: 파라미터 변경에 따른 테스트 수정` 해당 커밋에서 네이밍을 함께 변경했습니다!!!

2024-02-27 13:48 UTC, gaeun5744 commented on src/main/kotlin/lotto/constants/StringConstants.kt
> +    const val OUTPUT_PROFIT_RATIO = "총 수익률은 %s입니다."
아 이해했습니다!! 반복되는 코드를 최소화하고, 동시에 해당 상수가 어떤 영역에 해당하는지 이해하기 쉽게 하기 위해서는 `retryWhileNoException`의 경우와 같이 관련 패키지 내에 두는 것이 옳은것 같습니다! 이것이 모듈 내 resource 관리 방법에 해당하는 것 같습니다!! 현재는 view 혹은 model 내에서만 반복되는 상수가 없어서 각 파일 내에 상수를 두겠습니다 조언 감사합니다!!!

2024-02-27 14:01 UTC, gaeun5744 commented on src/main/kotlin/lotto/controller/LottoController.kt
> +    private val outputView: OutputView = OutputView(),
이 부분에 관해서는 상수와 일맥상통 한 것 같습니다..!!  여러 곳에서 쓰이기 때문에 object로 선언함으로써 모든 로직을 InputView, OutputView 내에서 처리하도록 하는게 옳은가? 라는 생각이 들었습니다. 왜냐하면 이 또한 프로그램이 확장하는데 있어서 걸림돌이 될 수 있다고 생각하기 때문입니다. 오히려 class로 선언함으로써, 추후 해당 객체를 상속받을 수 있는 가능성을 열어둠과 동시에, InputView,OutputView가 접근할 수 있는 객체를 제한함으로써 다른 사용자가 읽기 편하도록 만드는 것이 중요하다는 생각이 들었습니다. 

달아주신 코멘트들 덕분에 생각을 정리할 수 있었습니다 감사합니다!!😊😊

2024-02-27 14:08 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/PurchaseInfo.kt
> +class PurchaseInfo(purchasePrice: String, private val lottoPrice: Int = LOTTO_PRICE) {
아 제가 미처 생각하지 못한 방향이 있었네요!! 너무 당연하듯이 제가 로또 가격이 1000원인 경우, 2000원인 경우가 동시에 발생할 수 없다는 생각을 하고 있었네요... 생각해보면 복권의 종류가 많은데요ㅠㅠ
현재 `PurchaseInfo`는 추가적으로 고려해야할 파라미터가 lottoPrice 밖에 없지만, 추후 해당 객체가 커진다면 파라미터의 개수에 대해 더 고민해보겠습니다 자세한 설명 감사합니다!!😆

2024-02-27 15:13 UTC, gaeun5744 commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        val profitRatio = ResultCalculator.calculateProfitRatio(purchaseInfo, prizeCount)
조언 감사합니다!! 덕분에 Calculate라는 이름에 얽매여 `WinningLotto`이 맡아야 하는 책임을 간과했네요ㅠㅠ 
해당 코멘트를 보고 profitRatio 로직에 관해 고민을 많이 했습니다. 만약 `calculateProfitRatio` 를 `WinningLotto`객체에 넣을 경우, `lottoStore`/`prizeCount`/`PurchaceInfo` 이렇게 3가지의 파라미터가 필요하기 때문에 코드가 너무나 복잡해졌습니다.
이를 해결하고자 `WinningLotto`의 파라미터로 `lottoStore`를 추가해볼까 했지만, 이 둘은 독립적인 협력 관계에 가깝다고 여겨져서 서로 의존하지 않도록 만들어야 한다는 생각이 들었습니다.

이러한 생각을 거쳐, 결론적으로 `profitRatio`는 `WinnigLotto`와 `lottoStore`의 결과값에 의존하는 별개의 객체로 느껴져서 따로 이에 관한 클래스를 만들었습니다!!

2024-02-28 00:35 UTC, KwonDae commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    val lottos = List(purchaseInfo.amount) { Lotto(lottoNumberGenerator.generate()) }
WinningStatics 에서 코멘트 드린 부분과 연관성이 있겠네요.
LottoStore 는 사용자가 발행한 로또 정보를 들고있어야 할까요?
제가 현재 코드에서 이해하기에는 LottoStore는 가격에 대해 로또를 발행해주는 역할로 이해했습니다.
랜덤요소에 따라 구매 가격에 대해서 로또 발행을 하고 그 값을 반환만 하도록 변경해보는건 어떨까요?

2024-02-28 00:38 UTC, KwonDae commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +class WinningLotto(val lotto: Lotto, val bonusNumber: LottoNumber) {
WinningLotto 는 어떤 값을 프로퍼티로 갖고있어야 할까요?
상금에 대한 정보일테니 `각 등수별 당첨갯수, 수익률` 정도 갖고있으면 어떨까요?

2024-02-28 00:45 UTC, KwonDae commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +            .mapValues { it.value.size }
WinningStatics.kt 코멘트로 부터 이어질 내용 같습니다.
Controller로 부터 사용자가 발행한 로또 정보들의 집합(ex. Ticket), 당첨번호, 보너스번호를 전달받아
WinningLotto에서 당첨 정보(각 등수별 당첨 갯수, 수익률)을 내부적으로 수행하고 반환해주도록 해볼까요?

정말 간단한 예시입니다.
```
fun calculateWinningInfo(tickect, winningLotto, bonus) {
  val prizeCount = calculatePrizeCount(tickect, winningLotto, bonus)
  val profitRatio = calculateRatio(tickect, prizeCount)
 return WinningLoto(prizeCount, profitRatio)
}
``` 

식으로 미션의 요구사항 처럼 `하나의 함수는 한가지 일만 잘 하도록 해야한다` 를 유념하며 작성해볼 수 있겠네요!

2024-02-29 06:20 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +class WinningLotto(val lotto: Lotto, val bonusNumber: LottoNumber) {
이 부분에 관해서는, `WinningLotto`가 `각 등수별 당첨갯수, 수익률`을 속성으로 가지고 있기 보다는, 함수의 파라미터를 통해 비교하고자 하는 `lottos`를 받아서 결과를 반환하는게 옳다고 개인적으로 생각했습니다! 왜냐하면 `WinningLotto`와 비교하고자 하는 `lottos`가 여러 개 일 수 있기 때문에, 함수로 만들어야 유연하게 당첨갯수, 수익률을 얻을 수 있을거 같았습니다!!

2024-02-29 06:29 UTC, gaeun5744 commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    val lottos = List(purchaseInfo.amount) { Lotto(lottoNumberGenerator.generate()) }
계속 고민해보다가 lottoStore의 역할이 너무 적어서 객체로 분리하는게 무의미하게 느껴졌습니다ㅠ 그래서 `Ticket` 내부에서 `lottos`를 발행하도록 로직을 수정했습니다!!

2024-02-29 06:50 UTC, KwonDae approved these changes
마찬가지로 피드백 구현을 정말 잘 해주셨네요 👍 
처음과 비교했을 때 Controller에서 수행하던 로직들이 이제는 각자의 자리를 찾아간 것 같습니다.
1단계는 여기서 마무리 하도록 하겠습니다.
2단계 미션도 화이팅입니다 💪

2024-02-29 06:51 UTC, merged