[로또] 에디 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #81
Opened 2024-02-25 03:19 UTC by junjange

step2 미션 제출입니다 😊

### 완료한 기능 명세
- 로또 에러 핸들링
- 수동 로또 구매 로직 추가
- 예외 발생 테스트 코드 수정

### 고민과 해결 과정

- 예외 처리 커스텀을 어떤식으로 할까 고민하던 중, 주로 쓰는 require와 유사하게 만들면 좋을 것 같다고 생각했습니다. require 내부 코드와 유사하게 에러 핸들러를 만들었고 서비스에서 예상되는 예외를 직접 던지도록 구현했습니다. 예외가 발생해도 게임은 진행되어야 하기 때문에 GameState를 통해 게임의 상태를 관리했습니다.
- 이전에 1차 미션에서 "price 가 숫자 타입으로 '입력' 되었는지는 View 에서 검증하는 것이 좀 더 적절하지 않을까요?" 라고 질문주셨는데, 저는 그와 다르게 model에서 유효성 검증을 하고 있습니다. 그런데 미션을 수행할 수록 사용자로부터 문자열을 받게 되는 상황이 빈번하게 발생하고, 입력 값을 int로 바꾸는 과정을 팩토리 메서드를 통해 검증하고 처리하면서 코드량이 많아지고 있는 것 같습니다. view에서 검증을 해도 코드량은 많아지긴 할 것으로 예상되긴 하지만.. 이게 맞는지 잘 모르겠습니다.. 저는 클라이언트와 서버와의 관계라고 생각해서 클라이언트가 API를 통해 어떠한 입력을 주든 서버에서는 그것을 검증하고 처리 해야한다고 생각했습니다. 그냥 지금까지 하던 방식으로 진행해도 좋을까요?!..

2024-02-25 13:56 UTC, vagabond95 requested changes
2단계 진행하시느라 고생 많으셨습니다~!

구현해주신 내용을 바탕으로 몇가지 코멘트 남겼어요.
확인 후 리뷰요청 부탁드릴게요~!

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +    private fun getLottoBundleAndDrawResult(): Result<LottoResponse> =
네이밍에 And 가 들어간다는 것은 해당 함수가 2가지 이상의 역할을 수행한다는 신호인데요.
함수당 한가지 역할만 수행하도록 개선 가능할까요?

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/exception/ErrorCode.kt
> +enum class ErrorCode(val status: Int, val reason: String) {
에러코드 정리 👍

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/exception/ExceptionsHandler.kt
> +object ExceptionsHandler {
반복적인 작업을 공통화하는 시도 👍 

그런데, 서비스가 커질수록 모든 에러코드를 한 곳에서 관리했을 때 생길 수 있는 단점도 추후에는 같이 고려가 되면 좋을 것 같아요!

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/GameState.kt
> +sealed class GameState {
sealed class 활용 👍 

Enum, Sealed Interface 를 활용해도 동일한 목적으로 활용이 가능한데요,
각각 선택하는 기준에 대해 생각해보면 좋을 것 같습니다.

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoManualPurchase.kt
> +data class LottoManualPurchase(val count: Int) {
```suggestion
data class LottoManualPurchaseCount(val count: Int) {
```
에 더 가까울 것 같습니다!

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        const val MIN_PRICE = 1_000
해당 상수들은 이미 다른 모델에서 선언되어있는 상수로 보여요.
상수 선언의 중복을 제거해볼 수 있을까요?

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        val lottos = List(price.getNumberOfLottoTickets() - lottoPurchaseCount.count) { randomLotto() }
randomLottoCount 를 구하는 함수를 재활용 해볼 수 있지 않을까요~?

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +                Lotto(lottoManualPurchaseNumber.map { LottoNumber.from(it) }.toSet())
이와 같은 방식으로 Lotto 를 생성하는 코드가 다른 곳에서도 중복으로 사용되고 있는데요.
하나의 함수로 제공하여 재사용해봐도 좋겠습니다.

2024-02-25 13:56 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        lottoManualPurchaseNumbers: List<List<String>>,
이중 컬렉션은 쉽게 타입을 유추하기 어렵게 만드는데요.
일급 컬렉션으로 한번 감싸주는 것은 어떨까요?

2024-02-26 06:44 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        const val MIN_PRICE = 1_000
중복되는 상수 제거했습니다! 41135aa23827a9de7a28876c54d1819d1b813cd8

2024-02-26 06:44 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        val lottos = List(price.getNumberOfLottoTickets() - lottoPurchaseCount.count) { randomLotto() }
네네!! ab7087d8b0a6082ea892897d58b608b97d3f285b

2024-02-26 06:47 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +                Lotto(lottoManualPurchaseNumber.map { LottoNumber.from(it) }.toSet())
네네!! c3fa8e29fe31368a58da3470ef98d2d6e1493584

2024-02-26 13:45 UTC, vagabond95 requested changes
항상 빠르게 피드백 반영해주시네요 👍 
조금더 생각해보면 좋을 점에 대해 몇가지 코멘트 남겼어요.
확인 후 리뷰요청 부탁드릴게요~!

2024-02-26 13:45 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoAnalyzer.kt
> +    fun calculateResult(matchResultResponse: MatchResultResponse): LottoResult {
calculateResult 내에서 진행되는 로직은 MatchResultResponse 클래스가 '스스로' 수행할 수 있는 동작 아닐까요~?
MatchResultResponse 클래스의 역할이 파편화되었다고 볼 수도 있을 것 같아요!

2024-02-26 13:45 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        lottoManualPurchaseCount: LottoManualPurchaseCount,
manualPurchaseLottos 에서 lottoManualPurchaseCount 값을 추출해낼 수 있지 않을까요?
같은 의미를 가지는 상태는 최대한 재사용 해보면 좋을 것 같아요!

2024-02-26 13:45 UTC, vagabond95 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        val randomLottoCount = price.getNumberOfLottoTickets() - lottoManualPurchaseCount.count
getRandomLottoCount 의 호출에는 제한이 없는데, price 는 생성시에만 주입을 받으므로 
로또를 구매했을 때 price 값도 차감되어야 논리적으로 맞지 않을까요~?

추후에 수동으로 로또를 언제든지 구매할 수 있는 요구사항이 추가될 경우 버그가 발생할 수 있는 부분일 것 같아요.

2024-02-27 08:09 UTC, junjange commented on src/main/kotlin/lotto/model/LottoAnalyzer.kt
> +    fun calculateResult(matchResultResponse: MatchResultResponse): LottoResult {
감사합니다!! 5fdb71c49427acd01858663759d9f67b753c604b

2024-02-27 08:10 UTC, junjange commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        lottoManualPurchaseCount: LottoManualPurchaseCount,
감사합니다!! 1a739b169636c857e4c129a6f8b30c56c624858d

2024-02-27 08:11 UTC, junjange commented
LottoGameController가 GameState와 Price를 의존하고 있는 구조로 변경했는데, 게임 상태와 비용을 변경해야하기 때문에 불변성을 지키지 못하고 있습니다. 불변성을 지킬 수 있는 방법이 있을까요?!.. 아니면 어쩔 수 없는 부분일까요?!..

2024-02-27 14:10 UTC, vagabond95 commented
> LottoGameController가 GameState와 Price를 의존하고 있는 구조로 변경했는데, 게임 상태와 비용을 변경해야하기 때문에 불변성을 지키지 못하고 있습니다. 불변성을 지킬 수 있는 방법이 있을까요?!.. 아니면 어쩔 수 없는 부분일까요?!..

불변성을 지키려는 시도는 좋습니다. 다만, 모든 상태가 불변한 것은 사실상 불가능에 가깝습니다. 불가능한 것은 아니지만, 아주 제한적인 기능만 하는 프로그램이 되겠죠 :)

불변성도 중요하지만, 더 중요한 것은 상태를 관리하는 방식이라고 생각합니다.
이 부분은 주제가 너무 넓어서, 다른 코멘트 혹은 다른 미션을 진행하시다보면 좀 더 감이 잡히시는 때가 오실거라고 생각합니다. ㅎㅎ

2024-02-27 14:10 UTC, vagabond95 requested changes
이번에도 빠르게 리펙토링을 진행해주셨네요 👍 
Price 모델에 대해 좀 더 생각해볼만한 주제들이 있어 코멘트 남겼어요.
확인 후 리뷰요청 부탁드릴게요~!

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +data class Price(val money: Int = DEFAULT_MONEY) {
price 에 대한 리펙토링 시도 👍 
조금 더 생각할 거리들이 보여서 코멘트 남깁니다!

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +    fun plusPrice(strMoney: String): Price {
생성자에서는 Int 를 전달 받고 있는데, plus 에서는 String 타입을 받는 구조가 일관성이 없어보여요.
클래스를 사용하는 입장에서는 외부에 공개되는 상태 혹은 API 가 일관적인 형태로 제공되어야 이해하기 쉽고, 의도하지 않은 방향으로 활용되는 것을 방지할 수 있다고 생각합니다.

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +    fun plusPrice(strMoney: String): Price {
kotlin 에서는 `operator` 라는 키워드를 이용하여 산술 연산자 오버라이딩이 가능하므로 이번 기회에 활용해봐도 좋을 것 같아요.

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +    fun minusPrice(): Price = copy(money = money - getNumberOfLottoTickets() * MIN_PRICE)
plusPrice 가 실제로 더해지고자 하는 값을 받는다면,
minusPrice 도 동일한 규칙으로 빼고자 하는 값을 인자로 받는 것이 일관성이 있을 것 같아요.

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +    fun minusPrice(): Price = copy(money = money - getNumberOfLottoTickets() * MIN_PRICE)
또한, minusPrice() 라는 함수를 봤을 때 외부에서는 코드를 직접 확인하지 않은 한 얼마나 값이 빼지는 것인이 알 방법이 없기 때문에 좋은 형태의 함수가 아닌 것 같아요.

2024-02-27 14:10 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Price.kt
> +    fun minusPrice(): Price = copy(money = money - getNumberOfLottoTickets() * MIN_PRICE)
이러한 구조가 가능한 이유는 Price 가 `getRandomLottoCount`, `getNumberOfLottoTickets` 와 같이 Lotto 에 대한 의존성을 가지고 있기 때문이에요.

그런데, 잘 생각해보면 '가격' 과 '로또' 중에 어느 것이 더 상위 개념일까요?
다르게 얘기하면 로또가 가격에 대한 정보를 알고 있는 것과 가격이 로또에 대한 정보를 알고 있는 것 중 어느것이 더 자연스러울까요?

이 물음에 대한 답을 하다보면, 리펙토링에 대한 감을 잡으실 수 있을 것 같습니다 :)

2024-02-28 05:09 UTC, junjange commented on src/main/kotlin/lotto/model/Price.kt
> +    fun plusPrice(strMoney: String): Price {
사칙연산을 일관성 있게 하기 위해서는 우선 money를 무조건 int로 받어야 한다고 생각했습니다. 따라서 클래스 분리를 통해 돈의 상태를 나타내고 검증하는 Money 클래스를 만들어 리팩터링했습니다.

2024-02-28 05:39 UTC, junjange commented on src/main/kotlin/lotto/model/Price.kt
> +    fun minusPrice(): Price = copy(money = money - getNumberOfLottoTickets() * MIN_PRICE)
힌트를 주신 내용을 토대로 곰곰이 생각해보니, 구조가 조금 이상하다는 것을 느꼈습니다.
사용자에게 금액을 입력받아, 그것을 `Price`라는 객체에서 관리하는 것이 맞는지 의문이 들었고 `Price`에서 `Lotto`에 대한 정보를 알고 있는 것이 너무 이상했습니다. 저는 위와 같은 의문을 해결하기 위해 다음과 같이 구조를 변경했습니다.

`Controller`에서는 `InputView`를 통해 사용자에게 금액(예치금)을 입력받고 그 입력을 `Kiosk`에 넣어 예치금을 관리하게 했습니다. 예치금을 관리하는 이유는 금액을 넣으면서 로또를 연속해서 생성하는 경우에 이전에 사용하고 남은 예치금을 재사용하기 위해서 만들게 되었습니다. 
그리고 `Kiosk`에서는 `Deposit`(예치금)외에도 `Reocrd`(거래 기록)을 관리하는 것을 확인할 수 있습니다. 거래 기록을 프로퍼티로 관리하는 이유는 연속적으로 로또를 생성하고 예치금을 보관하는 과정에서 예외가 발생할 경우를 대비하기 위해서입니다. 예를 들어, 사용자가 로또를 여러 장 구매하고 예치금을 추가하는 도중에 어떤 이유로 예외가 발생한다면, 해당 예외 상황에 대한 처리가 필요합니다. 이때 예치금을 롤백하는 것이 바람직한데, 이를 위해서는 각 거래에 대한 정보를 기록해두어야 합니다. 따라서 거래 기록을 프로퍼티로 관리하여 예외 발생 시 롤백하는 과정을 매끄럽게 처리할 수 있게 되었습니다.
다음으로 `LottoBundle`를 생성하는 `LottoMachin`은 `Kiosk`에서만 수행될 수 있게 리팩터링했습니다.

2024-02-28 12:32 UTC, vagabond95 requested changes
좀 더 상위 개념의 도메인을 도입해서, 비즈니스 로직이 잘 통합 되었네요 👍 
해당 단계의 마지막 지점에 거의 다 온 것 같습니다!

구현해주신 kiosk 와 deposit 에 대해 몇가지 코멘트 남겼는데 확인 부탁드릴게요!

2024-02-28 12:32 UTC, vagabond95 commented on src/main/kotlin/lotto/model/Deposit.kt
> +        return copy(money = Money(money.value - other))
예치금의 개념이라면 뺴고자하는 값이 현재 남은 금액보다 큰 경우
즉, 마이너스가 되는 상황이 발생할 때의 예외처리가 필요하지 않을까요~?

2024-02-28 12:32 UTC, vagabond95 commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        kiosk.recordPurchase(money)
이 과정이 항상 같이 수행되어야 한다면, kiosk 내부에서 한번에 처리해주는 것은 어떨까요?
개별 스탭을 외부에서 처리해야할 경우 이러한 사항을 놓칠 수 있고 또 구현상으로도 강제하기 어려워 의도하지 않은 동작을 유발시키기 쉬울 것 같아요.

2024-02-29 00:28 UTC, junjange commented on src/main/kotlin/lotto/model/Deposit.kt
> +        return copy(money = Money(money.value - other))
헉 발생하지 않을 것이라고 생각했는데 메서드만 봤을 때는 충분히 가능한 상황이네요ㅠㅠ 감사합니다! 45b3a42dbe859c331ef64a89a9c15b9e29bcf323

2024-02-29 00:28 UTC, junjange commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        kiosk.recordPurchase(money)
넵!! 감사합니다 !! 2c00faa401e016b357d3a1fcc58e09505c8de6ec

2024-02-29 11:36 UTC, vagabond95 approved these changes
2단계에서 추가적으로 리뷰를 드릴 부분은 없는 것 같습니다.
구조적인 변경이 생기는 코멘트도 적극적으로 반영해주셨고, 점차 개선되는 구조가 보여서 기억에 남네요 ㅎㅎ

추가로 궁금하거나 논의하고 싶은 점이 있다면 미션 후에도 편하게 DM 남겨주세요.
다음 미션도 화이팅이십니다!

2024-02-29 11:36 UTC, merged

2024-02-29 15:14 UTC, junjange commented
2주동안 감사했습니다!!!🫡