[로또] 레오 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #83
Opened 2024-02-25 15:09 UTC by jaeyeongjo

안녕하세요! 2단계를 진행하면서 의문점이 생겨 질문드립니다.

논리적인 오류일 때만 예외를 던진다.
논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.
실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환한다.
일반적인 코틀린 코드에서 try-catch를 사용하지 않는다.

제 코드에 이 원칙들을 어떻게 적용할 수 있는지 잘 모르겠습니다.. 이와 관련하여 참고할 만한 자료나 레퍼런스가 있다면 공유해주실 수 있을까요?

2024-02-26 03:02 UTC, laco-dev requested changes
2단계 미션 잘 해주셨습니다.

지갑이라는 개념으로, 쇼핑하는 듯한 프로그램을 만들어주셔서 인상깊게 보았습니다.
전반적으로 지난번에 고생(?) 을 한 덕분인지 큰 구조 변경은 보이지 않습니다.

다만 지갑이라는 Stateful한 개념을 프로그램에 사용한다면, 그에 따른 책임과 사이드 이펙트를 고려해야만 합니다.

지갑이 여기저기 재사용 될 수 있으니까요 😱 

그 외에 몇가지 의견 같이 남겨드렸으니 마지막까지 화이팅입니다.

2024-02-26 04:25 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/LottoResult.kt
> -        return winningCountsByLottoRank[lottoRank] ?: 0
fun printResult(lottoResult: LottoResult) {
        println("\n당첨 통계\n---------")
        lottoResult.winningCountsByLottoRank.filterNot { it.key == LottoRank.MISS }
            .forEach { (lottoRank, count) ->
                println(
                    "${lottoRank.countOfMatch}개 일치${if (lottoRank.matchBonus == true) ", 보너스 볼 일치" else ""}" +
                        " (${lottoRank.winningMoney}원) - ${count}개",
                )
            }
        println("총 수익률은 ${String.format("%.2f", lottoResult.getProfitRate())}입니다.")
    }
    
   printResult 코드를 위와 같이 수정하여서, 굳이 사용하지 않아도 될것같아서 제거했습니다!

2024-02-26 06:17 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/AutoLottoMachine.kt
> +    }
로또가 발급이 된 후에 예산을 차감하도록 수정하겠습니다 ..!

제가 로또 구매 과정에 '지갑' 개념을 도입한 이유는 첫 번째로, 사용자가 입력한 예산(구입 금액) 같은 원시 값을 '지갑' 클래스로 포장함으로써, 이 금액의 유효성 검증을 관리할 수 있을 것 같아서입니다.

두 번째 이유는 로또 구매의 전반적인 흐름을 모델링하는 데 있어서 '지갑' 개념이 자연스러운 구조를 제공해줄 것 같아서입니다. 사용자가 먼저 수동으로 로또를 구매한 후 남은 예산으로 자동 구매를 진행하는 과정에서, '지갑'은 남은 금액을 추적하고, 얼마나 많은 로또를 추가로 구매할 수 있는지 결정하는 핵심 역할을 합니다. 이 과정을 '지갑'을 통해 명확하게 표현하고자 했습니다.

이러한 접근 방식에 대해 어떻게 생각하시는지, 제 접근 방식에 문제가 있는지 궁금합니다..!

2024-02-26 06:18 UTC, jaeyeongjo commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return AutoLottoMachine.createLottos(lottoBuyBudget, RandomLottoNumbersGenerator)
아..! 예시코드 참고해서 반영해보겠습니다

2024-02-26 06:22 UTC, jaeyeongjo commented on src/main/kotlin/lotto/view/InputView.kt
> +        return input.toIntOrNull() ?: INVALID_INPUT
그렇군요..! 반영하겠습니다

2024-02-26 06:23 UTC, jaeyeongjo commented on src/test/kotlin/lotto/model/AutoLottoMachineTest.kt
> +    val fixedLottoNumbersGenerator = FixedLottoNumbersGenerator(fixedNumbers)
다른사람이 봤을때, 이해하기 어렵거나 오해할만한 테스트내용들은 부연설명을 첨부하거나 개선하겠습니다!

2024-02-26 06:23 UTC, jaeyeongjo commented on src/test/kotlin/lotto/model/LottoBuyBudgetTest.kt
> +    }
반영하겠습니다!

2024-02-26 06:23 UTC, jaeyeongjo commented on src/test/kotlin/lotto/model/LottoBuyBudgetTest.kt
> +    @MethodSource("provideLottoPricesAndInvalidPrices")
그렇군요..! 반영하겠습니다

2024-02-26 06:36 UTC, jaeyeongjo commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
제 코드에서 require() 문을 통해 입력값 검증 시 예외를 발생시키고 있습니다. 이 경우, 잘못된 입력에 대해 바로 예외를 던져 프로그램이 종료되는 대신, null,sealed class을 반환해서 사용자에게 올바른 입력을 다시 요청하는 방식으로 처리해야 할까요?

2024-02-26 07:56 UTC, jaeyeongjo commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return AutoLottoMachine.createLottos(lottoBuyBudget, RandomLottoNumbersGenerator)
ManualLottoMachine에서 manualLottoBuyCount와 lottoBuyBudget을 내부 변수로 설정한 이유는, 사용자가 수동으로 구매할 로또의 수(manualLottoBuyCount)를 감싸서, 이 값이 주어진 예산(lottoBuyBudget)과 비교하여 유효한지 검증하기 위함입니다.

반대로 AutoLottoMachine은 수동 구매 후 남은 예산을 바탕으로 자동 구매를 진행하기 때문에, 별도의 내부 변수를 설정할 필요가 없다고 생각하여 object로 구현했습니다.

그렇기 때문에 두LottoMachine간의 로직이 어느정도 차이가 생긴것같습니다..!

2024-02-26 11:25 UTC, laco-dev commented on src/main/kotlin/lotto/model/LottoResult.kt
> -        return winningCountsByLottoRank[lottoRank] ?: 0
그러면 만약 출력 순서가 바뀌면 어떻게 대응해야 하나요?

2024-02-26 11:29 UTC, laco-dev commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return AutoLottoMachine.createLottos(lottoBuyBudget, RandomLottoNumbersGenerator)
네, 고민하신 내용은 앞으로의 학습을 조금 더 해보신 뒤 다른 방향으로도 고민 해보시면 좋을 것 같네요

2024-02-26 11:30 UTC, laco-dev commented on src/main/kotlin/lotto/model/AutoLottoMachine.kt
> +    }
접근방식의 문제라기 보다는, 불변 상태와 가변 상태에 대한 장단점과 차이점에 대해 이해하기를 기대했습니다.
지금 단계에서는 아직 위 개념을 학습하지는 않았기 때문에, 이 내용에 대해서도 마찬가지로 이후 학습을 하시면서 제가 드린 의견이 어떤 의미인지 찾아보시면 좋을 것 같아요

2024-02-26 11:35 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
입력 검증 실패를 UI라고 가정해봅시다.
키오스크에서 번호를 잘못 누른다고 오류가 나서 프로그램이 죽어버리지는 않겠죠?
혹은 입력할 수 없는 숫자를 누른다고 해서 오류가 나지 않고 사용자에게 적절한 안내를 하게 됩니다.

하지만 이러한 입력 끝에 번호가 만들어질 때 갑자기 이상한 값으로 만들어지게 된다거나 하면 의도치 않은 문제가 발생할 수 있습니다.

미션에서 제시하는 내용은, 모든 예외를 처리하거나  처리하지 말라는 의도가 아닌 각 관심사에 맞는 위치에서 정말 오류를 발생시킬 필요가 있을까? 를 생각해보기를 기대하는 내용입니다.

가령 toInt() 함수와 toIntOrNull() 함수가 왜 두개가 존재하는지 알았으면 하는 내용입니다.

2024-02-26 12:34 UTC, laco-dev requested changes
좋습니다.

같이 이야기를 나누다보니, 근본적으로 의문이 다시 드는 부분이 있어서 추가로 의견을 남겨두었어요.

한번 참고 해보시고, 어떤 차이가 있을지 고민 해보시면 좋겠습니다. 🙏🏻

2024-02-26 12:34 UTC, laco-dev commented on src/main/kotlin/lotto/model/LottoResult.kt
> +        return totalProfit.toDouble() / (totalCount * Lotto.PRICE_PER_LOTTO)
반영은 하지 않아도 좋습니다.

현재는 수익률을 계산하기 위해 전체 갯수가 실제 구입한 갯수라는 것이 보장됩니다.
하지만 winningCountsByLottoRank에 포함된 갯수가 전체 갯수와 일치하지 않을 수도 있고 로또의 가격이 상점마다 다르게 측정 될지도 모릅니다.

만약 아래와 같은 시그니처가 된다면, 어떤 차이가 있을까? 🤔 
```kotlin
fun getProfitRate(totalAmount: Int): Double { ... }
```

2024-02-26 12:34 UTC, laco-dev commented on src/main/kotlin/lotto/model/RandomLottoNumbersGenerator.kt
> +        }
마이너한 의견입니다.

대부분의 코드가 라인 수를 줄이기 위해서라거나 변수를 사용하지 않기 위해 체이닝 같은 코드를 많이 작성해 주신 것 같은데요.

지금은 바로 이해가 되겠지만, 이후에는 어떤 동작을 하는지 헷갈릴 지도 모르는데요.
일반적으로는 체이닝 함수의 경우 한줄에 하나씩 작성합니다.
```kotlin
LottoNumber.LOTTO_NUMBER_RANGE.shuffled()
   .take(N)
   .sorted()
   .map { ... }
```

2024-02-26 12:34 UTC, laco-dev commented on src/test/kotlin/lotto/model/AutoLottoMachineTest.kt
> +        assertThat(autoBuyedLottos).isEqualTo(fixedNumbers.map { Lotto(it.map(LottoNumber::of)) })
이 부분에서 다시 같은 생각이 조금 들었는데요. 🤔 
단순한 의견이고, 이렇게 바꾸라는 의도는 아닙니다.

이미 LottoNumbers Generator가 인터페이스로 분리된 상황이라면 머신 자체가 한번 더 분리될 필요가 있을까요?? 
```kotlin
class LottoMachine(lottoNumbersGenerator: LottoNumbersGenerator) {
   fun generate(count: Int): List<Lotto>
}

val manulLottoMachine = LottoMachine(Fixed)
val autoLottoMachine = LottoMachine(Auto)

```

2024-02-26 12:34 UTC, laco-dev commented on src/test/kotlin/lotto/model/LottoTest.kt
> +    }
- https://github.com/woowacourse/kotlin-lotto/pull/83#discussion_r1501993328

동일한 의견입니다.

2024-02-26 12:34 UTC, laco-dev commented on src/test/kotlin/lotto/model/ManualLottoMachineTest.kt
> +        val fixedNumbers = (1..24 step 6).map { (it..it + 5).toList() }
fixedNumbers가 무엇을 나타내는지 알기 어려워 보여요. 😱 
다른 사람이 봐도 이 동작이 무엇인지 충분히 이해가 될 수 있을까요?

테스트 환경이라면 직관적으로 이해할 수 있다면 여러가지 기법을 사용할 수도 있습니다.
https://blog.kotlin-academy.com/item-30-consider-factory-functions-instead-of-constructors-e1c747fc475

2024-02-27 01:00 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/LottoResult.kt
> -        return winningCountsByLottoRank[lottoRank] ?: 0
출력순서가 바뀐다면 printResult함수내에서 lottoResult.winningCountsByLottoRank을 원하는 출력형태로 파싱할 수 있을거같습니다!

2024-02-27 01:00 UTC, jaeyeongjo commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return AutoLottoMachine.createLottos(lottoBuyBudget, RandomLottoNumbersGenerator)
넵 감사합니다!

2024-02-27 01:38 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/AutoLottoMachine.kt
> +    }
아 그렇군요 ! 지갑의 예산이라는 가변상태를 만든다면 그에 따른 책임과 사이드 이펙트를 고려해야한다는 말씀이시군요!

2024-02-27 01:40 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/AutoLottoMachine.kt
> +    }
가변상태를 만들지 않아도 되는 상황에서는, 굳이 만들어서 그에따른 책임을 부담하는것보다는 가변상태를 만들지 않는게 더 나을수도있겠군요!

2024-02-27 01:43 UTC, jaeyeongjo commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
Inputview에서는 예외를 던지기보다는 toIntiOrNull()함수로 null을 반환해주었고, LottoNumber에서 예외를 던지게 하는게 각 관심사에 맞는 위치에서 오류를 발생시키는 예시인가요?

2024-02-27 01:44 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/LottoNumbersGenerator.kt
> +    fun generate(count: Int): List<List<LottoNumber>>
LottoNumbers 객체를 생성헤서 코드에 반영보겠습니다!

2024-02-27 01:45 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/LottoResult.kt
> +        return totalProfit.toDouble() / (totalCount * Lotto.PRICE_PER_LOTTO)
그렇군요..!  그 부분에 대해서는 미쳐 생각하지못했네요 
해당 부분에 대해서도 반영해서 다시 push해보겠습니다!

2024-02-27 01:46 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/RandomLottoNumbersGenerator.kt
> +        }
훨씬 보기편하네요! 반영하겠습니다

2024-02-27 01:47 UTC, jaeyeongjo commented on src/test/kotlin/lotto/model/AutoLottoMachineTest.kt
> +        assertThat(autoBuyedLottos).isEqualTo(fixedNumbers.map { Lotto(it.map(LottoNumber::of)) })
굳이 머신자체를 나누기보다는, 제시하신 코드처럼 하나의 머신에서 fixed,auto만 갈아끼우는게 훨씬 좋은 코드인것같습니다.
이것도 반영해서 push하겠습니다!

2024-02-27 01:47 UTC, jaeyeongjo commented on src/test/kotlin/lotto/model/LottoTest.kt
> +    }
수정하겠습니다!

2024-02-27 14:21 UTC, laco-dev commented on src/main/kotlin/lotto/view/InputView.kt
> +    }
너무 어렵게 생각하시지 않아도 됩니다.
관심사적인 접근보다는, 시나리오적으로 생각을 해보시면 좋을 것 같아요.

단순히 생각했을 떄, 이 코드에서 오류를 터트리는게 최선인가??? 라는 고민을 해보면 좋아요

2024-02-27 14:37 UTC, laco-dev requested changes
열심히 하시는 만큼, 아쉬운 부분 있으면 더 개선하고 싶으실 까봐 간단한 의견만 조금 남겨두었습니다.

다음번 요청에는 미션 종료할 수 있도록 하겠습니다. 👍🏻

2024-02-27 14:37 UTC, laco-dev commented on src/main/kotlin/lotto/model/Lotto.kt
> +        require(lottoNumbers.numbers.size == LOTTO_SIZE && lottoNumbers.numbers.distinct().size == LOTTO_SIZE) { LOTTO_SIZE_ERROR_MESSAGE }
이 유효성 검증은 이제 LottoNumbers에서 수행하면 될 것 같네요!

2024-02-27 14:37 UTC, laco-dev commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +}
이정도까지 빌드업을 했다면, 이제는 더이상 로또머신 자체가 불필요할 수도 있네요 ㅎㅎ
*객체가 단순히 리다이렉트만 해주고 있음

2024-02-27 14:37 UTC, laco-dev commented on src/main/kotlin/lotto/model/PurchaseDetails.kt
> +    autoPurchaseCount: Int? = null,
이 값이 null인 것과 0인 것에는 어떤 차이가 있을까요??

2024-02-27 14:37 UTC, laco-dev commented on src/main/kotlin/lotto/model/WinningBundle.kt
> +        }
지금은 Result의 Map이 외부로 직접 노출되고있어서 항상 0으로 초기화를 하도록 해야 했지만
이전처럼 상태를 내부로 감춘다면 굳이 복잡하게 초기화 할 필요 없이 있는것만 넣어 둘 수도 있어요.

일급 컬렉션의 순기능이 될 수 있습니다

```kotlin
class Result(private val map: Map<Rank, Int>) {
   fun getWinnintCountByRank(rank: Rank): Int { ... }
}
```

2024-02-28 02:01 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/PurchaseDetails.kt
> +    autoPurchaseCount: Int? = null,
사용자가 자동 로또 구입 갯수를 입력하지 않으면, 기본 값인 Null이 적용되게 해놨습니다.
기본 값을 Null로 정한 이유는 아무런 값이 없다(사용자가 입력을 하지 않았다)라는 의미입니다!

2024-02-28 02:08 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +}
그렇군요! 굳이 머신없이 구현가능할것같습니다 ㅎㅎ 반영하겠습니다

2024-02-28 02:08 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/Lotto.kt
> +        require(lottoNumbers.numbers.size == LOTTO_SIZE && lottoNumbers.numbers.distinct().size == LOTTO_SIZE) { LOTTO_SIZE_ERROR_MESSAGE }
그렇군요! 반영하겠습니다!

2024-02-28 06:00 UTC, jaeyeongjo commented on src/main/kotlin/lotto/model/WinningBundle.kt
> +        }
그렇군요 ! map을 외부로 노출시키지 않고, 내부적으로 컨트롤 하도록 코드를 구현해보겠습니다

2024-02-28 12:41 UTC, laco-dev approved these changes
피드백 반영 고생 많으셨습니다.

귀찮을지도 몰랐을텐데, 잘 따라와주셔서 좋았습니다.
앞으로의 미션에서도 지금까지 학습하고 경험한 내용은 모두 동일하게 적용되니 더욱 성장 하시기를 기대하겠습니다.

2024-02-28 12:41 UTC, merged