[로또] 팡태 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #92
Opened 2024-02-28 07:59 UTC by Hevton

안녕하세요 파이로 !!  
이번 미션도 잘 부탁드려요.

이번 미션에서 가장 고민했던 점은
1. step1을 진행할 때, LotteryStore는 두 가지 전략을 사용했어요.
랜덤 로또를 담은 티켓을 발행해주는 `RandomTicketGenerationStrategy` 전략 (프로덕션에 이용)
수동 로또를 담은 티켓을 발행해주는 `ExplicitTicketGenerationStrategy` 전략 (테스트에 이용)

이는 랜덤 로또 생성과 수동 로또 생성 전략을 갈아끼움으로써 A.테스트 장점 뿐 아니라 B. 추후 기능 확장성에 좋다고 생각했으나, 
step2에서 랜덤 생성과 수동 생성 전략 둘을 모두 포함할 수 있는 `MixTicketGenerationStrategy` 전략을 만들게 되면서, 기존 전략들이 굳이 개별적으로 존재할 필요 없이 하나의 방법으로 충분하다는 생각하여 이렇게 적용했어요.
<br/>

2. TDD 진행 시 test코드만 작성하고 커밋하는 방향과, 기능 구현까지 진행 후 한 번에 커밋하는 방향

커밋은 실행할 수 있는 단위가 되어야 하지 않을까 생각하여 후자가 더 이상적이라고 생각하고 있지만, 이번 미션에서는 전자로 진행했어요. 전자로 진행하면서 개발 도중 따로 불편함은 없었지만 협업으로 가게 되면 역시나 후자가 이상적이지 않을까 싶어요. 
이에 대한 파이로의 생각이 궁금해요.

<br/>
긴 글과 코드 읽어주셔서 감사해요.

2024-02-28 23:33 UTC, ghojeong commented
> 커밋은 실행할 수 있는 단위가 되어야 하지 않을까 생각하여 후자가 더 이상적이라고 생각하고 있지만, 이번 미션에서는 전자로 진행했어요. 전자로 진행하면서 개발 도중 따로 불편함은 없었지만 협업으로 가게 되면 역시나 후자가 이상적이지 않을까 싶어요.

저도 동의합니다. 커밋은 실행할 수 있는 단위가 되어야 편합니다.
꼭 협업을 하지 않고 혼자 구현하더라도, 기능에 무언가 문제가 생겨서 롤백을 할 때도 편합니다.
커밋메시지를 읽고 롤백했는데 테스트가 실패하고 빌드가 제대로 되지 않는다면,
대체 어디까지 옛날로 롤백을 해야할지 헤매게 됩니다.

만약 서비스 도중이라면, 실행과 테스트 통과하지 않는 커밋이 있을 경우,
롤백을 했음에도 테스트 실패로 배포가 안되거나 추가적인 장애가 연쇄적으로 일어나서,
폭풍 야근! 을 경험하게 될 수도 있습니다. ㅋㅋㅋㅋㅋ
그래서 저는 협업을 하던 혼자 개발을 하던 빌드, 테스트 통과, 실행할 수 있는 단위로 커밋을 남기는 것을 좋아합니다.

2024-02-29 02:23 UTC, ghojeong requested changes
팡태!
step2 기능 훌륭하게 구현해주셨습니다!
Controller 부분에서 리팩토링을 해볼만한 부분에 대해 피드백 남겨보았습니다.
다음주까지 시간 남았으니, 리팩토링할 여지가 있는 부분들 더 많이 피드백 드릴 수 있도록 하겠습니다!

2024-02-29 02:23 UTC, ghojeong commented on src/main/kotlin/utils/RandomTicketGenerationStrategy.kt
> +        return Ticket(lotteries, amount, LotteryPurchasePattern(0, lotteries.size))
> step2에서 랜덤 생성과 수동 생성 전략 둘을 모두 포함할 수 있는 MixTicketGenerationStrategy 전략을 만들게 되면서, 기존 전략들이 굳이 개별적으로 존재할 필요 없이 하나의 방법으로 충분하다는 생각하여 이렇게 적용했어요.

먄약 MixedTicketGenerationStrategy 로 충분하다고 생각하셨다면, 기존의 RandomTicketGenerationStrategy 를 왜 남겨두셨는지 궁금합니다.
추후에 어떻게 활용하겠다는 계획이 있으시나요?

2024-02-29 02:23 UTC, ghojeong commented on src/test/kotlin/utils/ExplicitTicketGenerationStrategy.kt
>  class ExplicitTicketGenerationStrategy(
마찬가지로 MixedTicketGenerationStrategy 가 있음에도,
ExplicitTicketGenerationStrategy 를 남겨야할 필요성이 있을까요?
참고로 너무 헤매지 않게 힌트를 남겨드리자면 저는 RandomTicketGenerationStrategy 는 팡태님의 이유가 중요하지만,
 ExplicitTicketGenerationStrategy 는 반드시 남길 필요성이 있다고 생각합니다.

RandomTicketGenerationStrategy 와 ExplicitTicketGenerationStrategy 를 남겨야하는지에 대해서 팡태님이 의견 남겨주시면 좋겠습니다.

2024-02-29 02:23 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
input 에 대한 예외처를 하고 계신데, 
아래의 미션 힌트를 한번 도전해보시기를 추천드립니다.

```
예외 처리를 통해 에러가 발생하지 않도록 한다.
참고로 코틀린에서는 아래와 같이 예외 처리를 한다. 장기적으로는 아래와 같이 예외 처리하는 걸 연습해 본다.
- 논리적인 오류일 때만 예외를 던진다.
- 논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.
- 실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환한다.
- 일반적인 코틀린 코드에서 try-catch를 사용하지 않는다.
```

2024-02-29 02:23 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        if (lotteryPurchasePattern.manualLottoCount > 0) {
모든 종류의 매직넘버 상수화 부탁드립니다.
그리고 Controller 에 조건문 혹은 반복문이 있을 경우,
가능한 model 의 테스트 가능한 비즈니스 로직으로 옮길 수 있도록 부탁드립니다.

2024-02-29 02:23 UTC, ghojeong commented on src/main/kotlin/utils/MixedTicketGenerationStrategy.kt
> +    }
```suggestion
  private fun generateRandomLotteries() = List(lotteryPurchasePattern.autoLottoCount) {
        Lottery(RandomLotteryGenerator.generateNumbers())
    }
```

가변리스트 대신 불변리스트로도 구현할 수 있다는 것을 참고하시면 좋을 것 같아 의견 남깁니다.

2024-02-29 02:23 UTC, ghojeong commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
```suggestion
data class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
```

LotteryPurchasePattern 이 현재 ofManual  말고는 그 어떤 로직도 가지고 있지 않는 듯 한데,
data class 로 취급해도 되지 않을까 해서 제안해봅니다.

2024-03-01 04:03 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        if (lotteryPurchasePattern.manualLottoCount > 0) {
step 1에서 step 2로 요구사항이 바뀌면서, 기존의 분리하고 모듈화했던 방식을 처음부터 다시 구성해야 될지도 모르겠다고 느꼈습니다.
이런게 유지보수의 어려움이고 소프트웨어 공학의 어려움이구나 라고 느꼈습니다.

그 중에서 대표적으로 LotteryStore에서 사용하는 전략들의 발행 단위가 Ticket이라는 점에서, 기존의 Random 전략과 Explicit 전략을 함께 사용하면 총 2개의 티켓이 나오기에 하나로 대체하기 어려웠다는 점이 있었습니다.

또한 여기에 남겨주신 코멘트처럼, 컨트롤러에서 매직넘버 조건문이나 반복문 등의 로직을 넣어주고 싶지 않은데,
'수동으로 구매할 로또 수를 입력해 주세요' 에 대한 입력이 0일 경우 '수동으로 구매할 번호를 입력해 주세요' 를 InputView에서 보여줄 이유가 없으므로 저렇게 조건문을 넣게 되었습니다.

2024-03-01 04:07 UTC, Hevton commented on src/main/kotlin/utils/MixedTicketGenerationStrategy.kt
> +    }
이런 방식은 전혀 생각하지 못했습니다. 정말 감사드립니다🔥

2024-03-01 04:13 UTC, Hevton commented on src/main/kotlin/utils/RandomTicketGenerationStrategy.kt
> +        return Ticket(lotteries, amount, LotteryPurchasePattern(0, lotteries.size))
@ghojeong 남겨놓으면서 두 가지 생각을 했습니다.

파이로에게 이러한 변경 결과에 대해 리뷰로 여쭤보고, 이야기를 나눈 뒤에 필요에 의해 나머지 코드를 정리하면 되겠다 생각했습니다.

그리고 한 켠으로는, 프로덕션이 아니라 학습의 과정이라고 중점적으로 생각한 탓에 이렇게 전략 패턴에 대해 진행했던 흔적으로 남겨놓을까도 생각이 들었습니다. 추후에 활용 계획은 없습니다. 제 욕심이라고 생각도 들어요.

2024-03-01 04:15 UTC, Hevton commented on src/test/kotlin/utils/ExplicitTicketGenerationStrategy.kt
>  class ExplicitTicketGenerationStrategy(
위에서 잠깐 말씀드렸던 것 처럼 RandomTicketGenerationStrategy는 현재 필요하진 않다고 생각합니다.

그리고 파이로의 생각과 달라서 불안하지만, 저는 파이로가 이 질문을 남겨주기 전까지 ExplicitTicketGenerationStrategy도 필요가 없다고 생각했습니다. 
이게 필요해지려면 현재 ExplicitTicketGenerationStrategy의 인자로 `explicitLotteriesNumbers: List<List<Int>>` 뿐 아니라 자동/수동에 대한 사용자 지정의 명시적인 값들을 각각 구분해줘야만 의미가 있어지지 않을까 생각했습니다.

의견을 남겨주시면 감사드리겠습니다.

2024-03-01 04:18 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@ghojeong 사실 어제부터 이 내용을 계속 읽어보고, 관련 문서들도 찾아봤는데 어려움이 있어서
방향에 대한 도움을 구하고 싶습니다.

" 논리 오류를 만들지 말라. 그럼에도 만들 수 밖에 없으면 그때 예외를 던지는거다. 그리고 예외를 던졌을 땐 호출부에서 관리하지 말고 전역적으로 관리하라. " 라는 내용이 맞을까요?

2024-03-01 06:58 UTC, Hevton commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
구현한 이유를 스스로 돌아볼 수 있는 질문을 주셔서 감사합니다.
저는 기본적으로는 클래스를 사용하면서, 데이터 클래스 적용에는 다음과 같은 점을 고려하는 것 같습니다.

1. 자동으로 생성되는 오버라이드 메서드들이 현재 필요한지
2. 아니면 이 클래스가 단순 데이터만을 보관하고 전달하는데에만 사용되는지

그 누군가가 이야기해주진 않았지만, 저는 의미론적으로 사용하고 있습니다.
데이터의 보관과 전달에 있어서는 보통 데이터 클래스를 사용하고 있고,
데이터와 함께 처리 기능이 있을 때는 보통 클래스를 사용하고 있는 것 같습니다.

그래서 팩토리 메서드와 데이터 처리를 담은 클래스이면서, 오버라이드되는 메서드들도 필요가 없다고 생각하여 클래스로 구현하였습니다.

한없이 부족한 지식에 도움을 주실 수 있다면 정말 감사드리겠습니다. 의견을 남겨주시면 제 생각 확장에 큰 도움이 될 것 같습니다.

2024-03-01 08:56 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@Hevton 

논리 오류를 만들지 말라는 의미는 아닙니다.
개발을 하면서 논리 오류는 언제나 생길 수 밖에 없습니다.
그 보다는 논리 오류가 생겼을 경우의, 예외처리에 대해서 집중하셨으면 좋겠습니다.
논리 오류가 생겼을 때 생긴 예외는, 던져질 수도 있고, 호출부에서 관리할 수도 있고, 전역적으로 관리할 수도 있고, 오류를 무시하고 디폴트 동작 혹은 값이 부여되도록 할 수도 있습니다.

미션 힌트는 이런 여러 방법 중에서, 코틀린 안드로이드 개발에서 자주 쓰이곤 하는 방법들을 소개한 것이고,
이를 연습해보자는게 피드백입니다.
참고로 연습해보자고 하는 방법들도 언제나 꼭 지켜야하는 정답이라고 생각하지는 말아주세요.
다만, 이 방법이 익숙하지 않다면 연습해볼 가치가 있는 방법들입니다.

2024-03-01 08:58 UTC, ghojeong commented on src/main/kotlin/utils/RandomTicketGenerationStrategy.kt
> +        return Ticket(lotteries, amount, LotteryPurchasePattern(0, lotteries.size))
> 진행했던 흔적으로 남겨놓을까도 생각이 들었습니다.

남겨놓는 이유라면 저는 이것도 나쁘지 않다고 생각합니다.
어차피 미션은 배포용 코드가 아니라, 연습하고 실력을 향상하는게 주목적이니까요.
다만, 실제 현업으로 일하게 되면 추후에 사용되지 않을 코드는 지워달라고 리뷰가 달릴 수 있다는 점은 말씀드려봅니다.
이유는 일단 코드가 남게되고 팡태님이 동료로써 존중받는다면, 다른 동료들이 팡태님이 남긴 코드를 유지보수하기 위해 정성을 쏟을 수 있기 때문입니다.

2024-03-01 09:02 UTC, ghojeong commented on src/test/kotlin/utils/ExplicitTicketGenerationStrategy.kt
>  class ExplicitTicketGenerationStrategy(
MixedTicketGenerationStrategy 는 로또 티켓 발행의 핵심 로직 중 하나이고,
언제든 다른 개발자가 만든 Strategy 로 변경될 수 있습니다.
단, 다른 Strategy 로 변경되었을 때 팡태님이 작성하신 코드의 테스트가 실패해서는 안됩니다.

언젠가 MixedTicketGenerationStrategy 가 아닌 다른 Strategy 가 쓰이게 되더라도,
팡태님이 작성하신 테스트 코드가, 팡태님이 작성하신 ExplicitTicketGenerationStrategy 로 테스트를 하는한,
다른 동료에 의해 테스트가 실패하는 경우는 없게 됩니다.

테스트 코드 또한 의존성 분리를 해야할 필요성이 있다는 관점에서 저는 ExplicitTicketGenerationStrategy 는 꼭 필요하다고 생각합니다.

2024-03-01 09:10 UTC, ghojeong commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
> 그래서 팩토리 메서드와 데이터 처리를 담은 클래스이면서, 오버라이드되는 메서드들도 필요가 없다고 생각하여 클래스로 구현하였습니다.

이런 기준이 있다면 저는 충분하다고 생각합니다.
저는 특히 팡태가 말씀주신 "이 클래스가 단순 데이터만을 보관하고 전달하는데에만 사용되는지" 조건은 저도 크게 동의하는 조건입니다.

제가 LotteryPurchasePattern 에 대해서 data class 를 제안한 이유는, LotteryPurchasePattern 가 ofManual 말고는 유의미한 메서드가 없어서, 
"데이터만을 보관하고 전달하는데에만 사용" 되고 있는 듯 하였기 때문입니다.

혹시 팡태가 생각하시기에 LotteryPurchasePattern 에 데이터의 보관과 전달 외에 다른 역할과 책임이 있는지 여쭈어봅니다.

2024-03-01 09:13 UTC, ghojeong requested changes
안녕하세요 팡태!
질문주신 내용들에 대해서 답변과 추가적으로 생각해볼만한 질문을 남겨보았습니다.
답변한 내용 중 어렵거나 추가적인 설명이 필요한 부분이 있다면 언제든 추가로 질문주세요!
혹은 중점적으로 도움받거나, 도전해보고 싶은 부분을 말씀주시면 그 부분 추가로 리뷰해드리겠습니다.

2024-03-01 09:32 UTC, Hevton commented on src/main/kotlin/utils/RandomTicketGenerationStrategy.kt
> +        return Ticket(lotteries, amount, LotteryPurchasePattern(0, lotteries.size))
감사합니다. 어떤 의미로 처음 코멘트를 달아주셨을지에 대해 이해하고 있습니다. 이에 대한 추가적인 말씀까지 나눠주셔서 감사합니다.
앞으로 더 생각해 볼 수 있을 것 같습니다.

2024-03-01 09:44 UTC, Hevton commented on src/test/kotlin/utils/ExplicitTicketGenerationStrategy.kt
>  class ExplicitTicketGenerationStrategy(
감사합니다. 테스트 코드 또한 의존성 분리를 해야할 필요가 있다는 점을 인지하고 있습니다.
티켓 발행이 자동/수동을 함께 진행하는 Mixed 전략 하나로 통합된 만큼
현재 ExplicitTicketGenerationStrategy은 테스트로의 역할을 잘 하지 못하고 있기에 생성자를 자동/수동의 의미를 지닌 변수 각각을 갖도록 수정해야만 의미가 있어질 것이라 생각했는데, 전략의 다양성을 생각했을 때 꼭 그럴 필요는 없겠다 생각이 들었습니다.

2024-03-01 09:58 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        if (lotteryPurchasePattern.manualLottoCount > 0) {
굉장히 무서운 내용이네요.
컴퓨터와 함께 지내는 시간이 길어질수록, 항상 답을 찾는 이분법적 사고에 몰두되거나 완벽주의적 성향이 강해지는 것 같아요.
그걸 내려놓고 진행하려다보면 결국 어느샌가 무언가를 처음부터 다시 해야하는 경우도 생기고.. 정답이 없는 내용인 만큼 어렵다고 느껴요. 그래서 확률을 높이기 위해 더 많은 견해와 방향을 바라보고, 유연한 사고를 가지려고 노력하고 있습니다.

2024-03-01 10:03 UTC, Hevton commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
제 생각에는 유효성 검사를 품고 있다는 점이 조금 애매한 경계였던 것 같습니다.
혹시 이에 대해서는 어떻게 생각하시는지 제가 여쭤볼 수 있을까요?

2024-03-01 11:18 UTC, ghojeong commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
객체는 상태(멤버)와 그에 따른 로직(메서드)를 통해 그 역할과 책임이 나타납니다.
유효성 검사는 현재 객체가 상태를 갖기 전 "생성"할 때 적용되는 로직이고,
객체가 실제로 상태를 가진 후에 갖게 되는 로직은 현재 전혀 없습니다.

상태를 갖기전의 로직은 극단적으로 말해서, 외부 유틸의 static 메서드로 제공되어도 아무 문제가 없습니다.
그렇기에 팡태님도 현재 유효성 검사를 내부 object 의 static 메서드로 제공하고 있습니다.
팡태는 LotteryPurchasePattern 의 역할과 책임이 "유효성 검사" 라고 생각하시나요?

만약 팡태가 의도한 역할과 책임이 유효성 검사가 전부이고, 
그에 따라 LotteryPurchasePattern 라는 객체의 이름을 지으신게 맞다면,
저는 객체 이름에서 유효성 검사라는 역할과 책임을, 동료 개발자의 입장에서 유추하기 어려웠다고 피드백 드려봅니다.

2024-03-02 02:46 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@ghojeong 관련된 문서들이나, 크루들의 PR 질문도 참고해서 찾아봤지만
논리 오류가 어떤 기준인지, 어떤 상황에 예외를 남기고 어떤 상황에 null을 하면 좋다는 것인지 어려운 내용인 것 같습니다 ㅜ..ㅜ
관련되어서는 더 고민해보겠습니다.

2024-03-02 03:04 UTC, Hevton commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
어떤 말씀이신지 와닿았습니다. 설명을 너무 잘해주시는 것 같아요.
현재 제가 무언가를 헷갈려하고 있는 것 같은데, 바로잡아볼 부분이 보여지면 좋겠습니다.

저의 개념적인 부분이 부족할 수 있지만, LotteryPurchasePattern 을 처음 설계할 때
만약 사용자가 5천원을 지불했고, '수동 로또 갯수 입력' 이 3이라고 주어진다면,
수동 로또: 3, 자동 로또: 2 라는 결과를 계산해주면서 각 값 또한 멤버로 갖고 있는 '구매 패턴에 대한 책임을 갖는' 클래스를 정의하면 좋겠다 라고 생각했습니다.

유효성 검사가 애매하다고 생각했던 것은, 에러 메세지도 그렇고 'LotteryPurchasePattern' 에 종속되는 유효성 검사라고 생각했기 때문인데요..!

생성 과정에서 1. 결과 계산과 2. 유효성 검사를 진행해준 뒤에 생성합니다. 
이 생성 과정은 클래스의 역할이라고 볼 순 없는 개념인가요??

2024-03-02 05:31 UTC, ghojeong commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
생성 과정도 클래스의 역할중 하나입니다. 하지만 생성과정 "만이" 클래스의 역할로 하려면, 저는 굳이 "클래스" 혹은 객체지향적인 설계가 필요한가? 라고 생각합니다.
그런 방식의 설계는 전통적인 C 의 struct 문법만으로도 충분히 구현할 수 있기 때문입니다.

LotteryPurchasePattern 를 설계를 할 때,  '구매 패턴에 대한 책임을 갖는' 클래스를 정의하려 하셨다고 들었습니다.
저도 클래스명을 보고 구매 패턴에 대한 역할이 LotteryPurchasePattern 에 있을 거라고 기대했습니다.

그리고 여기서의 구매 패턴이란, manualLottoCount 만큼 수동으로 로또를 발행하고, autoLottoCount 만큼 자동으로 로또를 발행한다 입니다.
그렇다면 저는 클래스명만보고 기대하는 것은 단순히 manualLottoCount 와 autoLottoCount 라는 숫자 데이터를 제공하는게 아니라, 오히려 이 숫자 데이터는 캡슐화되어 접근할 수 없고, 실제로 로또를 발행하거나,
로또를 발행하기에는 역할이 너무 커지는 것 같다면, 현재 자동 혹은 수동 로또의 발행이 가능한 상태인지 알려주는 boolean 값을 계산해서 보여주지 않을까 기대했습니다.
그렇다면 LotteryPurchasePattern 는 단순히 숫자 데이터를 제공하는 객체가 아니라, 역할과 책임에 걸맞는 유의미한 로직을 제공하는 객체가 됩니다.

지금은 역할과 책임에 걸맞는 유의미한 로직이 전혀 보이질 않습니다.

2024-03-03 13:39 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@ghojeong 안녕하세요 파이로, 이번 주말 동안엔 예전부터 잡혀 있던 여행 일정을 다녀왔습니다. 피드백 남겨주신 부분에 대해 어려움을 겪고 있던 터라 여행 일정 동안 머리를 비우며 다시 생각해보고자도 했고, 첨부해주신 문서와 또다른 크루들의 피드백 내용도 많이 살펴보며 생각을 정리해보고자 노력했습니다.

하지만 이와 관련해서 여전히 경계점이 명확해지지가 않네요..

처음에는 `논리 오류일 때만 예외(exception)를 던진다. 논리 오류가 아니라면 예외를 던지지 말고 null을 반환한다` 라고 이해했습니다.
그치만 첨부해주신 크루의 PR 피드백에서 `true/false로 조건을 지을 수 있다면 논리 오류이고 그렇기에 null을 활용할 수 있다`라고 말씀해주신 부분을 생각하면 제가 뭔가를 잘못된 방향으로 받아들이고 있지 않나 생각이 듭니다.

지금 이렇게 깊게 고민할 내용일까 걱정스러우면서도, 생각했던 것 만큼 쉽사리 이해가 되지 않으니 속상한 마음이 크고, 파이로께도 죄송하네요..

2024-03-03 13:47 UTC, Hevton commented on src/main/kotlin/model/LotteryPurchasePattern.kt
> +class LotteryPurchasePattern(val manualLottoCount: Int, val autoLottoCount: Int) {
@ghojeong 제가 바라보지 못한 넓은 관점의 견해를 남겨주셔서 감사드립니다. 말씀하신 내용을 토대로 스스로 생각해보니, 현재 LotteryPurchasePattern은 단지 유효성 검증만을 갖고 있고 이는 객체지향적인 설계로써 접목되기에는 아쉽다고 생각했습니다. 해당 클래스는 현재 파이로가 말씀해주신 것 처럼 데이터로써의 관점이 크기 때문에 data class로 정의하는게 더 가깝다는 생각을 할 수 있게 되었네요. 감사합니다.

2024-03-03 14:05 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
> 논리 오류일 때만 예외(exception)를 던진다. 논리 오류가 아니라면 예외를 던지지 말고 null을 반환한다.

이 부분이 제일 잘못 이해하신 것 같습니다.
안드로이드 개발 시에는 모든 경우에 예외를 던지지 않도록 한다. 라고 생각해주세요.
그 이유는 핸들링 되지 못한 예외가 하나라도 있을시, 앱이 크래시가 나면서 죽기 때문입니다.
가능한 default 값이 반환되면 좋고, default 값이 없다면 null 이 반환되어야 합니다.
null 대신 default 값을 선호하는 이유는 null 이 NullException 예외를 발생시켜,
마찬가지로 앱이 크래시나게 만들 위험이 있기 때문입니다.

예외를 던지는 것은 안드로이드에서 예외를 어떻게 핸들링하는지 충분히 숙지하고 던져도 늦지 않습니다.
지금은 그보다는 어떻게든 예외를 안던지도록 개발하는 방법을 연습하셨으면 좋겠습니다.

2024-03-03 15:15 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@ghojeong 감사합니다. 그럼 지금처럼 모델들에서 throw로 예외를 던지는 방법 대신, 예외에 대해 nullable이나 디폴트 값 또는 sealed class를 활용해보자는 방향으로 이해했는데 그 방향을 말씀하시는게 맞을까요?

2024-03-03 23:15 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
넵 저 힌트의 핵심은 "논리 오류일 때, 예외를 던진다" 가 핵심이 아니라,
"논리 오류가 아니면 예외가 던져져서는 안된다" 가 핵심입니다.

아침에 일어나서 읽어보니 저도 어제 피곤해서, 헷갈릴 여지가 있는 피드백을 남긴 것 같은데,
논리 오류를 포함한 모든 오류는 오류가 발생했을 때, "어떻게 핸들링할 것인가?" 가 핵심입니다.
"논리 오류" 라는 키워드에 꽂히기 보다는, 어떻게 크래시가 덜 나는 코틀린 앱을 만들 것인가에 집중하셨으면 좋겠습니다.

만약 논리 오류를 정말 깊게 공부하고 싶으시다면, Logical Exception 이전에 [Fallacy](https://en.wikipedia.org/wiki/Mathematical_fallacy) 라는 키워드를 깊게 공부하시기 바랍니다.
컴퓨터과학 전공 수업 때, 컴퓨터의 기반이 되는 이론으로 꼭 다루는 내용 중 하나입니다.
그와 동시에 기원전 2천년전부터 교과서에 실린 학자들이 다루어온, 공부할 수록 더 어려워지는 내용 중 하나입니다.
원하신다면 Boolean Algebra 관점에서 논리 오류가 무엇인지 더 자세히 설명해드릴 수 있으니 원하신다면 언제든 말씀주세요.
하지만 시간 여유가 많지 않은 상황에서, 개발 중심으로 생각하는 입장에서는 어떻게 앱이 크래시 나는 것을 막을 것인가? 관점으로 시간 투자를 했으면 합니다.

2024-03-03 23:22 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
> 지금 이렇게 깊게 고민할 내용일까 걱정스러우면서도, 생각했던 것 만큼 쉽사리 이해가 되지 않으니 속상한 마음이 크고, 파이로께도 죄송하네요..

저도 아침에 다시 읽어보니 논리적인 오류를 포함하여 무작정 예외를 던지지 말라는 쪽으로 제가 피드백을 드리고 있는 것 같군요.
이번 일은 팡태가 헷갈릴수 있는 피드백을 제가 드린 게 맞는 것 같습니다.
리뷰어들 말이 절대적인 것이 아니고, 피드백 또한 상황과 사람에 따라 달라질 수 있는 것이니,
만약 잘 모르겠다 싶으면, 지금처럼 리뷰어가 잘못 피드백을 주었을 수도 있다고 생각하고,
적극적으로 여쭈어주세요! 답답하시면 DM 을 보내시는 것도 괜찮습니다.

2024-03-03 23:22 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@Hevton 

다시 한번 제 피드백 의도를 정리해보면

1. 앱이 죽는 것을 방지하기 위해, 무슨 일이 일어나도 예외를 던지지 않는 방법을 연습해 볼 필요가 있다.
2. 던져진 예외는 반드시 핸들링 되어야 한다. 핸들링하기 위한 조건은 논리 오류일 경우에 알기가 쉬우며, 테스트도 가능하다.

정도 입니다. 무엇이 논리 오류인지, 아닌지 판별하기 어려우시면, 저는 "테스트 코드" 를 기준으로 판별하라고 하고 싶습니다.
논리 오류가 던져지는 상황을 테스트 코드로 작성할 수 있다면, 제 기준에서는 명확한 논리 오류입니다.
만약 테스트 코드로 작성되어 있지 않다면, 설사 논리 오류더라도 논리 오류가 아니라 언제 터질지 모르는 시한 폭탄으로 취급되어야 한다고 생각합니다.

2024-03-03 23:26 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
팡태님 코드에 대해 다시한번 생각해보니,
"앱이 터지지 않는다" 라는 관점에서 이미 잘 작성을 해주신 것 같습니다.

제가 힌트의 스타일을 강요하려다가, 오히려 팡태님을 혼란스럽게 한 것 같습니다.
강조하지만 리뷰어도 좋지 않은 피드백을 드릴 수 있고, 의문점이 생긴다면 지금처럼 언제든지 반박 혹은 질문을 주세요!
환영하겠습니다.

2024-03-03 23:30 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
> 논리적 오류는 True/False 를 판별할 수 있는 명확한 조건이 있고,
그렇기에 언제 오류가 발생해서 핸들링을 해야하는지 명확합니다.
그렇기에 해당 오류가 발생하는 경우에 대한 조건을 걸어서 예외를 던지는 대신에, null 값 혹은 Default 값을 부여할 수 있는 것입니다.

참고로 호두님께 드린 피드백에는 이 부분이 오해를 불러 일으킨 것 같은데,
null 값 혹은 default 값을 부여하는 것은 오류를 핸들링하는 방법 중 하나를 나타낸 것일 뿐입니다.
이건 제가 정말 헷갈릴 여지가 있게 잘못 글을 썼군요.

그보다 핵심은 "논리 오류는 언제 발생해서 핸들링을 해야하는지 명확" 입니다.
해당 오류가 발생할 수 있는 상황을 모두 테스트 코드로 작성할 수 있다면 저는 논리 오류라고 봅니다.
가령 문자열 입력에 대한 오류는 가능한 문자열을 입력할 수 있는 가짓수가 무한개라서 테스트하기 어렵습니다.

2024-03-04 03:52 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@Hevton 

[제이슨](https://woowacourse.slack.com/archives/C06DZU72A79/p1709462802601079?thread_ts=1709458213.391329&cid=C06DZU72A79) 이 논리적 오류에 대해서 공식적으로 질의 응답을 받을 수 있는 슬랙 스레드를 만드셨는데,
궁금하신 부분들 여기에 전부 질문해보시는 것은 어떨까 제안해봅니다.
리뷰어에게도 많은 도움이 될 것 같습니다.

2024-03-04 06:43 UTC, Hevton commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
@ghojeong 안녕하세요. 안드로이드 크루들 대부분 비슷한 고민을 갖고 있는 것 같아서 함께 이야기를 했습니다.

현재 코드에서 던지고 있는 오류들은 모두 테스트 코드로 검증하고 있습니다. 그렇다는 것은 논리 오류라고 볼 수 있다고 이해했습니다. (말씀해주신 2번)
하지만 예외를 던졌을 때 미처 대응하지 못했을 가능성을 생각하면, sealed class 등의 상태 패턴으로 관리할 수 있는 방법도 있다고 말씀하시려는 것 같다고 느꼈습니다 (말씀해주신 1번)

하지만 현재 제 코드에서는 모든 대응을 해주고 있으므로, 코드적으로는 잘 작성을 한 것 같다고 말씀해주신 것 같습니다.

그치만 예외를 던지지 않고 nullable을 활용하는 등 상태패턴으로 관리하기 위해 Amount 같은 클래스의 팩토리함수에서 Amount를 리턴하는 대신에 sealed class를 활용하여 Succes.Amount 나 Success.InvalidNumber 등으로 감싸자니 사용성이 아쉬울 것 같다고 생각했습니다. 더욱이 sealed 마저 사용하지 않고 nullable만 사용한다면 예외 메세지 자체를 받아볼 수 없다고 생각했습니다.

제가 생각했을 때의 말씀해주신 예외 처리의 활용 방안은, 안드로이드를 비유했을 때 Repository 단에서 작업들을 일괄적으로 runCatching 하여 예외를 잡아준 뒤에, View에 옵저버 패턴으로 반영해줄 때 try catch를 사용하는 것이 아닌 sealed class를 이용해서 상태를 적용하고 반영하는 방향이 아닐까 하는 생각이 들었습니다.

현재 제 콘솔 프로그램에서는 그럼 적용 가능성이 낮지 않을까 하는 생각이 들었습니다.

2024-03-04 23:34 UTC, ghojeong commented on src/main/kotlin/controller/LotteryController.kt
> +        val bonus = safe { readBonus(winningLotto) }
넵 저도 동의합니다. 무리해서 적용할 필요가 전혀 없는것 같습니다.

2024-03-05 00:48 UTC, ghojeong approved these changes
팡태!
로또의 미션 수행 기간이 지났으므로,
승인 후 머지하도록 하겠습니다.
다음 미션에 가셔서도 화이팅입니다! 🔥

2024-03-05 00:49 UTC, merged

2024-03-05 06:47 UTC, Hevton commented
짧은 시간이었지만 좋은 견해들 많이 남겨주셔서 감사드립니다.
더 많은 생각을 해 볼 수 있는 기회였습니다.

2024-03-05 06:49 UTC, ghojeong commented
@Hevton 

넵! 더 많은 생각을 해 볼 수 있는 기회였다니 다행입니다!
혹시 제 피드백 때문에 생각이 혼란스러워지거나 제한이 되었을까 걱정되었는데,
이렇게 말씀주셔서 감사합니다!