[로또] 해음 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #95
Opened 2024-02-28 12:16 UTC by haeum808

### 로또 2단계 미션을 구현 완료 했습니다.

안녕하세요 말리빈윤 1단계에서 좋은 피드백을 많이 해주셔서 감사합니다.
제가 잘 이해하지 못하고 넘어간 부분이 있었던거 같은데 다시 열심히 장고해서 고쳐나가겠습니다.
실력이 부족해서 2단계 요구사항을 추가했는데 잘 추가했는지도 알 수가 없는걸 느껴서 더욱 공부를 열심히 해야겠습니다.
이번 리뷰도 잘 부탁드립니다!!!

### 질문 사항입니다.

논리적인 오류가 아니면 null을 던지라는 요구사항이 추가되었습니다.
도메인 로직에서 발생하는 오류는 논리적인 오류라고 생각하고
논리적인 오류가 아닌 것은 예를 들어 사용자가 구입금액에 "1000"을 입력해야 하는데 "1000원"을 입력햇을 떄 null을 던져서 처리하라는 의미로 해석했는데 잘 해석한건지 궁금합니다.
자바와 코틀린이 다른 것중에 (IOException같은) 체크 예외가 없는 것인데
이런것처럼 예외 대신에 null을 받아서 처리할지 말지를 알아서 해라! 라는 이유인지 다른 이유가 있는지 궁금합니다. 

로또 생성을 제어하는 테스트를 하라고 리뷰남겨주셨는데 분명히 테스트를 하는게 좋다고 생각합니다.
하지만 제가 부족해서 이해를 잘 하지 못했습니다.
제가 생각한 것은 범위와 정렬을 테스트하고 랜덤적인 요소는 테스트하지 않는 것인지 궁금합니다.

`fun countMatch(lotto: Lotto): Int = (lotto.numbers intersect numbers).size`
위 코드처럼 'lotto.numbers'와 같이 lotto의 상태를 Lotto가 가져와서 사용하는데 이런 구조도 괜찮은지 궁금합니다.
객체는 상태와 행동을 가지고 자율적으로 행동해야하는데 다른 객체의 상태를 가져오는게 불편하게 느껴집니다.
그렇다고 WinningLotto에 Lotto들을 넣자니 객체가 책임이 너무 많아져 유지보수성이 저하된다고 생각합니다.
두 방법 중에서 트레이드 오프를 잘 판단해야 하는 것인지 아니면 지양해야할 코드인지 궁금합니다!.

 
### 전에 해주신 피드백에 대한 저의 생각을 정리해봤습니다. 감사합니다!

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502604553

- Integer 클래스 내부에서는 valueOf로 사용했던 값은 다시 사용할 수 있게 만들어져 있었습니다.
이를 차용해서 로또 프로젝트에 만들어서 사용하겠습니다.

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502583314

- Lotto에 더 가져올 역할을 찾아서 적용시키겠습니다. 어떤 책임을 어떤 역할이 해야 할지 감이 안잡혔는데 객체의 값을 꺼내서 계산하는 곳을 유심히 봐야할 거 같습니다.

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502585147

- LottoMachine의 책임으로 변경했습니다!

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502586044

- 여러 방식으로 로또 만들어서 전략패턴 처럼 만들려고 sealed class로 만들었습니다!

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502586093

- sealed class에 대해 무지해서 안쪽에 두었습니다. 바깥쪽에 둘 수 있는 지식을 얻었습니다!

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502583191

- plus도 infix를 활용해서 "+"를 써서 직관적으로 사용할 수 있듯이 contain를 "in"을 사용해서 직관적으로 변경하겠습니다. 감사합니다.

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502583314

- Lotto가 WinningLotto의 findRank를 더 잘 수행할 수 있는 책임이라 옮겼습니다.

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502598830

- BeforeEach의 단점을 확실히 알 수 있었습니다! 감사합니다!

https://github.com/woowacourse/kotlin-lotto/pull/67#discussion_r1502599990

- 로직을 바꿨으면 사용처를 보자! 명심하겠습니다!

2024-02-29 09:53 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!
제가 오늘까지 마무리 해야 할 업무가 있어서, 질문에 대한 답변은 내일 중에 달아두도록 할게요 ㅠ_ㅠ 양해 부탁드려요.
여러 코멘트 남겨두었으니, 피드백 반영 후 다시 리뷰 요청 부탁드려요!

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +
거의 다 왔네요..!!!
로또가 자기 자신과 보너스 번호까지 받아서 등수를 반환하고 있네요!

등수를 계산하는 게 로또 티켓이 해야하는 일이 적절할까요 ?_?

스스로가 자기 자신을 비교했을 때, 맞은 번호의 개수 정도만 반환하게 만들어보는 건 어떨까요?

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +) {
이 객체는 한 번 사용한 뒤, 재활용하지 못하는 형태네요!
객체를 한 개만 만들고, 새로 만들지 않고 로또 생성을 여러번 할 수 있도록 변경해보는 건 어떨까요?

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +    }
랜덤에 대한 요소가 다시 테스트 할 수 없는 형태로 변경되었네요 😥
외부로부터 주입 받는 형태로 변경해서 테스트가능하도록 변경해주세요!

개수만을 비교하는 것은 테스트에 큰 의미를 갖지 못한다고 생각해요.
개발자가 제어 가능한 환경에서 원하는 로또 티켓 자체를 검사해야 테스트도 의미가 있어요 :)

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +        }
캐싱을 활용해주셨네요! 👍
테스트를 통해 실제로 같은 인스턴스를 반환하고 있는지 검증해보는 건 어떨까요?

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/WinningLotto.kt
당첨 티켓이 여러 로또 티켓을 받아 등수를 계산해주네요!
그렇다면 1개의 로또 티켓을 받아 비교하는 역할도 이 객체에 위치하는 게 자연스럽다는 생각이드네요 :)
해음은 어떻게 생각하시나요?

2024-02-29 09:53 UTC, malibinYun commented on src/test/kotlin/domain/LottoMachineTest.kt
> +    }
수동 로또를 만들어내는 것을 개수로 검증하는 것이 어색하다고 느껴지네요.
수동 로또를 만들어내는 역할을 LottoMachine 에게 부여하고 싶다면, Lotto 객체를 생성하는 역할을 부여해보는 건 어떨까요?

2024-02-29 09:53 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
contains 내부 로직을 any를 활용하기 보다, set의 기능인 contains 를 활용해보는 건 어떨까요?
시간 복잡도에서 어떤 차이점을 보일까요?

2024-02-29 10:43 UTC, haeum808 commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
먼저 의미 상에서 차이가 있을것 같습니다. numbers가 Set, Map 컬렉션이 아니고 List 이더라도
any 안에 조건이 복잡하거나 contains 로직이 다르다면 any를 쓰는게 맞겠지만
이상황에서는 contains와 똑같은 역할을 하기 때문에 새롭게 만들어서 해석할 시간을 늘리기 보다는
이미 있는 라이브러리 함수를 사용하는게 맞다고 생각합니다.

시간 복잡도 측면에서는 numbers가 현재 Set이기 때문에 선형 탐색이 아닌 해시로 찾게됩니다.
any를 사용하게 되면 시간복잡도 O(n)이 나오지만 contains를 사용하면 O(1)이 나오게 되어 월등한 차이가 있습니다.
그래서 말씀해주신 것처럼 contains를 이용하는게 적합하다고 생각합니다.

컬렉션 함수를 잘 알고 쓰는게 중요하다고 느꼈습니다.
시간복잡도도 생각하면서 사용하겠습니다.

2024-02-29 10:51 UTC, haeum808 commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +        }
꼼꼼히 보지 못했습니다!
예외를 던지고 있기 때문에 무조건 검증하는게 좋다고 생각합니다!

2024-02-29 11:27 UTC, haeum808 commented on src/main/kotlin/lotto/model/Lotto.kt
> +
너무 일차원적으로 생각했었습니다.
lotto와 bonus는 WinningNumber가 가지고 있는데 이걸 굳이 "Lotto에게 메시지를 보내서 거기서 처리해!" 처럼 이상하게 코드를 작성했습니다.
객체 스스로 상태를 가지고 충분히 처리할 수 있는 책임인데 의미 없이 넘긴 책임이라고 생각합니다.
즉 잘못된 협력이라고 생각합니다.
변경하는게 맞다고 생각합니다!

2024-03-01 08:38 UTC, malibinYun commented
제 닉네임은 말리빈이에욧! 👾 깃헙 아이디는 malibin이 이미 있어서 성을 붙인거랍니다... (TMI)

> 논리적인 오류가 아니면 null을 던지라는 요구사항이 추가되었습니다.
도메인 로직에서 발생하는 오류는 논리적인 오류라고 생각하고
논리적인 오류가 아닌 것은 예를 들어 사용자가 구입금액에 "1000"을 입력해야 하는데 "1000원"을 입력햇을 떄 null을 던져서 처리하라는 의미로 해석했는데 잘 해석한건지 궁금합니다.
자바와 코틀린이 다른 것중에 (IOException같은) 체크 예외가 없는 것인데
이런것처럼 예외 대신에 null을 받아서 처리할지 말지를 알아서 해라! 라는 이유인지 다른 이유가 있는지 궁금합니다.

회원 가입을 예시로 들어볼게요.
회원 가입이 되어있지 않은 아이디와 비밀번호로 Member 객체를 생성하는 것은 논리적인 오류일까요?
회원 가입을 하기 위해 아이디 비밀번호를 입력해 생성하려 시도했어요. 이 때 이미 존재하는 아이디였다면, 이것은 논리적인 오류일까요?

> 로또 생성을 제어하는 테스트를 하라고 리뷰남겨주셨는데 분명히 테스트를 하는게 좋다고 생각합니다.
하지만 제가 부족해서 이해를 잘 하지 못했습니다.
제가 생각한 것은 범위와 정렬을 테스트하고 랜덤적인 요소는 테스트하지 않는 것인지 궁금합니다.

아래 처럼 정확히 개발자가 원하는 로또 반환 값을 테스트 해보시라는 의미었어요!
```kotlin
~~
val actualLotto = Lotto.makeLotto(makeLottoStrategy)
val expectedLotto = Lotto(6, 1, 3, 45, 20, 17)

assertThat(actualLotto).isEqualTo(expectedLotto )
```
사실 정렬된 것을 테스트하는 것은 큰 의미를 가져오기는 어려워보여요. 
어떤 특정한 상황에서는 오름 및 내림차순이 아닌 다른 정렬 방식이 요구 사항이 될 수도 있기 떄문이에요.


> fun countMatch(lotto: Lotto): Int = (lotto.numbers intersect numbers).size
위 코드처럼 'lotto.numbers'와 같이 lotto의 상태를 Lotto가 가져와서 사용하는데 이런 구조도 괜찮은지 궁금합니다.
객체는 상태와 행동을 가지고 자율적으로 행동해야하는데 다른 객체의 상태를 가져오는게 불편하게 느껴집니다.
그렇다고 WinningLotto에 Lotto들을 넣자니 객체가 책임이 너무 많아져 유지보수성이 저하된다고 생각합니다.
두 방법 중에서 트레이드 오프를 잘 판단해야 하는 것인지 아니면 지양해야할 코드인지 궁금합니다!.

스스로가 스스로를 받아 꺼내오는 것이 굉장히 어색할 수 있다고 생각해요 :)
하지만! 저는 이 부분에서는, "객체가 다른 객체의 값을 꺼낸다" 는 이 부분 만큼은 조금 예외라고 생각해요.
왜냐면 아예 다른 객체가 아닌, 갖고 있는 값만 다른 자기 자신이기 때문이에요.
그렇기에 countMatch 메서드 내에서, 파라미터로 받은 lotto의 private 멤버변수인 numbers 를 접근할 수 있었지요 :)

만약 이것 조차 예외를 두지 않는다면, equals() 등을 구현하기란 굉장히 어려울 거라 생각해요.
equals 의 자동 생성되는 구현이 어떻게 되어있는지도 들여다 보시면 좋겠네요!

2024-03-01 08:41 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
반드시 모든 Set이 시간 복잡도가 O(1)인 것은 아니랍니다!
Set은 interface이기에, 아래 다양한 구현체들이 존재해요!
코틀린에서 setOf() 메서드는 어떤 Set 구현체를 활용하는지도 알아보셔도 좋겠어요 🙂

2024-03-02 07:27 UTC, haeum808 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +) {
재활용하지 못하고 적절하지 못한 추가적인 객체라고 생각해서 Money 객체와 합쳐주었습니다.

2024-03-02 07:29 UTC, haeum808 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +    }
개수 비교는 정말 여기서 의미가 없다고 생각합니다.
제어 가능 및 테스트 용이하게 람다를 넘기는 방식으로 변경했습니다.

2024-03-02 08:46 UTC, haeum808 commented on src/main/kotlin/lotto/model/WinningLotto.kt
저도 그렇게 생각합니다! 그래서 LottoDrawingResult의 책임으로 변경하고 보너스 번호가 있는지 체크하는 책임을 WinningLotto에 위임했습니다.

2024-03-02 08:48 UTC, haeum808 commented on src/test/kotlin/domain/LottoMachineTest.kt
> +    }
확실히 개수를 검증하는 테스트는 여기 중요한 로직이 아닌것 같습니다.
또한 장고 끝에 LottoMachine보다 Lotto가 만드는것이 맞는 것 같아 Lotto로 책임을 옮겼습니다.

2024-03-02 08:58 UTC, haeum808 commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
toSet()은 LinkedHashSet이 되는것을 첨을 배웠습니다!
이외에도 TreeSet, TreeMap 등등 여러 구현체를 공부하겠습니다!

2024-03-02 10:56 UTC, haeum808 commented
죄송합니다! 말리빈 닉네임 잘못 부르지 않을게요!!

답변을 이해가 잘되게 써주셔서 감사합니다. 이해한 것을 바탕으로 다시 리팩토링 진행하여 코드리뷰 올립니다. 감사합니다.

2024-03-03 13:27 UTC, malibinYun requested changes
피드백 반영 고생 많으셨어요.
미션 코드가 발전해나가는 것이 눈에 띄네요!
크게 남길 코멘트가 많이 없었어요.
다음 요청으로 미션 마무리 지을게요! 피드백 반영하시거나, 시도해보고 싶은 것이 있다면 반영해주시고 리뷰 요청 부탁드려요. 기타 질문들도 환영이니, DM으로 질문 주셔도 좋아요!

2024-03-03 13:27 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +data class Lotto(val numbers: TreeSet<LottoNumber>) {
Set 대신 TreeSet을 사용해주셨네요!
인터페이스를 사용하지 않고 구현체 class를 사용하면 어떤 차이점이 생길까요?

다른 Set 구현체를 사용해야하는 요구사항이 생긴다면, 코드는 어떤 변화가 생길 수 있을까요?

이팩티브 코틀린 서적의 아이템 27을 읽어보셔도 좋겠어요 :)

2024-03-03 13:27 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoDrawingResult.kt
> +
현실세계에서는 사람이 당첨 번호를 보면서 로또가 당첨인지 아닌지 판별하지만,
프로그래밍 세계에서는, 당첨 로또 번호 스스로가 다른 로또를 비교해서 결과를 내어주는, 물체가 자율성을 가지는 특이한 마법의 세계로 만들어볼 수 있어요!

```kotlin
val countOfMatch = targetLotto.countMatch(winningLotto.lotto)
```
위 코드에서 winninglotto의 값인 lotto를 꺼내서 전달해주는 곳이 있으니, 메시지를 던지는 것을 좀 더 강화해볼 수 있겠어요.

"로또 결과" 가 당첨을 비교해주는 것 보다,
당첨 로또가 비교해서 "로또 결과"를 만들어내는 것이 현실 세계를 빌어 조금 더 자연스러운 느낌을 준다고 생각해요 :)

2024-03-03 13:27 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +) {
> 재활용하지 못하고 적절하지 못한 추가적인 객체라고 생각해서 Money 객체와 합쳐주었습니다.

그런 의미는 아니었어요..!
로또를 생성하는 기능을 활용하기 위해서는 매번 이 LottoMachine 객체를 새로 만들어야하니,
LottoMachine객체를 한 번만 만들면서 로또를 생성하는 기능을 몇 번이고 재사용할 수 있는 형태로 변경해보시라는 의미었어요🙂

2024-03-03 13:27 UTC, malibinYun commented on src/main/kotlin/lotto/model/MakeLottoStrategy.kt
> +}
자동과 수동 로또 생성 전략을 하나로 묶고 싶으신 흔적이 보이네요!
하지만 이런 형태라면, 수동 로또 1개당 수동 로또 생성 전략 객체를 1개씩, 1대 1로 만들어야하는 단점이 생기겠어요.
디자인 패턴에 매몰되지 않고, 랜덤의 요소만을 분리해보는 건 어떨까요?

2024-03-03 13:27 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoDrawingResult.kt
> +
그리고 이 로직에 대한 테스트가 빠져있네요!
테스트 코드도 꼭 작성해주세요!

2024-03-04 03:55 UTC, haeum808 commented on src/main/kotlin/lotto/model/Lotto.kt
> +data class Lotto(val numbers: TreeSet<LottoNumber>) {
구현체를 사용하면 그 구현체에 너무 의존하는 문제가 생길것 같습니다.
요구사항이 바꼈을때 TreeSet -> Set으로만 바꾸고 아래 메서드 잘돌아가 바꾸지않아 문제가 생길 수 있습니다.

2024-03-04 03:58 UTC, haeum808 commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +) {
아하 이해했습니다. 로또 만드는 것을 재사용할 수 있는 형태로 변경하겠습니다.

2024-03-04 04:15 UTC, haeum808 commented on src/main/kotlin/lotto/model/LottoDrawingResult.kt
> +
그렇네요! 논리적으로 당첨 로또가 갯수를 세는게 맞다고 생각합니다.
테스트 코드도 추가하겠습니다.

2024-03-04 04:16 UTC, haeum808 commented on src/main/kotlin/lotto/model/Lotto.kt
> +data class Lotto(val numbers: TreeSet<LottoNumber>) {
이펙티브 코틀린 아이템 27을 읽고 추상화의 장점과 단점을 확실하게 알 수 있었습니다.
언제 추상화할지 안할지 기준을 잘 세워보겠습니다.

2024-03-04 04:27 UTC, haeum808 commented on src/main/kotlin/lotto/model/MakeLottoStrategy.kt
> +}
객체가 너무 많이 생겨나는 문제가 있었습니다. 랜덤의 요소만을 분리하겠습니다!

2024-03-05 02:22 UTC, malibinYun approved these changes
로또 미션 완주하시느라 고생 많으셨어요 :)
미션은 이만 마무리하도록 하겠습니다.
다음 블랙잭 미션도 잘 마무리 짓길 응원할게요!

2024-03-05 02:22 UTC, merged