[예니] 로또 2단계 제출합니다.
woowacourse/kotlin-lotto pull request #96
Opened 2024-02-28 14:46 UTC by JoYehyun99

### 이전 피드백 수용
반영한 부분들에 대해 😁 이모지 남겼습니다!
해당 부분만 질문 이해가 어려워서 일단 넘겼습니다,,!
> 어떤 입력 값이 들어와서 발생한 예외인지 메시지에 담아보는 건 어떨까요?
어떤 장점이 생길까요?

### 수정 사항
- 수동 로또 입력 기능
- `예외 처리를 통해 에러가 발생하지 않도록 한다.` : 최대한 null 반환하도록 변경했는데 제가 잘 이해한 건지 모르겠습니다,,,! 이 부분에서 어려움을 느껴 시간이 좀 걸렸습니다 😭 일단 유효하지 않은 값들을 입력할 경우, 재입력 받을 수 있도록 수정했습니다!

2024-02-29 14:45 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!
질문에 대한 답변은 내일 중에 코멘트 달아놓을게요 ㅠ_ㅠ
오늘은 제가 힘이 너무 없어서.. 내일 회복한 다음 좋은 상태로 코멘트 남겨놓을게요!
여러 코멘트 남겨두었으니, 충분히 고민해보시는 시간 가져보시면 좋겠어요 :)

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +    fun hasMatchingBonusNumbers(bonusNumber: LottoNumber): Boolean = numbers.contains(bonusNumber)
in 연산자에서 contains 함수로 변경한 이유가 무엇이었나요 ?_?

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +        fun of(vararg numbers: Int): Lotto = Lotto(numbers.map { LottoNumber.valueOf(it) }.filterNotNull().toSet())
요 부분은 부 생성자가 아닌 팩토리 함수로 분리한 이유가 무엇이었나요 ?_?

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoMachine.kt
> +        numbers.map { number -> Lotto(number.mapNotNull { LottoNumber.valueOf(it) }.toSet()) }
랜덤 요소를 잘 분리해주셨네요!
로또 티켓 자체를 생성하는 로직은 조금 비슷한 부분이 있어 보여요.
자동 발급 로직에서 수동 발급 로직을 재활용해보는 건 어떨까요?

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +            return CACHED_LOTTO_NUMBERS[number]
로또 번호를 늘 같은 인스턴스를 활용할 수 있도록 잘 캐싱해주셨네요 👍👍

늘 같은 인스턴스가 실제로 반환되고 있는지 테스트 코드로 검증해보는 건 어떨까요?

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/model/PurchaseAmount.kt
> +        }
생성자를 사용하는 것과 팩토리 메서드를 사용하는 것 두 가지 모두 구현한 이유가 무엇일까요 ?_?
검증 로직도 굉장히 비슷하네요!

2024-02-29 14:45 UTC, malibinYun commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getWinningNumbers(): Set<Int> {
요기에서 타입 반환을 LottoNumber -> Int로 바꾸게 된 생각의 변화가 궁금해요! 🙂

2024-02-29 14:45 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto.of(1, 2, 3, 4, 5, 6, 7) }
어떤 에러 메시지가 발생했는지도 검증해보는 건 어떨까요?

2024-02-29 14:45 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoTest.kt
>          assertTrue(result)
아래 코드와 어떤 차이점이 생겨날까요 ?_?
```suggestion
        val result = lotto.hasMatchingBonusNumbers(LottoNumber.valueOf(bonusNumber))
        assertThat(result).isTrue()
```

2024-02-29 14:45 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoMachineTest.kt
>          }
이 테스트의 이름에 대해 더 고민해보는 건 어떨까요?
정말 테스트 이름만을 검증하고 있는 테스트일까요?

또, foreach 로 검증하기보다, 실제 값 객체를 1대 1로 비교해보는 건 어떨까요?
어떤 차이점이 생길까요 ?_?
테스트 코드를 머릿속에서 한 번 연산하는 것과 가독성에 대해 연관지어서 고민해보세요!

2024-03-01 06:00 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/Lotto.kt
> +    fun hasMatchingBonusNumbers(bonusNumber: LottoNumber): Boolean = numbers.contains(bonusNumber)
1단계 피드백 내용에 포함되어서 변경하기는 했지만
조금 찾아보니 `contains`가 **특정 요소의 존재 여부를 파악**한다는 의미가 명시적으로 드러나서 이지 않을까,,,, 라는 생각이 들었습니다!

2024-03-01 06:10 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +            return CACHED_LOTTO_NUMBERS[number]
넵! 그런 부분도 테스트를 진행해볼 생각은 못했었네요,,ㅎㅎ

2024-03-01 06:24 UTC, JoYehyun99 commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getWinningNumbers(): Set<Int> {
음 코드를 작성하면서 `데이터 변환`을 어디에서 하는 것이 좋을까에 대한 고민을 계속 하고 있었는데,
이번에 예외 처리에 대해 고민하면서 `InputView`에서 너무 많은 일을 하게 되는 것이 아닐까? 라는 의문이 들었습니다. 
굳이 `InputView`에서 어떤 domain으로 변환하는지 알아야 할까? 라는 생각도 들었어서  
변환하는 과정을 컨트롤러로 옮겨버렸습니다 ,,!

2024-03-01 06:43 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/PurchaseAmount.kt
> +        }
이번 미션을 진행하면서 
> 논리적인 오류일 때만 예외를 던진다.
> 논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.

해당 부분에 대한 의문이 많았었고, [해당 글](https://medium.com/@galcyurio/kotlin%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EB%B2%95-48a5cd94a4e6)을 많이 참조하게 되었는데요, exception을 throw 하는 대신 유효하지 않은 값이라면 `Null`을 반환하기 위해 팩토리 메서드로 구현했습니다! 이렇게 구현하는게 괜찮은 방법일까요,,,?

생성자를 따로 private으로 막아두지 않았던 이유는,,, 팩토리 함수 부분을 나중에 추가하면서 생성자 부분을 막아 놓는 것을 까먹었습니다 ,,,, 🥹

2024-03-01 06:49 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoTest.kt
>          assertTrue(result)
`assertThat(result).isTrue()` 
훨씬 가독성이 좋은 것 같습니다! 😄

2024-03-01 06:56 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/Lotto.kt
> +        fun of(vararg numbers: Int): Lotto = Lotto(numbers.map { LottoNumber.valueOf(it) }.filterNotNull().toSet())
헉 굳이 팩토리 함수를 사용하지 않고 부 생성자를 사용해도 되겠네요,,,! 
이 부분에서는 딱히 팩토리 함수의 이점이 보이는 것 같지는 않아서 오히려 부 생성자를 사용하는 것이 나을것같습니다,, 수정하겠습니당~

2024-03-01 07:05 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto.of(1, 2, 3, 4, 5, 6, 7) }
그렇다면 에러 메세지도 상수화를 해서 처리해야 하는 건가요?
사실 에러 메세지 내용까지 테스트 하는 이유가 와닿지 않는데 설명해주실 수있나요? 🥹🥹

2024-03-01 07:29 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoMachineTest.kt
>          }
제가 질문을 맞게 이해한 건지는 모르겠지만 ,,, 일단 수정해보겠습니다!

2024-03-01 07:31 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoMachineTest.kt
>          }
실제 값 객체를 1대 1로 비교한다면, `actual`이 어떤 값을 가져야 하는지 `expected`로 명확히 보여지기 때문에 가독성이 더 좋을 것 같습니다 😃

2024-03-01 08:48 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +    fun hasMatchingBonusNumbers(bonusNumber: LottoNumber): Boolean = numbers.contains(bonusNumber)
이 부분을 피드백 드린 건 아니었어요!

operator fun contains() 에 대해 알아보시고, in 과 어떤 연관관계를 가지고 있는지 찾아보시면 좋겠네요! 🙂

2024-03-01 08:50 UTC, malibinYun commented on src/main/kotlin/lotto/model/PurchaseAmount.kt
> +        }
음~ PurchaseAmount를 생성할 때 Exception이 발생하는 건 논리적인 오류인지 아닌지 먼저 고민해보세요!

글에서 팩터리 메서드를 활용한 경우는,
> 논리 오류일 때 던진 예외는 어떻게 처리하나요?

에 대한 해결책으로 보이네요!

2024-03-01 08:52 UTC, malibinYun commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun getWinningNumbers(): Set<Int> {
그렇게 생각해볼 수도 있겠네요! 👍

2024-03-01 08:53 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoTest.kt
>          assertTrue(result)
result가 `non-null` -> `nullable` 이 되는 변화점에서도 더 생각해보세요!

2024-03-01 08:55 UTC, malibinYun commented
> 어떤 입력 값이 들어와서 발생한 예외인지 메시지에 담아보는 건 어떨까요?
어떤 장점이 생길까요?

require 등의 검증 로직으로 Exception이 발생할 때, 어떤 이유에서 발생했는지 문자열로 메시지를 표현해주셨지요!
이 메시지에 어떤 값이 들어와서 이 Excpetion이 발생했는지 메시지에 담아보시라는 의미었어요 :)

2024-03-01 11:07 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/Lotto.kt
> +    fun hasMatchingBonusNumbers(bonusNumber: LottoNumber): Boolean = numbers.contains(bonusNumber)
아하!! 새롭게 알게된 부분이네용,,,,
그러면 굳이 `hasMatchingBonusNumbers` 라는 메서드를 만들지 말고, 로또 클래스 내에서 `operator fun contains()`를 정의해서 나중에 로또 결과를 생성하는 로직에서 `in`을 사용하는 방법을 제안해주신게 맞나요?

2024-03-02 03:54 UTC, malibinYun requested changes
피드백 반영 고생 많으셨어요!
생각해보면 좋을 곳들에 여러 코멘트 남겨두었으니, 확인해주세요!
피드백 반영 후 다시 리뷰요청 부탁드려요~

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return LottoMachine.issueTickets(LottoNumbersGenerator.generateNumbers(numberOfAutoTickets))
로또를 생성하는 역할을 객체로 묶어봐도 좋겠어요!

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +    fun hasMatchingBonusNumbers(bonusNumber: LottoNumber): Boolean = numbers.contains(bonusNumber)
그렇게 적용해볼수 있겠네요! 👍

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
>          require(numbers.size == NUMBER_COUNT) { "로또 번호는 중복되지 않는 6개의 수로 구성되어야 합니다." }
에러 메시지에 어떤 입력 값이 들어왔는지 같이 표시해보는 건 어떨까요?
어떤 장점이 생길 수 있을까요?

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
> +
마지막 중괄호는 빼도 된답니다 :)
```suggestion
    constructor(vararg numbers: Int) : this(numbers.map { LottoNumber.valueOf(it) }.filterNotNull().toSet())
```

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +            return CACHED_LOTTO_NUMBERS[number]
팩토리 메서드에서 검증 로직이 빠져 더이상 사용하지 않게 되었네요!
삭제하면 좋을지, 생성자로 옮기면 좋을지 고민해보시면 좋겠어요 :)

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/model/WinningLotto.kt
generateWinningStatus 함수의 역할을 여러개로 쪼개 볼 수 있어보여요.
하나의 메서드가 하나의 일만 하도록 연습해보세요!

2024-03-02 03:54 UTC, malibinYun commented on src/main/kotlin/lotto/util/LottoNumbersGenerator.kt
> +        }
이 메서드가 반환하는 타입이 `List<Int>` -> `List<Set<Int>>` 이렇게 변경된 이유가 무엇이었나요 ?_?

2024-03-02 03:54 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoNumberTest.kt
> +        assertThat(firstGenerated).isSameAs(secondGenerated)
assert 구문을 나열하는 것과 assertAll 로 감싸는 것은 어떤 차이점이 있을까요?

2024-03-02 03:57 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto.of(1, 2, 3, 4, 5, 6, 7) }
에러를 한 개만 던지는 객체였다면 큰 문제가 없겠지만,
여러 검증 로직이 들어있는 객체라면 어떨까요?

같은 IllegalArgumentException을 발생하지만, 그 타입만 가지고는 정확히 원하는 Exception이 나타났는지 검증했다고 하기엔 어려워보여요.

에러메시지 테스트에 상수를 사용했을 떄와, 하드코딩 했을때는 어떤 차이점이 있을까요?

2024-03-02 14:04 UTC, JoYehyun99 commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        return LottoMachine.issueTickets(LottoNumbersGenerator.generateNumbers(numberOfAutoTickets))
해당 부분을 `LottoMachine`에서 하도록 옮기겠습니다~

2024-03-02 14:12 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoNumberTest.kt
> +        assertThat(firstGenerated).isSameAs(secondGenerated)
`assert`문이 여러개 일 경우에 앞에 위치한 검증에 실패하면 이후 `assert`들을 실행할 수 없군요,,🫢
`assertAll`을 사용해서 모든 `assert`들을 검증하고 확인해볼 수 있도록 해보겠습니다!

2024-03-02 15:21 UTC, JoYehyun99 commented on src/main/kotlin/lotto/util/LottoNumbersGenerator.kt
> +        }
자동 생성 되는 로또 개수 만큼 `set<Int>`을 생성하여 리스트로 반환하는 것으로 생각했었는데, 굳이 복잡하게 이중 컬렉션으로 반환하지 않아도 될 것 같습니다! 수정하겠습니다!!

2024-03-02 16:07 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoTest.kt
>          assertTrue(result)
`!!` 사용하는 게 조금 찜찜했었는데, 
`contains` 의 인자로 nullable 값도 들어갈 수 있다는 걸 알게되었네욤..!

2024-03-02 16:15 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/Lotto.kt
>          require(numbers.size == NUMBER_COUNT) { "로또 번호는 중복되지 않는 6개의 수로 구성되어야 합니다." }
에러 원인을 조금 더 명확하게 파악할 수 있을 것 같습니다,,,!

2024-03-02 16:19 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/LottoNumber.kt
> +            return CACHED_LOTTO_NUMBERS[number]
로또 프로그램 도메인의 중요한 로직이라고 생각해서 init 블록으로 옮기겠습니다!

2024-03-02 16:24 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/WinningLotto.kt
`WinningRank` 를 생성해주는 부분을 분리해보겠습니다!

2024-03-02 16:46 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/PurchaseAmount.kt
> +        }
구입 금액에 대한 Exception은 논리적인 오류라고 생각해서 팩토리 메서드 대신 생성자를 사용하여 예외를 던지겠습니다!

2024-03-02 17:17 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto.of(1, 2, 3, 4, 5, 6, 7) }
흠 미션을 진행하면서 개인적으로 에러 메세지 상수화 반대파였는데

2024-03-02 17:32 UTC, JoYehyun99 commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto.of(1, 2, 3, 4, 5, 6, 7) }
앗 그런데 현재 로또 클래스에서 리스트가 아닌 `set`으로 설정했기 때문에 사용자가 중복된 숫자를 넣은 건지, 숫자 6개를 넣지 않은 것인지 파악할 방법이 없어보입니다,,,! 이런 경우에는 어떤 식으로 에러를 구분해야하나요,,,? 
리스트 형식으로 인자를 받아서 set 형식으로 변환한 값을 프로퍼티로 갖게 변경하는 방법을 생각해보긴 했습니다,,!

2024-03-03 13:41 UTC, malibinYun requested changes
피드백 반영하시느라 고생 많으셨어요!
이제 크게 피드백 드릴 부분이 없을 정도로 많이 다듬어졌네요 👍
여러 시도해보고 싶은 게 있으시다면 반영 후 리뷰 요청 부탁드려요.
마무리 짓고 싶으시다면 코멘트나 DM 남겨주세요! 질문도 언제나 환영입니다 🙂

2024-03-03 13:41 UTC, malibinYun commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        val winningNumbers = InputView.getWinningNumbers().mapNotNull { LottoNumber.valueOf(it) }.toSet()
메서드 체이닝은 한 줄에 하나씩 해보는 건 어떨까요?
어떤 차이점이 생길까요 ?_?

<details>
<summary> 힌트 </summary>

Exception이 발생했을 때와 연결지어서 고민해보세요!

</details>

2024-03-03 13:41 UTC, malibinYun commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
numbers.toString() 했을 때와 어떤 점이 다를까요?
numbers.toString()은 왜 원하는 형태로 문자열을 출력해줄까요 ?_?

2024-03-03 13:41 UTC, malibinYun commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +    }
여기에도 예외 메시지에 입력 값을 표시해주는 건 어떨까요?

2024-03-03 13:41 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoMachineTest.kt
> +        )
수동과 자동 모두에 대한 테스트 코드이니, 수동도 합쳐서 값을 1대 1로 비교해보는건 어떨까요?

2024-03-03 13:41 UTC, malibinYun commented on src/test/kotlin/lotto/model/LottoTest.kt
> +        assertThrows<IllegalArgumentException> { Lotto(1, 2, 3, 4, 5) }
어떤 에러 메시지가 표시되는지도 검증해보는 건 어떨까요?

2024-03-03 14:31 UTC, JoYehyun99 commented on src/main/kotlin/lotto/model/Lotto.kt
>      }
앗 밑부분에 `toString`을 오버라이딩 해놓고 잊고 있었네요,,! 수정하겠습니다!!

2024-03-03 15:19 UTC, JoYehyun99 commented on src/main/kotlin/lotto/controller/LottoGameController.kt
> +        val winningNumbers = InputView.getWinningNumbers().mapNotNull { LottoNumber.valueOf(it) }.toSet()
Exception 발생 시 에러 발생 지점을 찾기 쉬워질 것 같습니다..!

2024-03-05 02:44 UTC, malibinYun approved these changes
로또 미션 완주하시느라 정말 고생 많으셨어요 :)
다음 블랙잭 미션 진행도 화이팅이에요!
미션은 이만 마무리 하도록 할게요!

2024-03-05 02:44 UTC, merged