[로또] 채채 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #97
Opened 2024-02-28 17:46 UTC by chaehyuns

안녕하세요!! step2 미션을 완료하면서 몇가지 궁금했던 점을 또 여쭤보고 싶습니다!
WinningLotto를 생성하여서 winningNumbers와 bonusNumber를 저장하였습니다. 
하지만 객체를 만들고 나니 이 객체는 검증한 하는 역할만 존재하고 다른 역할은 존재하지 않음을 깨달았습니다.
하지만 저의 코드를 처음 읽는 사람의 경우 당첨 로또(혹은 당첨 로또 번호)임을 알려주기 위해 이런 객체로 존재하는 것도 나쁘지 않다고 생각해서 그대로 구현을 진행하였습니다.
이런 경우 리뷰어꼐서 어떻게 생각하시는지 궁금합니다! 🤔💭 감사합니다!!!

2024-02-29 11:54 UTC, chaehyuns commented
## 추가적으로 comment 하고 싶은 내용이 있어서  댓글 남깁니다 😚

### class, object 를 나누는 기준
이전 step1의 미션에서 '해당 LottoNumberGenerator는 object 로 활용이 가능할까요?'
class, object 를 나누는 기준에 대한 질문을 해주셨는데, 
먼저 LottoNumberGenerator는 Test코드에서 TestNumberGenerator을 만들어서 랜덤 값을 제어하기 위한 수단으로 
주생성자로 선언해서 관리하고 싶어서 class로 구현하였습니다. 
원래 저의 class와 object의 기준은  상태를 저장하지 않고 단순한 함수 호출로 로직을 수행하는 경우
 object를 사용하는 등 특징을 사용하려 했습니다. 
하지만 저의 기준으로만 결정하기엔 view의 경우 컨트롤러 클래스 외부에서 접근하거나 수정할 수 없도록 제한해 주고 싶은 등 여러가지 특수한 상황이 생기면서 기준이 무너지고 있는 듯한 느낌을 받았습니다.  혹시 리뷰어님께서는 명확한 기준이 있으신지 정말 궁금해졌습니다!

### 구조적인 부분에서 부족한 점이 있는 지 궁금합니다!
가장 근본적으로 이것이 옳은 구조이다. 아니면 옳지 않은 구조이다. 로 이분법적으로 나눌 수 는 없겠지만, 
옆의 다양한 크루들의 구조를 보면서 혹시나 저의 구조에서 부족한 부분이 있는지 궁금해졌습니다. 

###  List<List<String>>을 통해 받아오는 구조의 개선 방법?
이번 step2를 구현하면서 수동 로또 번호를 반복적으로 사용자에게 입력받아야했습니다. 
저는 step1 리뷰를 바탕으로 "," split을 view에서 하는게 맞다는 판단이 완전히 들었습니다!
그렇기에 저는 List<List<String>>을 사용해서 [1,2,3,4,5,6]  ,[1,2,3,4,5,6]  이런식으로 받아올 수 밖에 없는데 
이렇게 input을 받아와도 되는지 아무리 생각해도 더 좋은 방법이 생각나지 않았습니다. 이런 경우 controller나 model이 ","를 알아서 쪼개주는 게 더 효율적일지 아니면 그냥 List<List<String>을 사용해도 될 지 궁금합니다!

### 잡담 또는 고민 상담
요즘 아는 것이 정말 부족하다고 느끼는 하루 하루를 보내고 있습니다! 혹시 리뷰어님께서 추천하시는 공부법이 있는지 아니면 추천하실만한 책이 있는지도 알려주실 수 있으면 혹시 공유가 가능할지 궁금합니다 ☺️

2024-02-29 16:45 UTC, KwonDae requested changes
2단계 미션을 잘 진행해주셨네요 👍 
2단계에서는 각 객체의 역할에 대해 조금 집중적으로 코멘트를 드렸습니다.
코멘트 확인 후 충분히 고민해보시고 다시 요청주세요!
끝까지 화이팅입니다 💪

2024-02-29 16:45 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        return WinningLotto(winningLotto, bonusNumber)
사실 이부분이 아래 코멘트에 이어지는 부분입니다.
WinningLotto에게 필요한 정보를 전달하고 WinningLotto가 스스로 판단하여 당첨번호 갯수, 당첨금, 수익률 같은 정보들을 갖고있다면 return 되는 WinningLotto만을 가지고 활용할 수 있겠네요

2024-02-29 16:45 UTC, KwonDae commented on src/main/kotlin/lotto/model/WinningLotto.kt
> +    }
사실 지금은 검증만 하고 있기에 단순 wrapping class에 불과합니다.
하지만 WinningLotto 에서 과연 할 수 있는게 정말 없을까요? 🧐

2024-02-29 16:45 UTC, KwonDae commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    }
> List<List>을 통해 받아오는 구조의 개선 방법?
> 이번 step2를 구현하면서 수동 로또 번호를 반복적으로 사용자에게 입력받아야했습니다.
> 저는 step1 리뷰를 바탕으로 "," split을 view에서 하는게 맞다는 판단이 완전히 들었습니다!
> 그렇기에 저는 List<List>을 사용해서 [1,2,3,4,5,6] ,[1,2,3,4,5,6] 이런식으로 받아올 수 밖에 없는데
> 이렇게 input을 받아와도 되는지 아무리 생각해도 더 좋은 방법이 생각나지 않았습니다. 이런 경우 controller나 model이 ","를 알아서 쪼개주는 게 더 효율적일지 아니면 그냥 List<List을 사용해도 될 지 궁금합니다!

재미있는 리펙토링 주제네요.
List<List<String>>을 보면 동료 개발자가 처음 이 코드를 보았을 때 이해하기 쉬울까요?
또한, LottoStore에서 Collection을 정제하는게 좋은걸까요?

InputView로 부터 입력받을 때 지금 채채가 만들어놓은 Lotto를 활용하여, List<Lotto>를 받도록 하는건 어떨까요?

2024-02-29 16:45 UTC, KwonDae commented on src/main/kotlin/lotto/model/Lottos.kt
>              }.mapValues { (_, value) -> value.size }
WinningLotto에 대한 코멘트를 드렸던 것 처럼
`fun winningResult` 함수도 WinningLotto 에서 수행할 수 있을까요?
그럼 Lottos의 클래스가 필요할까요?
사용자가 발행한 로또에 대한 정보(List<Lotto>), 구매금액 같은 여러 곳에서 사용할 공통 도메인 모델을 의미있게 만들어보는건 어떨까요?

_hint. 현실에서도 로또 티켓 한장 안에 어떤 정보들이 담겨있을까요?_

2024-02-29 16:45 UTC, KwonDae commented on src/main/kotlin/lotto/model/LottoNumberGenerator.kt
>  class LottoNumberGenerator : NumberGenerator {
> class, object 를 나누는 기준
> 이전 step1의 미션에서 '해당 LottoNumberGenerator는 object 로 활용이 가능할까요?'
> class, object 를 나누는 기준에 대한 질문을 해주셨는데,
> 먼저 LottoNumberGenerator는 Test코드에서 TestNumberGenerator을 만들어서 랜덤 값을 제어하기 위한 수단으로
> 주생성자로 선언해서 관리하고 싶어서 class로 구현하였습니다.
> 원래 저의 class와 object의 기준은 상태를 저장하지 않고 단순한 함수 호출로 로직을 수행하는 경우
> object를 사용하는 등 특징을 사용하려 했습니다.
> 하지만 저의 기준으로만 결정하기엔 view의 경우 컨트롤러 클래스 외부에서 접근하거나 수정할 수 없도록 제한해 주고 싶은 등 여러가지 특수한 상황이 생기면서 기준이 무너지고 있는 듯한 느낌을 받았습니다. 혹시 리뷰어님께서는 명확한 기준이 있으신지 정말 궁금해졌습니다!

class 와 object 차이는 
인스턴스화를 통해 객체를 생성, Singleton instance 로 생성하는 관점에서 있습니다.
인스턴스화를 통한 객체를 생성하게 되면 생성하는 객체마다 다른 state 를 갖게 됩니다.
현재는 LottoNumberGenerator는 인스턴스화를 통한 각 객체마다의 state가 다를까요?

구조를 보면 fun generate를 통해 제어하고 있습니다.
아래 글을 한번 참고해보시죠!
https://www.baeldung.com/kotlin/object-vs-data-class

2024-02-29 16:56 UTC, KwonDae commented
> 구조적인 부분에서 부족한 점이 있는 지 궁금합니다!
> 가장 근본적으로 이것이 옳은 구조이다. 아니면 옳지 않은 구조이다. 로 이분법적으로 나눌 수 는 없겠지만,
> 옆의 다양한 크루들의 구조를 보면서 혹시나 저의 구조에서 부족한 부분이 있는지 궁금해졌습니다.

말씀하신대로 옳고 그른건 없습니다. 단지 채채 스스로가 명확한 기준을 갖고 시도를 해보는게 중요합니다. 물론 옆 크루의 구조를 참고를 할 순 있겠지만, 그것이 본인의 구조보다 낫다 아니다를 판단하는건 의미가 없다고 생각합니다.
참고할 때는 '아! 저런 구조로 설계를 할 수 있겠구나, 어떤 장점이 있을까?, 해당 구조의 장점을 내 설계도에 접목시킬 수 있을까?' 정도로 생각이 나아갔으면 합니다. 
그런 관점에서 `객체들에게 조금 더 할일을 명확하게 구분 짓고 부여`하면 보다 좋은 구조가 될 것이라 생각하여 코멘트를 드렸으니 참고해주세요 :) 

> 잡담 또는 고민 상담
> 요즘 아는 것이 정말 부족하다고 느끼는 하루 하루를 보내고 있습니다! 혹시 리뷰어님께서 추천하시는 공부법이 있는지 아니면 추천하고 싶은 책이 있는 지도 혹시 공유가 가능다면 알려주실 수 있는지궁금합니다 ☺️

저 또한 하루 하루를 부족한게 많음을 느끼며 살아가고 있습니다 ㅎㅎ 
저는 주로 공식문서와 이미 우리가 사용하는 기본 라이브러리(androidx, kotlin.collection)의 함수 내부 구현이 어떻게 되어있는지를 참고하는것이 많은 도움이 되었습니다. 흔히 사용하는 take, groupBy 같은 함수들이 어떻게 동작하는지에 의문을 갖고 살펴보다보면 그들이 왜 그렇게 구현했는지 의문을 갖다보면 그것들이 내 지식으로 쌓이게 될 수 있겠죠
지금 단계에서 일급 컬렉션, 객체, 인터페이스 같은 기본 뼈대를 구성하는 것들에 대해 알아가는데 `객체지향의 사실과 오해` 도 도움이 많이 될거라 생각합니다 👍

2024-03-03 00:21 UTC, chaehyuns commented on src/main/kotlin/lotto/controller/LottoController.kt
> +    }
profitRate를 계산하는 과정에서 Controller 입장에서 생각하는 부분을 놓치고 있다는 것을 깨달았습니다. 수정하겠습니다!

2024-03-03 00:25 UTC, chaehyuns commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        return WinningLotto(winningLotto, bonusNumber)
확실히 Lottos보다는 WinningLotto가 당첨번호 갯수를 가지고 있는 것이 맞다고 생각이 들었습니다! 다만 제 생각으로는 LottoStore가 당첨금, 수익률을 계산하는 것이 조금 더 현실 세계와 비슷하다고 생각하여 구현하였는데, LottoStore에 대한 책임이 너무 과해진 것인지 아니면 괜찮은지에 대한 궁금증이 들게 되었습니다! 🤔

2024-03-03 00:29 UTC, chaehyuns commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    }
고민을 하다가 다시 view에서 List<String>을 받아 controller에서 repeat을 하였습니다.  로또를 발행하는 책임이 있는 LottoStore애 Lotto.lottoNumbersOf(manualLottoNumbers) 로 List<String> 을 바로 Lotto로 발행 하였는데, 맞게 이해한 것인지 궁금합니다! 🤔

2024-03-03 00:58 UTC, KwonDae commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    }
InputView에서 `Set<Lotto>` 로 Controller에게 반환해주는건 어떻게 생각하시나요?
InputView에서 넘겨주는 Lotto 원소는 말그대로 Lotto 원소이고, 아직 발행된 로또티켓은 아니라고 생각이 들어요.
Controller에게 `Set<Lotto>`를 넘겨주고, 그 다음에 남은 금액이 있다면 로또 발행 책임이 있는 객체에서 자동로또를 추가해서 `발행`한다.


```
// in InputView.kt
fun readManualLottoNumbers(manualLottoCount: Int): Set<Lotto> {
        val manualLotto = mutableSetOf<Lotto>()
        repeat(manualLottoCount) {
            val lottoNumbers =
                validateNullInput(readlnOrNull()).replace(" ", "").split(SPLIT_DELIMITER).map(String::trim)
            manualLotto.add(Lotto.lottoNumbersOf(lottoNumbers))
        }
        return manualLotto.toSet()
    }
```

2024-03-03 01:15 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        return WinningLotto(winningLotto, bonusNumber)
LottoStore의 역할에 대해서 생각해볼 필요가 있을 것 같아요.
LottoStore 인스턴스가 생성될 때 마다 각 인스턴스는 다른 당첨금, 수익률을 갖게 될까요? 🧐
LottoStore는 로또 발행 외에 어디까지 책임을 갖게 하면 좋을까요?
이부분에 대해 고민해보시고 채채의 의견을 공유해주세요 🙂

2024-03-03 01:16 UTC, chaehyuns commented on src/main/kotlin/lotto/model/Lottos.kt
>              }.mapValues { (_, value) -> value.size }
이번 제출(step2 두번째 pr)을 돌아보면 여러곳에서 사용할 공통 도메인에 대한 점을 크게 개선하여 해결하지 못한것 같습니다. 
LottoTicket을 만든다면 Lotto의 정보, 로또 티켓 가격 이런 정보들이 들어가게 되는 건지 감이 안잡혀서 다시 질문 드립니다 🥹

2024-03-03 01:18 UTC, chaehyuns commented on src/main/kotlin/lotto/model/LottoNumberGenerator.kt
>  class LottoNumberGenerator : NumberGenerator {
좋은 글 추천해주셔서 감사드립니다!! state를 가지지 않으면서 class로 둔다는 점이 마음에 들지 않았었는데, 그 부분을 해결할 수 있었던 거 같습니다!!

2024-03-03 16:06 UTC, chaehyuns commented on src/main/kotlin/lotto/model/LottoStore.kt
> +    }
아 View가 Model을 아는 것을 최대한 막아야한다는 관점에서 생각하다보니 List<Lotto>로 발행할 생각은 못했던거 같습니다! 
`InputView에서 넘겨주는 Lotto 원소는 말그대로 Lotto 원소이고, 아직 발행된 로또티켓은 아니라고 생각이 들어요.` 라는 리뷰를 보고 나니 오히려 유연성을 높여줄 수 있는 방안이라는 생각이 드네요! 감사합니다!

2024-03-03 16:45 UTC, chaehyuns commented
### Step2 리뷰 바탕으로 수정 사항

* Lottos class 삭제
* WinningLottoCalculator로 당첨 계산 로직 관심 모으기
* List<List<String>> 구조 변경

이번 리뷰를 통해 수정을 하며 객체에 대한 고민에 혼란에 빠져있는 와중에 빠르게 DM으로 응답해주셔서 정말 감사했습니다! 
제이든이 알려주신 팁인 A4를 한장 펼쳐놓고 Flow chart를 만드는 방식으로 어떤 객체가 현재 어떤 일을 하고 있는지 전반적인 설계를 볼 수 있었습니다! 
그덕에 객체들에게 조금 더 할일을 명확하게 구분 짓고 부여하려고 고민해보는 시간을 많이 가지려고 노력했는데, 제가 리뷰를 잘 이해한건지 궁금해지네요! 🤓 

추가적으로 이번 미션에서도 groupBy를 쓰면서도 구현을 위한 수단으로 쓰는 것이 아니라  어떻게 동작하는 지에 대한 의문을 가지고 참고하면 더 이해도가 높아졌을 텐데라는 깨달음을 얻게 되었습니다! 차근차근 기초부터 쌓아나가는 것이 역시 중요하군요! 
그리고 `객체지향의 사실과 오해` 스터디를 이제 곧 진행할 예정이라 굉장히 반갑게 느껴졌습니다 ☺️
따스한 조언과 리뷰를 진행하면서 도움이 될만한 글을 추천해주신 점에서 정말 감사드립니다 🙇🏻‍♀️ 
한층 더 성장하는 시간을 가질 수 있었습니다!  💪🏻

2024-03-04 09:10 UTC, KwonDae requested changes
많은 피드백을 드렸음에도 불구하고 전반적으로 잘 반영해주셨네요 👍 
점점 코드가 발전해 나가는 모습이 보여 다행입니다 🙂
로또 미션을 마무리 하기 전 꼭 짚고 넘어갔으면 하는 부분에 대해 코멘트를 남겨드렸습니다.
다음 요청으로 미션 마무리 지을 예정이니 한번 고민해보시고 리뷰 요청 부탁드릴게요
문의사항은 DM으로 편하게 주세요!
끝까지 화이팅입니다 💪

2024-03-04 09:10 UTC, KwonDae commented on src/main/kotlin/lotto/view/InputView.kt
> +        val manualLotto = mutableListOf<Lotto>()
👍

2024-03-05 13:27 UTC, chaehyuns commented on src/main/kotlin/lotto/controller/LottoController.kt
>      private fun initPurchaseAmount(): PurchaseAmount {
논리적인 오류, 그리고 논리적이지 않은 오류일 경우를 나누어서 생각을 하다보니까 코드가 굉장히 복잡해져서, 
지난주의 당첨 번호를 제외하고는 runCatching을 사용해서 입력을 다시 받아오도록 구현했습니다! 
하지만 제가 올바르게 이해한지 모르겠어서 일단 먼저 push를 하고 리뷰를 받아보자는 결론에 이르게 되었습니다 🥹
혹시 말씀해주신 의도대로 제가 코드를 작성한 것인지 궁금합니다!

2024-03-05 15:12 UTC, KwonDae approved these changes
마지막까지 피드백 반영해주시느라 정말 고생많으셨습니다.
리펙토링 과정에서 여러 방법들을 시도하는 커밋들을 통해 더욱 성장하는 시간들이었음을 알 수 있었습니다.
로또에서의 노력들이 다음 미션에서 도움이 되기를 바라며
로또미션은 여기서 마무리 하겠습니다.
남겨드린 피드백은 꼭 한번 천천히 읽어봐주시길 바랄게요.
다음 미션도 화이팅입니다 💪

2024-03-05 15:12 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LottoController.kt
> +        }
제가 함께 논의하고 싶은 것이 이런 부분이었습니다.
`단순 예외를 던지는 것과 null 을 반환하는 것이 어떤 차이`가 있는지 알아보았으면 하는 생각이었습니다.
물론 500원을 입력받는다 해서 구현에 따라 프로그램이 비정상으로 동작하지 않도록 `require()` 를 활용해 예외를 던져서 논리 오류를 막고 있었습니다.

그렇다면 논리 오류를 막고 있었기에, 여기서 발생하는 예외처리를 할 수 있는 방법에 대해서 생각해보면
1. 미션에서 제시한 것 처럼 null 을 반환하여 잘못된 값이 전달됐다고 프로그램 내에서 "룰"을 만들 수 있다.
2. 다시 입력값을 받도록 처리한다.

null을 return 할 경우 controller 에서 돌아오는 null에 대한 처리를 해야 합니다. 지금 수정해주신 방법처럼요.
단순 예외를 던지는 것 외에도 null을 반환하여 controller에서 처리가 가능하다는 것을 알게되었네요 :) 

이것은 예외가 발생했을 때의 처리 제어권을 어디로 위임할거냐로 볼 수 있습니다.
예외상황이 발생했을 때 [여기](https://github.com/woowacourse/kotlin-lotto/pull/97/commits/a60b9c689ba9990d332df65906eb9a8686b5a6f9#diff-121f6f3168811736cb71a571efd1b26320000d1e4ebf3dc8081b168b69678fd9R14-R21) 처럼 다시 해당 함수를 호출하는 상황에서는 Controller가 개입을 할 수 없습니다.
만약 추가적인 대응 로직이 필요하다면 view에서 비즈니스 로직을 처리해 결국 MVC 구조로 분리한 장점이 사라지게 되겠죠.

왜 코틀린에서 예외가 발생할 경우 null을 반환하는 방식을 사용하고 있는지 한번 생각해보셔도 도움이 될 것 같습니다.
결론은 예외 처리에 대해 정답은 없습니다. 위에서 말했듯이 프로그램 내에서 Null을 반환해도, 예외를 던져 처리하든 정답은 없지만 다양한 경험을 통해 해당 방법들의 차이점을 알고 어떤 방식이 나에게 맞는 스타일인지 이후 미션에서도 찾아갔으면 좋겠습니다.

[참고글1](https://elizarov.medium.com/kotlin-and-exceptions-8062f589d07)
[참고글2](https://kotlinlang.org/docs/exceptions.html)

2024-03-05 15:16 UTC, KwonDae commented on src/test/kotlin/lotto/LottoStoreTest.kt
> +            )
참고로 테스트에 Test Fixture 라는 개념이 있습니다.
이는 여러 테스트에서 같은 Data를 사용할 때, 코드 중복을 피하면서 가독성을 높이는 방법인데요
[참고하면 좋은 글](https://tjdtls690.github.io/studycontents/java/2022-10-10-test_fixture/)이 있어 공유드립니다.

2024-03-05 15:17 UTC, merged

2024-03-05 15:18 UTC, KwonDae commented on src/test/kotlin/lotto/LottoStoreTest.kt
> +            )
참고로 테스트에 Test Fixture 라는 개념이 있습니다.
이는 여러 테스트에서 같은 Data를 사용할 때, 코드 중복을 피하면서 가독성을 높이는 방법인데요
[참고하면 좋은 글](https://tjdtls690.github.io/studycontents/java/2022-10-10-test_fixture/)이 있어 공유드립니다.

2024-03-06 02:04 UTC, chaehyuns commented
끝까지 참고글이나 성장할 수 있는 많은 방향을 제시해주셔서 감사합니다! 😊 추천해주신 글 모두 꼼꼼히 읽어보겠습니다!