[로또] 해나 2단계 미션 제출합니다.
woowacourse/kotlin-lotto pull request #98
Opened 2024-02-28 18:14 UTC by hxeyexn

안녕하세요 제이든!
1단계에 이어 2단계도 잘 부탁드리겠습니다! 소중한 시간내어 코드 리뷰해주셔서 감사합니다 😊

<br>

## step1 중복 상수에 대한 질문 관련 의견
> 질문 3. 중복 상수
> 필요한 상수들을 각각의 파일 내에서 companion object에 선언하고 있습니다. 각 파일마다 필요한 상수를 정의하는 게 유지보수하기 편하지 않나라는 생각이 들어 각각의 파일에서 관리하도록 했습니다.
> 
> 각각의 파일에서만 사용되는 부분은 각각의 파일에서 관리하고, 공통적으로 쓰이는 상수들은 별도의 상수 파일을 만들어서 관리
> 지금처럼 각각의 파일에서 필요한 상수는 각각의 파일에서 관리

step1에서 위 질문을 드렸었고, 제이든이 아래와 같은 답변을 해주셨습니다.

> 이건 해나의 의견도 궁금하네요.
> 단지 2번의 경우에는 수정이 필요할 때 모든 곳에서 수정을 요구하겠죠? 실수로라도 바꾸지 않았다면 상이한 결과를 나타낼겁니다.

그래서 여러가지 경우의 수를 생각해보며 제 생각을 정리해보았습니다. 공통적으로 쓰이는 상수들이라도 하나만 문구가 수정되어야 하는 경우를 대비해 2번이 유지보수하기 더 편하지 않나라는 의견입니다. 분리 해놓은 것을 합치는 것보다 합쳐 놓은 걸 분리하는 게 더 힘들다고(네이밍 등..) 느꼈기 때문입니다. 프로젝트 특성에 따라 상수를 관리하는 규칙을 다르게 적용하는 것도 하나의 방법이라고 생각합니다.

<br>

## 🙋‍♂️ step2를 진행하면서 했던 고민
### 고민 1. 
step1에서 랜덤 로또 테스트와 2단계 기능 확장(수동 로또 발행)을 위해 로또 티켓 전략을 사용했습니다.
- `RandomTicketGenerationStrategy` (랜덤 로또 티켓 발행) 
- `ExplicitTicketGenerationStrategy` (테스트를 위한 명시적 로또 티켓 발행)

step2 초반에는 ManualTicketGenerationStrategy(수동 로또 티켓 발행)만 추가해서 기능을 구현했습니다.  전략을 그대로 사용했더니 TicketGenerationStrategy가 Ticket을 반환하는 것이 아니라 Lottery를 반환해 티켓의 역할이 모호해졌고, 티켓 전략과 티켓의 역할에 대한 의문이 들었습니다.

굳이 전략이 필요한가? 라는 생각도 들어서 랜덤 번호 생성을 제외한 전략을 없애고, 수동 로또 생성, 자동 로또 생성, 로또 티켓 발행 기능을 가진 LotteryMachine이라는 모델을 만들까 고민도 해봤습니다.

결론적으로 수동 로또 기능을 위해 기존 전략을 지우고 새로 클래스를 만들기 보단 확장을 중점에 두자고 기준을 잡았고, 기존 Ticket 전략을 Lotteries 전략으로 바꿨습니다. 더불어 LotteryStore를 LotteryMachine으로 변경하여 LottoMachine의 issueLotteries라는 행위에서 Lotteries 전략(수동/자동)만 바꿔 끼우고 이렇게 발급된 수동/자동 로또를 Machine이 issueTicket이라는 행위를 통해 한 장의 티켓으로 발행해주도록 했습니다.  

위 고민에 대한 제이든의 의견을 듣고 싶습니다!

<br>

### 고민 2. 커밋 단위
수동 로또 생성 기능을 구현하면서 수정할 부분이 많은 데 실행 가능한 단위로 커밋하려다보니, fa046fa 가 너무 많은 변경점을 가지고 있다는 느낌을 받았습니다. 추가 기능을 구현하는 데 변경점이 많다면 제이든은 어떤 기준으로 커밋 단위를 정하시나요?

2024-02-29 17:51 UTC, KwonDae requested changes
1단계에 이어 2단계도 미션을 잘 진행해주셨습니다 👍 
꼭 짚고 넘어갔으면 하는 부분들에 대해 코멘트 달아드렸으니 
충분히 고민해보신 후 다시 요청 부탁드립니다.
끝까지 화이팅 💪

2024-02-29 17:51 UTC, KwonDae commented on src/main/kotlin/controller/LotteryController.kt
> +    }
InputView로부터 `List<Lottery>` 를 전달받는건 어떨까요?
Controller에서 데이터를 정제하는 책임이 있어야 할까요?

2024-02-29 17:51 UTC, KwonDae commented on src/main/kotlin/model/ManualLotteryCount.kt
> +class ManualLotteryCount(val count: Int) {
ManualLotteryCount 역할을 좀 더 의미있게 활용해볼까요?
현재 프로젝트 내에서 ManualLotteryCount 클래스는 구매 정보에 가까운 성격을 띄우고 있네요.
그렇다면 구매정보에 관련된 값들을 하나의 클래스에 모아 책임을 갖도록 하고 응집해보는건 어떨까요?

2024-02-29 17:51 UTC, KwonDae commented on src/main/kotlin/controller/LotteryController.kt
> +    ): Ticket = LotteryMachine.issueTicket(manualLotteries, autoLotteries, amount)
> step2 초반에는 ManualTicketGenerationStrategy(수동 로또 티켓 발행)만 추가해서 기능을 구현했습니다. 전략을 그대로 사용했더니 TicketGenerationStrategy가 Ticket을 반환하는 것이 아니라 Lottery를 반환해 티켓의 역할이 모호해졌고, 티켓 전략과 티켓의 역할에 대한 의문이 들었습니다.
> 
> 굳이 전략이 필요한가? 라는 생각도 들어서 랜덤 번호 생성을 제외한 전략을 없애고, 수동 로또 생성, 자동 로또 생성, 로또 티켓 발행 기능을 가진 LotteryMachine이라는 모델을 만들까 고민도 해봤습니다.

이부분에서 깊게 고민해볼 수 있겠네요.
Controller에서 개별 로또마다 수동, 자동을 뽑아내서 티켓을 발급받도록 하는 과정이 필요할까요?

Controller -> LottoMachine에게 필요한 정보(수동 로또, 구매금액...)를 전달해서 LottoMachine이 알아서 수동, 자동 로또를 발급하고 Ticket을 반환받도록 하는건 어떨까요?
LottoMachine에게 좀 더 주체적인 역할을 부여해볼까요?

2024-02-29 17:51 UTC, KwonDae commented on src/main/kotlin/controller/LotteryController.kt
>          printWinningResult(winningResult)
이 부분에서 동료 개발자가 보게되었을 경우 빠른 시간내 이해하기 어떨까요?
파편화 되어 있는 함수들을 순서대로 보았을 떄 이해하기 쉽도록 해볼 수 있을것 같아요.
ex)
1. 사용자로 부터 입력 받는 함수(구매 정보를 받아오기)
2. 로또 생성 함수(수동, 자동 로또 생성 수행)
3. 당첨 로또 입력 받는 함수
4. 당첨금 계산(로또 비교, 수익률 계산)

식으로 Controller 내부에서도 함수들을 정리해볼 수 있겠네요 👍

2024-02-29 17:56 UTC, KwonDae commented
> 그래서 여러가지 경우의 수를 생각해보며 제 생각을 정리해보았습니다. 공통적으로 쓰이는 상수들이라도 하나만 문구가 수정되어야 하는 경우를 대비해 2번이 유지보수하기 더 편하지 않나라는 의견입니다. 분리 해놓은 것을 합치는 것보다 합쳐 놓은 걸 분리하는 게 더 힘들다고(네이밍 등..) 느꼈기 때문입니다. 프로젝트 특성에 따라 상수를 관리하는 규칙을 다르게 적용하는 것도 하나의 방법이라고 생각합니다.

좋습니다. 본인의 명확한 기준을 갖고 여러 경험을 통해 장단점을 파악하는게 해나 스스로에게 많은 도움이 될거에요. 여러 미션을 통해 여러 방법을 경험하시는걸 추천드립니다 👍 

> 고민 2. 커밋 단위
> 수동 로또 생성 기능을 구현하면서 수정할 부분이 많은 데 실행 가능한 단위로 커밋하려다보니, https://github.com/woowacourse/kotlin-lotto/commit/fa046faf3c232bc24a0e6565e7bebbf5b4ec682f 가 너무 많은 변경점을 가지고 있다는 느낌을 받았습니다. 추가 기능을 구현하는 데 변경점이 많다면 제이든은 어떤 기준으로 커밋 단위를 정하시나요?

커밋 단위는 기능 단위가 되어야 하며 해당 기능 빌드가 잘 되어야 합니다. 단지 해당 커밋의 경우엔 패턴을 수정하다보니 변경점이 많은거로 생각되는데요, 그만큼 아키텍처의 중요성에 대해서 한번 느낄 수 있었던거 같습니다. 자동, 수동 외에 또다른 로또 발급 형태가 추가될 때 Generator에 따라서 도메인 로직이 어느정도 수정되어야 하는지 살펴보면서, 현재 도메인 로직이 유연하게 대응할 수 있는가? 에 대해 한번 고민해봐도 좋을 것 같습니다 💯

2024-03-02 13:07 UTC, hxeyexn commented on src/main/kotlin/model/ManualLotteryCount.kt
> +class ManualLotteryCount(val count: Int) {
미션이 진행될수록 객체를 어느 정도까지 나눠야하나?라는 의문이 들었는 데, 초반 설계 과정에서 최대한 나눠보고 관련된 값들끼리 응집하면 객체들이 유의미한 역할과 책임을 적절히 가질 수 있겠다는 생각이 드네요! 제이든 덕분에 객체를 나누는 기준에 대해 한 번 더 짚고 넘어가는 계기가 되었습니다. 감사합니다!

2024-03-02 13:08 UTC, hxeyexn commented on src/main/kotlin/controller/LotteryController.kt
>          printWinningResult(winningResult)
동료 개발자가 처음 제 코드를 접한다면 확실히 빠른 시간 내 이해하기가 어렵겠네요..! 😭  제가 동료 개발자 입장이라면 가장 먼저 controller의 start 메서드를 살펴볼 것 같은데, 미션을 진행하면서 해당 부분은 너무 신경을 쓰지 않았던 것 같습니다. 처음 이 코드를 볼 동료 개발자의 관점에서 생각해 좀 더 가독성 있는 코드를 작성하도록 유념해야겠네요..!

2024-03-02 14:10 UTC, hxeyexn commented
@KwonDae 

피드백 반영과 더불어 예외 처리에 대한 권장 사항을 적용해 보고 있습니다. 여러 자료를 참고하다 보니 혼란이 생겨 질문드립니다!

> - 논리적인 오류일 때만 예외를 던진다.
> - 논리적인 오류가 아니면 예외를 던지지 말고 null을 반환한다.

Step2에 위와 같은 권장사항이 있었습니다. 아토믹 코틀린과 여러 자료를 보면서 논리 오류에 대한 생각을 아래와 같이 정리했습니다. 제가 이해한 바가 맞을까요?

> - 논리 오류일 때  : 로또 번호가 1~45 범위 내의 숫자가 아닌 다른 숫자(ex. 100)일 때 exception을 던짐
> - 논리 오류가 아닐 때 : 숫자가 아닌 문자(ex. a)일 때는 null을 반환

논리적인 오류에 대한 제이든의 생각도 듣고 싶습니다!

2024-03-03 09:07 UTC, KwonDae commented
> 논리 오류일 때 : 로또 번호가 1~45 범위 내의 숫자가 아닌 다른 숫자(ex. 100)일 때 exception을 던짐
> 논리 오류가 아닐 때 : 숫자가 아닌 문자(ex. a)일 때는 null을 반환

정리해주신 내용이 맞습니다!
일단 [논리 오류](https://ko.wikipedia.org/wiki/%EB%85%BC%EB%A6%AC_%EC%98%A4%EB%A5%98) 에 대한 정의는 이렇습니다.
`프로그램이 부정확하게 동작하게 하지만 비정상적으로 종료 또는 충돌 시키지는 않는 버그`
해당 힌트에 대해서 [도움 될만한 글](https://medium.com/@galcyurio/kotlin%EC%97%90%EC%84%9C%EC%9D%98-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC-%EB%B0%A9%EB%B2%95-48a5cd94a4e6)을 가져왔는데요, 읽어보시고 고민 후 저에게도 공유해주세요 🙂

2024-03-03 14:29 UTC, hxeyexn commented on src/main/kotlin/controller/LotteryController.kt
> +    ): Ticket = LotteryMachine.issueTicket(manualLotteries, autoLotteries, amount)
Controller에서 LottoMachine으로 수동 로또와 구매 정보, 랜덤 로또 전략만을 전달해 LottoMachine이 수동, 자동 로또 발급 및 Ticket을 반환하도록 수정했습니다! [2cdb456](https://github.com/woowacourse/kotlin-lotto/pull/98/commits/2cdb456809fb30741457c5eb8ada67c48e829343)

2024-03-03 14:36 UTC, hxeyexn commented on src/main/kotlin/controller/LotteryController.kt
>          printWinningResult(winningResult)
start 메서드 내부를 함수로 파편화하여 정리했습니다! [d50e65c](https://github.com/woowacourse/kotlin-lotto/pull/98/commits/d50e65cd9aef02cae81ce5ef470d4d3913cfa6fd)

2024-03-03 14:44 UTC, hxeyexn commented on src/main/kotlin/model/ManualLotteryCount.kt
> +class ManualLotteryCount(val count: Int) {
data class를 이용해 Amount와 ManualLotteryCount를 구매 정보라는 클래스로 응집해보았습니다. [10845af](https://github.com/woowacourse/kotlin-lotto/pull/98/commits/10845afa3fff0278d37f7bf586f727ee764ab1bc)

2024-03-03 15:32 UTC, hxeyexn commented on src/main/kotlin/controller/LotteryController.kt
> +    }
해당 질문에 대해 생각해보니, Controller에서 데이터를 분할하는 책임은 필요 없다고 판단했습니다. 따라서 InputView에서 분할 후 `List<List<String>>`을 바로 전달받도록 수정하였습니다! [d08fd1d](https://github.com/woowacourse/kotlin-lotto/pull/98/commits/d08fd1ddab106f22338c3ef310e0e7af743ad902) [f54b2cc](https://github.com/woowacourse/kotlin-lotto/pull/98/commits/f54b2cc14b025cda11e6f391d88d65d2dcf194ee)

다만 InputView로부터 `List<Lottery>`를 전달 받아야 하는지에 대해선 의문이 들었습니다. 

현재 `List<Lottery>`를 직접 전달받지 않은 이유는 콘솔 이외의 다른 환경에서 동일한 데이터를 다양한 형태로 활용할 수 있도록, 최소한으로 정제한 데이터를 보다 유연성 있게 사용하기 위함이었습니다. 다른 데이터들도 동일한 이유로 최소한 정제된 데이터를 controller에게 넘겨주고 있습니다. 

또 한편으로 제이든 조언대로 InputView에서 `List<Lottery>`를 직접 받게 되면, 데이터의 무결성이 보장되어 결과적으로 더 안정적인 시스템을 구축할 수 있을 것 같다는 생각이 듭니다.

InputView로부터 얼마나 정제된 데이터를 Controller가 받아야하는 지 확신이 서지 않는 데, 이에 대해 도움 주실 수 있다면 정말 감사하겠습니다..!

2024-03-03 16:36 UTC, hxeyexn commented
피드백 주신 내용들 최대한 반영해보려 시도해봤습니다! LotteryNumber에 대한 논리 오류 처리는 아직 갈피를 못 잡아 Amount와 ManualLotteryNumber에 대한 논리 오류 처리만 진행해보았습니다..! 이에 대해 코멘트 해주시면 감사하겠습니다 🙇 LotteryNumber에 대한 논리 오류 처리는 공유해 주신 글 보며 좀 더 고민해보도록 하겠습니다 ㅠㅠ

2024-03-04 00:44 UTC, KwonDae commented on src/main/kotlin/controller/LotteryController.kt
> +    }
@hxeyexn 
동료 개발자가 유지보수를 맡았을 때, `List<List<String>>` 을 보고 어떤 의미를 갖는 데이터인지 쉽게 알 수 있을까요?
또한, 이중 List로 되어 있기에 보일러 플레이트 코드도 발생하게 됩니다.

InputView 이외에도 `List<Lottery>` 같이 모델 역할을 하는 정보에 접근하는게 아닌, 원시값 `List<List<String>>` 에 접근해야 하는 이유가 있을까요?

2024-03-04 00:57 UTC, KwonDae commented on src/main/kotlin/view/InputView.kt
> +    fun readManualLotteries(manualLotteryCount: ManualLotteryCount): List<List<String>> {
이부분 반환 타입을 보고 어떤 값인지 알기 위해 내부 구현을 모두 봐야 했는데요,
이 코드를 읽는 사람에게 보다 알기 쉽게 하는 방법엔 어떤 방법이 있을까요?

2024-03-04 00:57 UTC, KwonDae commented on src/main/kotlin/model/ManualLotteryCount.kt
> +class ManualLotteryCount(val count: Int) {
관련있는 값들을 모아 의미있는 객체를 활용하니 가독성이 한층 높아졌네요 👍

2024-03-04 05:52 UTC, KwonDae requested changes
피드백 반영해주시느라 고생많으셨습니다.
미션을 마무리하기 전 꼭 짚어보고 넘어갔으면 하는 부분에 대해 코멘트 드렸으니
확인 후 꼭 요청 주세요 👍 
끝까지 화이팅입니다 💪

2024-03-04 05:52 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LotteryController.kt
> +    }
<img width="981" alt="image" src="https://github.com/woowacourse/kotlin-lotto/assets/33443660/2fc8ac62-2123-46be-943e-fde2ebf802c7">

현재는 구입금액이 1000원 미만이면 바로 Exception을 발생시켜 종료시키고 있습니다.

한번 식당의 키오스크를 생각해보면,
기본금액 5000원 이상인 식당에서 우리가 현금을 1000원을 넣는다고 프로그램이 종료될까요?
5000원 이상 투입을 안내문구를 띄운다던가, 무엇이 잘못됐는지를 알려줘 가이드를 할 수 있겠죠.

미션에서 요구하는 논리적인 오류는 사용자가 경험하는 모든 과정에 있어서 Exception을 던져야 하는 상황인지, 혹은 어떠한 오류가 발생했을 때 적절하게 문제를 해결하도록 할 것인지 기대하는 요구사항입니다.

```
// Controller 내에서 처리
private fun readAmount(): Amount {
        return runCatching {
            Amount.fromInput(inputView.readAmount()) ?: readAmount()
        }.getOrElse {  throwable ->
            outputView.printError(throwable.message ?: "잘못된 입력")
            readAmount()
        }
    }
```
현재 구조에서는 위와 같이 가능하겠네요!
위 같은 방법 말고도 InputView로 부터 검증된 Amount를 Controller가 전달 받는다면 어떨까요?
Controller에서 `try-catch` or `runCatching` 같은 코드들이 필요없게 할 수 있을까요?

```
// in InputView
    fun readAmount(): Amount? {
        println(HEADER_READ_AMOUNT)
        return runCatching { 
            Amount(readln().toInt())
        }.getOrNull()
    }

    private fun readAmount(): Amount {
        val amount = inputView.readAmount()
        if (amount == null) {
            outputView.printError("잘못된 값 입력")
            return readAmount()
        }
        return amount
    }
```

이렇게 Amount? 를 nullable 하게 활용할 수 있겠네요
해나 스스로 고민해보고 논리 오류가 아닐 때 어떤 방법을 활용하는게 좋을지 고민해보세요!

2024-03-04 05:52 UTC, KwonDae commented on src/main/kotlin/lotto/controller/LotteryController.kt
> +        }
ManualLotteryCount 내부 validatePurchaseBound 의 require로 인해 Exception이 발생하면 어떻게 될까요?
위의 readAmount()와 같이 빈번한 Exception 발생은 프로그램 실행에 좋은 영향을 주지 않습니다.

2024-03-05 13:55 UTC, hxeyexn commented
수동 로또 수가 45 초과일 때 제외하곤 프로그램이 종료되지 않도록 논리 오류와 예외 처리했습니다!
수동 로또 수가 45 초과일 때 재시도 로직을 어디서 수행해야할 지 감을 못 잡아서 해당 부분 제외하고 리뷰 요청 드립니다.. ! ㅠㅠ

2024-03-05 15:00 UTC, hxeyexn commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun readManualLotteries(manualLotteryCount: ManualLotteryCount): List<List<String>> {
논리 오류 처리를 진행하면서 List<List<String>>를 List<List<Int>>를 반환하도록 수정했습니다.
제이든 말씀대로 다른 개발자가 봤을 때 현재 반환 타입을 보고 어떤 값인지 어렵다는 점 이해합니다!
다만 LIst<List<Int>>를 List<Lottery>로 바꾸지 않은 이유는 다음과 같습니다. 현재 로직에서 InputView에서 List<Lottery>를 바로 반환하려고 시도해봤는 데, 그렇게 되면 ManualLotteriesGenerationStrategy가 존재하는 이유가 없어진다는 느낌을 받았습니다. 그래서 List<Lottery>로 반환하지 않았는 데 이에 대한 제이든의 생각을 여쭤봐도 될까요? 🥲

2024-03-05 15:34 UTC, KwonDae commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun readManualLotteries(manualLotteryCount: ManualLotteryCount): List<List<String>> {
`ManualLotteriesGenerationStrategy` 의 역할에 대해서 살펴보면 현재 단순 `Lottery` 로 mapping 해주는 것 외에는 비즈니스 로직이 존재하지 않습니다.
`RandomLotteriesGenerationStrategy` 의 경우엔 랜덤이라는 비즈니스 로직이 존재하지만,
List<List<Int>> -> List<Lottery> 과정에서 과연 `ManualLotteriesGenerationStrategy` 가 정말 필요한가? 에 대해 생각해보아도 좋을 것 같아요 👍 
어차피 검증로직은 Lottery에 존재하니까요

2024-03-05 16:13 UTC, KwonDae approved these changes
2단계에서 여러번 요청드렸음에도 불구하고 끝까지 피드백 반영해주시느라 고생많으셨습니다.
꼼꼼하게 의견을 달아주시고 마지막까지 리펙토링 하는 과정에서 점점 성장하고 있음을 느낄 수 있었습니다 👍 
다음 블랙잭 미션에서도 이런 경험들이 도움이 되기를 바라며
로또미션은 여기서 마무리 하겠습니다.
도움이 될만한 코멘트를 남겼으니 천천히 읽어봐주시기를 바랄게요.
다음 미션도 화이팅입니다 💪

2024-03-05 16:13 UTC, KwonDae commented on src/main/kotlin/lotto/view/InputView.kt
> +        return readManualLottery()
> 수동 로또 수가 45 초과일 때 재시도 로직을 어디서 수행해야할 지 감을 못 잡아서

이런 과정을 통해 로직 수행의 제어권에 대한 생각을 해보게 되었네요 👍 
`단순 예외를 던지는 것과 null 을 반환하는 것이 어떤 차이`가 있는지 알아보았으면 하는 생각이었습니다.
물론 500원을 입력받는다거나 로또 번호 범위를 벗어난 숫자를 입력했을 때 구현에 따라 프로그램이 비정상으로 동작하지 않도록 `require()` 를 활용해 예외를 던져서 논리 오류를 막고 있었습니다.

그렇다면 논리 오류를 막고 있었기에, 여기서 발생하는 예외처리를 할 수 있는 방법에 대해서 생각해보면

1. 미션에서 제시한 것 처럼 null 을 반환하여 잘못된 값이 전달됐다고 프로그램 내에서 "룰"을 만들 수 있다.
2. 다시 입력값을 받도록 처리한다.

현재는 2번을 선택해주셨는데, 만약 요구사항이 변경되어 예외상황에 대한 추가 로직이 필요할 때 현재로서는 InputView 에 코드를 추가하여 view에서 비즈니스 로직을 처리하게 될겁니다. 결국 MVC 패턴 구조의 장점이 사라지게 되겠죠.

이것은 `예외가 발생했을 때의 처리 제어권`을 어디로 위임할거냐로 볼 수 있습니다.
예외상황이 발생했을 때 이곳처럼 다시 해당 함수를 호출하는 상황에서는 Controller가 개입을 할 수 없습니다.

1차적으로 InputView에서 숫자로 이루어졌는지 확인을 한 후,
LotteryNumber 로 wrapping 하는 과정에서 LotteryNumber 의 `require()` 에서 뱉는 예외가 발생한다면
Controller에게 null 을 반환하여 Controller 에서 null 에 대한 처리를 하게끔 제어권을 넘겨주는건 어떨까요?

Controller 에서는 검증을 따로 안해도 되니 방대해지지 않고, 예외상황에 대한 대처만 어떻게 할지 노선을 정해주면 되겠죠
왜 코틀린에서 예외가 발생할 경우 null을 반환하는 방식을 사용하고 있는지 한번 생각해보셔도 도움이 될 것 같습니다.
결론은 예외 처리에 대해 정답은 없습니다. 위에서 말했듯이 프로그램 내에서 Null을 반환해도, 예외를 던져 처리하든 정답은 없지만 다양한 경험을 통해 해당 방법들의 차이점을 알고 어떤 방식이 나에게 맞는 스타일인지 이후 미션에서도 찾아갔으면 좋겠습니다.

또한, 위의 내용은 [Kotlin 에서 왜 Checked Exception을 제공하지 않는지](https://kth990303.tistory.com/393)와도 관련이 있습니다.
함께 참고해보세요 👍
[참고글1](https://elizarov.medium.com/kotlin-and-exceptions-8062f589d07)
[참고글2](https://kotlinlang.org/docs/exceptions.html)

2024-03-05 16:18 UTC, merged

2024-03-05 16:26 UTC, KwonDae commented on src/test/kotlin/lotto/model/winning/WinningResultTest.kt
> +            )
참고로 테스트에 Test Fixture 라는 개념이 있습니다.
이는 여러 테스트에서 같은 Data를 사용할 때, 코드 중복을 피하면서 가독성을 높이는 방법인데요
[참고하면 좋은 글](https://tjdtls690.github.io/studycontents/java/2022-10-10-test_fixture/)이 있어 공유드립니다.

2024-03-11 16:44 UTC, hxeyexn commented on src/main/kotlin/lotto/view/InputView.kt
> +    fun readManualLotteries(manualLotteryCount: ManualLotteryCount): List<List<String>> {
돌이켜보니 `RandomLotteriesGenerationStrategy` 와 `ExplicitLotteriesGenerationStrategy` 만으로 전략패턴을 사용한 이유가 충분한 데, 전략 패턴을 사용했으니 꼭 이걸 수동 로또에도 이용해야겠다는 생각에 갇혀있었던 것 같습니다. 개발도 상황에 따라 유연하게 사고하는 게 정말 중요한 것 같습니다 ㅠㅠ `ManualLotteriesGenerationStrategy`의 존재에 대해 다시 한번 생각해 보게 되었습니다. 감사합니다!